### ISSUE TITLE
Basic Map in root doesn't work

### ISSUE THREAD

**Issue by chonthu** [go-yaml/yaml#101]
example:

<pre>

---
- k: val
  k2: val2
</pre>

error: yaml: line 1: did not find expected key

**Comment by blubberdiblub** [comment]
It's probably because your YAML document has a sequence (indicated by the hyphen) as top level element, not a map. Does it work if you try to `Unmarshal()` it into a `[]interface{}` or `[]map[string]interface{}`?

**Comment by chonthu** [comment]
It does not, unfortunately

**Comment by dmage** [comment]
```
package main

import (
    "gopkg.in/yaml.v2"
    "log"
)

func main() {
    data := []byte(`---
- k: val
  k2: val2
`)
    var out []map[string]interface{}
    err := yaml.Unmarshal(data, &out)
    if err != nil {
        log.Fatal(err)
    }
    log.Printf("%+v", out)
}
```

Output:

```
2016/02/02 23:03:20 [map[k:val k2:val2]]
```

Looks good, don't you?

**Comment by chonthu** [comment]
:+1:
