### ISSUE TITLE
Untagged field names "y" and "n" marshalled with quotes, others not

### ISSUE THREAD

**Issue by TLINDEN** [go-yaml/yaml#1020]
```go
package main

import (
  "fmt"
  "image"
  "gopkg.in/yaml.v3"
)

func main() {
  p := image.Point{4, 5}
  bytetree, _ := yaml.Marshal(p)
  fmt.Println(string(bytetree))
}
```

prints:
```default
x: 4
"y": 5
```

It doesn't matter if it is an upper or lower case `y`. The letters `n` and `N` are also affected.

That comes really unexpected. Looks like some strange interpretation of `y` as `yes` and `n` as `no` - but why the quotes?

best regards,
Tom

**Comment by stavros-k** [comment]
I don't thing this is a bug.
https://yaml.org/type/bool.html

**Comment by TLINDEN** [comment]
I see.

I understand it for values, as in `enable: yes` which should become `enable: true`. But why would anyone do this with keys? Doesn't make any sense to me.

So now I have to add a function to my code to remove the quotes in such cases, because I use YAML only for pretty printing of arbitrary structs.

:angry:

**Comment by stavros-k** [comment]
I've seen a fair share of weird things people do in yaml. I do agree that keys shouldn't be treated as values. I haven't read up on the yaml spec to the fullest, so I'm not sure if this is "by spec" or not. I just stumbled upon your issue by "accident". Hope someone more well versed in the spec can chime in

**Comment by TLINDEN** [comment]
It's worse than just adding quotes, it also removes keys from the struct:
```go
	type Punkt struct {
		y, YES, yes int
	}

	po := Punkt{4, 6, 8}
	by, _ := yaml.Marshal(po)
	fmt.Println(string(by))
	
	fmt.Printf("Punkt: %#v", po)
```

Prints:
```default
"yes": 6

Punkt: main.Punkt{y:4, YES:6, yes:8}
```

**Comment by TLINDEN** [comment]
Also keys are being removed, note that the key `YES` is missing as well.

I need to try to get rid of YAML.

I am developing configuration modules for more than 25 years (e.g.  Config::General for perl) and never - NEVER!  - did it come to my mind to remove whole configuration keys. Manipulating the values: yes, I even have the very same "yes|on|enabled" feature in Config::General. But the keys?! No. No. No. HELL NOOOOO!!!

And the bad new is: I can't switch to TOML either: https://github.com/pelletier/go-toml/issues/932 :(

What a freaking mess.

**Comment by perlpunk** [comment]
1. YAML is a data serialization language. Mapping keys can be strings, numbers, null, booleans and even mappings or sequences as well. Not every language can implement this, but a boolean as a mapping key is totally valid in YAML, even if you don't see a use case for it
2.. go-yaml implements YAML 1.1, where `y` and `n` are booleans. in YAML 1.2 the list of scalars that are recognized as booleans has been reduced drastically, along with some [other changes](https://perlpunk.github.io/yaml-test-schema/schemas.html). More and more YAML libraries are slowly picking this up, but it is still not very well known by users.

**Comment by TLINDEN** [comment]
Thanks for the clarification. I already put a workaround into my module, since I am only using YAML as data dumper/visualization tool.
