### ISSUE TITLE
YAML parsing is not as expected

### ISSUE THREAD

**Issue by RedCrazyGhost** [go-yaml/yaml#1024]
In theory, data in json format should not be parsed into data in a structure.

<img width="656" alt="image" src="https://github.com/go-yaml/yaml/assets/49381700/cf5d76ca-a0ad-46e2-bd49-adc901c24b83">

This problem was discovered when I was writing gin test cases. (See [Issue](https://github.com/gin-gonic/gin/issues/3862))

**Comment by adriant-ntc** [comment]
This sounds correct?

YAML (from 1.2 onward at least) is supposed to be a [superset of JSON](https://yaml.org/spec/1.2.0/#id2558778), so it makes sense that this would parse.

**Comment by RedCrazyGhost** [comment]
That's right. I saw something similar at Red Hat
[Red Hat - What is YAML?](https://www.redhat.com/en/topics/automation/what-is-yaml)
