### ISSUE TITLE
Module abandoned?

### ISSUE THREAD

**Issue by andig** [go-yaml/yaml#1034]
This module has a number of good quality PR that slowly get bit-rodden. The last update (the unfortunate 1 billion dollar mistake) is two years old. It is not clear, if this module is still being maintained (seems it isn't).

It would be great to get an update on the state of this module and worst case lay grounds for a coordinated fork.

/cc @niemeyer 

**Update** note there is https://github.com/goccy/go-yaml as maintained and 1k-starred alternative.

**Comment by yxxhero** [comment]
any news?

**Comment by andig** [comment]
I've tried reaching out to @niemeyer on email but no luck.

**Comment by niemeyer** [comment]
It's not abandoned, but maintenance is unfortunately behind while my daily attention is elsewhere, as has been stated a few times here. My goal is to move the project under a team at Canonical, but it's not there yet.

**Comment by andig** [comment]
Thank you for the response @niemeyer, much appreciated. I was not aware this has been stated already. Maybe leave the issue open for better discoverability? 

I realise how much effort it is to maintain such a widely-used project. This module is imho one of the basic building blocks of many Go applications and has little existing alternatives. It would be great- while the transition is ongoing- to get bugs and maybe obvious, self-contained features (like https://github.com/go-yaml/yaml/pull/901?) addressed.
