### ISSUE TITLE
~ Null handled incorrectly for *string

### ISSUE THREAD

**Issue by zstewar1** [go-yaml/yaml#109]
When decoding into a *string, null is handled correctly, but ~ is not.

To confirm this, I added the following two tests to `unmarshalTests` in decode_test.go:

``` go
{
    "canonical: ~",
    map[string]*string{"canonical": nil},
}, {
    "english: null",
    map[string]*string{"english": nil},
},
```

The first test fails, but the second test passes. My understanding was that `~` and `null` are semantically equivalent in yaml.

**Comment by niemeyer** [comment]
Hi Zachary,

It's not clear what is happening there, but we have had these exact lines in decode_test.go for a very long time, and tests pass fine:

https://github.com/go-yaml/yaml/blob/v2/decode_test.go#L142

Do tests pass for you if you don't change anything?

**Comment by niemeyer** [comment]
Sorry, your example uses pointers as values rather than `interface{}`, so I went ahead and copied your lines into the test file. They still pass.

Is your code up to date?

**Comment by zstewar1** [comment]
I tried again on a different machine, and still go the same result. I'm using a freshly-pulled version of the repository on master (7ad95dd0798a40da1ccdff6dff35fd177b5edf40) with go 1.4.2. My bash output and patch file are shown below, if they help.

One thing that I find strange is that even after I added 6 new tests (to see whether this is just a problem with `*string`, or pointers in general), the output from `go test` still only says it ran 21 tests. Does the test runner only run the first 21 tests for some reason?

``` bash
zachary $ go version
go version go1.4.2 linux/amd64
zachary $ export GOPATH=~/yaml-test/
zachary $ go get gopkg.in/yaml.v2
zachary $ go get gopkg.in/check.v1
zachary $ cd ~/yaml-test/src/gopkg.in/yaml.v2
zachary $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
zachary $ git show --name-only
commit 7ad95dd0798a40da1ccdff6dff35fd177b5edf40
Author: Gustavo Niemeyer <gustavo@niemeyer.net>
Date:   Wed Jun 24 11:29:02 2015 +0100

    Fix omitempty support for floats.

encode_test.go
yaml.go
zachary $ go test
OK: 21 passed
PASS
ok      gopkg.in/yaml.v2    0.015s
zachary $ patch decode_test.go < ~/decode_test.patch 
patching file decode_test.go
zachary $ go test

----------------------------------------------------------------------
FAIL: decode_test.go:596: S.TestUnmarshal

decode_test.go:617:
    c.Assert(value, DeepEquals, item.value)
... obtained map[string]*string = map[string]*string{"canonical":(*string)(0xc2080a2140)}
... expected map[string]*string = map[string]*string{"canonical":(*string)(nil)}

OOPS: 20 passed, 1 FAILED
--- FAIL: Test (0.01s)
FAIL
exit status 1
FAIL    gopkg.in/yaml.v2    0.014s
zachary $ 
```

``` diff
--- gopkg.in/yaml.v2/decode_test.go 2015-06-25 09:33:53.192381256 -0700
+++ decode_test.go  2015-06-25 09:42:41.837811088 -0700
@@ -152,6 +152,27 @@
        map[string]*bool{"empty": nil},
    },

+   // For issue 109
+   {
+       "canonical: ~",
+       map[string]*string{"canonical": nil},
+   }, {
+       "english: null",
+       map[string]*string{"english": nil},
+   }, {
+       "canonical: ~",
+       map[string]*int{"canonical": nil},
+   }, {
+       "english: null",
+       map[string]*int{"english": nil},
+   }, {
+       "canonical: ~",
+       map[string]*struct{}{"canonical": nil},
+   }, {
+       "english: null",
+       map[string]*struct{}{"english": nil},
+   },
+   
    // Flow sequence
    {
        "seq: [A,B]",
```

**Comment by niemeyer** [comment]
Sorry, I can reproduce the bug. I did that in a rush yesterday and tested on yaml.v1 instead of yaml.v2.

I will fix that, thanks.

**Comment by niemeyer** [comment]
Regarding the number of tests, you didn't actually add a new test. You added an entry to a slice that is used by one of the tests.

**Comment by zstewar1** [comment]
Ah, I see.

Anyway, thanks for being responsive.

**Comment by fschuetz04** [comment]
A change to solve this issue is suggested in #265, I'll probably open a pull request.
