### ISSUE TITLE
Double quote on "On/Off/True" etc.

### ISSUE THREAD

**Issue by imcom** [go-yaml/yaml#115]
I am just wondering, given the following code snippet

in resolve.go:

```
        {true, yaml_BOOL_TAG, []string{"y", "Y", "yes", "Yes", "YES"}},
        {true, yaml_BOOL_TAG, []string{"true", "True", "TRUE"}},
        {true, yaml_BOOL_TAG, []string{"on", "On", "ON"}},
        {false, yaml_BOOL_TAG, []string{"n", "N", "no", "No", "NO"}},
        {false, yaml_BOOL_TAG, []string{"false", "False", "FALSE"}},
        {false, yaml_BOOL_TAG, []string{"off", "Off", "OFF"}},
```

in encode.go:240L:

```
if rtag == yaml_BINARY_TAG {
        if tag == "" || tag == yaml_STR_TAG {
            tag = rtag
            s = rs.(string)
        } else if tag == yaml_BINARY_TAG {
            failf("explicitly tagged !!binary data must be base64-encoded")
        } else {
            failf("cannot marshal invalid UTF-8 data as %s", shortTag(tag))
        }
    }
```

The strings "on, On, off, Off ..." etc. listed above will be surrounded by double quote when marshalled.

Is that the expected behaviour? I find that kind of strange cuz I find that I can't change that encode behaviour by giving params and the double quote seems is of no particular usage ...

Can someone kindly explain that a little bit?

**Comment by niemeyer** [comment]
Yes, this is expected behavior because these values are generally interpreted as boolean, per the YAML specification. If you don't quote them, they mean something else.
