### ISSUE TITLE
License. Can I include source code in my repository?

### ISSUE THREAD

**Issue by aramalipoor** [go-yaml/yaml#118]
We're using this amazing library in our [farmer-project](https://github.com/farmer-project/farmer).

Is it possible to include this library in our repository source codes, and use import paths like `github.com/farmer-project/farmer/vendor/src/gopkg.in/yaml.v2`?

**Comment by niemeyer** [comment]
Yes, the license does allow you to do that. Please refer to the LICENSE and LICENSE.libyaml file for full details on what's accepted or not.
