### ISSUE TITLE
Feature request: json.Marshal compatibility

### ISSUE THREAD

**Issue by christophercurrie** [go-yaml/yaml#12]
I'd love to incrementally upgrade the use of JSON to YAML for config files in my projects, but to do that I'd have to add "yaml" tags to all of my structs so that they match the "json" tags.

It would be great to have an unmarshalling mode that uses the json packages defaults (Upper case keys) and reads the "json" tags from structs, so I can use go-yaml as a drop in replacement until the config files can be rewritten.

**Comment by ghost** [comment]
On the topic of compatibility, if maps should be map[string]interface{} instead of map[interface{}]interface{}, that would be most helpful.  At the moment, they aren't, which deviates from the behavior of encoding/json.

**Comment by niemeyer** [comment]
I have originally advocated having a generic "key" tag that would be used by multiple packages, but the core Go team favored an approach where each package would have its own namespace. The yaml package is following that recommended convention.

In terms of the type of maps, yaml accepts non-string keys, which json does not, so both packages are correct with the respective types.
