### ISSUE TITLE
Curious what's the motivation for the lowercasing behavior

### ISSUE THREAD

**Issue by nathanleclaire** [go-yaml/yaml#120]
It caught me kind of off guard that the unmarshalled fields are assumed to be lowercase, especially as the exported fields in Golang have to start with caps:

> Struct fields are only unmarshalled if they are exported (have an upper case first letter), and are unmarshalled using the field name lowercased as the default key.

I'm curious what the motivation for the automatic lowercasing behavior is?  Is it a YAML thing?  It's not really a problem for me, it's just surprising and I can't figure out from Googling around why it is done this way.  I see no mention of YAML requiring keys to start with lowercase, but I admit I haven't researched extensively.

**Comment by niemeyer** [comment]
The original idea was to match the most popular format for yaml files, which is by far lowercase fields. If I had to do it again, I'd probably have followed what is now the most common convention, but it's a bit late to change this now. Keeping people's code working is more important.

**Comment by nathanleclaire** [comment]
> I'd probably have followed what is now the most common convention, but it's a bit late to change this now. Keeping people's code working is more important.

Sure, no problem, thanks for the reply!
