### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by fgrosse** [go-yaml/yaml#121]
When given a string that contains escaped characters I would expect the decoding library to remove the escape codes when unmarshalling into the target type.

Here an examplatory test to show what I mean:

``` go
package fgrosse_test

import (
    "testing"
    "gopkg.in/yaml.v2"
)

func TestYamlEscaping(t *testing.T) {
    input := `This is a string containing an escaped \@`
    expected := "This is a string containing an escaped @"

    var actual string
    if err := yaml.Unmarshal([]byte(input), &actual); err != nil {
        t.Errorf(err.Error())
    }

    if actual != expected {
        t.Errorf(`Expected "%s" but got "%s"`, expected, actual)
    }
}
```

Output:

```
--- FAIL: TestYamlEscaping (0.00s)
    yaml_test.go:18: Expected "This is a string containing an escaped @" but got "This is a string containing an escaped \@"
FAIL
exit status 1
FAIL    github.com/fgrosse  0.002s
```

**Comment by niemeyer** [comment]
The assumption isn't valid in two different ways:
1. The `\@` string is not a valid escape sequence. If you try to decode this, it must error out.
2. yaml only interprets escape sequences inside double quoted strings. Per [the spec](http://www.yaml.org/spec/1.2/spec.html#id2776092):

> Note that escape sequences are only interpreted in double-quoted scalars. In all other scalar styles, the “\” character has no special meaning and non-printable characters are not available.

**Comment by fgrosse** [comment]
Oh I didnt know there is no way I can use `@` in an unquoted string
Thanks for clearing that up :)

**Comment by niemeyer** [comment]
If that was true the error message out of your example would not contain that character.
