### ISSUE TITLE
Automated build

### ISSUE THREAD

**Issue by jsha** [go-yaml/yaml#127]
I notice this project doesn't appear to have an automated build integration (e.g. Travis). Would you accept a PR to add one? It would also require a small amount of setup on the travis-ci.org web site.

**Comment by niemeyer** [comment]
Last I looked Travis required custom access to my projects for being able to build them, which doesn't sound entirely reasonable. Has that changed?

**Comment by jsha** [comment]
It needs to be added as a Service Hook (
https://developer.github.com/webhooks/#service-hooks), which means GitHub
notifies it on pushes and pull requests, but it does not get access to
modify your repository.​

**Comment by niemeyer** [comment]
We have travis for quite a while now. Closing this.
