### ISSUE TITLE
Relicense to MIT

### ISSUE THREAD

**Issue by ibuildthecloud** [go-yaml/yaml#135]
libyaml is MIT but this project is LGPL.  Even with the exceptions added to the license the LGPL license is causing legal issues for some projects I'm involved with.  Is there any chance you would consider re-licensing this project to MIT to match the original libyaml license?  I have no ability to convince lawyers so my only choice at this point is to not use this project if it stays LGPL.  Re-licensing would be greatly appreciated as I have very much enjoyed using your work.  Thanks

**Comment by niemeyer** [comment]
Changing it on my side would also involve talking to lawyers, so without any proper reasoning other than "they don't like LGPL" I'm somewhat empty-handed to get into that conversation on my side.

**Comment by ibuildthecloud** [comment]
Okay, fair enough.

**Comment by niemeyer** [comment]
After much internal debate, we've finally managed to get agreement to move the license towards the Apache License v2. Reopening #160 until the license lands.
