### ISSUE TITLE
decoder silently ignores fields in the yaml-input for which no field in the struct-type exists. 

### ISSUE THREAD

**Issue by oec** [go-yaml/yaml#136]
If I have a struct

```
   type T struct {
      A string
   }
```

and use the following string as input:

```
   data := "a: foo\nb: bar\n"
```

then the call to yaml.Unmarshal

```
  t := &T{}
  e := yaml.Unmarshal(data, t)
  ...
```

will succeed without error and thereby silently ignore field "b" in the input.

I consider this behaviour a bug, as it doesn't allow f.e. to catch misspellings in config-files.

In my project I fixed this with the following patch for decode.go:

```
--- decode.go   2015-10-18 17:55:27.332842372 +0200
+++ my/decode.go    2015-10-18 17:14:26.421462484 +0200
@@ -640,6 +640,9 @@
            value := reflect.New(elemType).Elem()
            d.unmarshal(n.children[i+1], value)
            inlineMap.SetMapIndex(name, value)
+       } else {
+           d.terrors = append(d.terrors, fmt.Sprintf("line %d: no such field '%s' in struct '%s'", n.line+1, name, out.Type()))
+           return false
        }
    }
    return true

```

**Comment by oec** [comment]
Of course, another - more complex - patch would be to implement something similar as the ",any"-tag in encoding/xml.  Unmarshaling into struct _without_ a field with that tag would silently ignore extra fields in the input (as it is now).  A field of type map[string]interface{} with the tag ",any" could serve as a catch-all and consumers could decide what to do with it.

**Comment by abligh** [comment]
+1 - at least an option to error this would be good.

**Comment by wfarner** [comment]
Are there any plans to accept the above patch, possibly with added plumbing to make the behavior optional/non-default?  Happy to pitch in.

**Comment by niemeyer** [comment]
Erroring in that case would be unacceptable, but we can do something similar to what I've used elsewhere: support the inline tag in maps too. This is useful in a number of cases as it allows mixing previously known key with custom ones, and if you want to error when the map is not empty that's easy too.

**Comment by wfarner** [comment]
@niemeyer can you elaborate?  I'm not following how inlining maps helps to address the use case @oec demonstrated in the original issue filing.

**Comment by vincentbernat** [comment]
Is there a known workaround for this bug/feature?

**Comment by douglaswth** [comment]
@vincentbernat there's my branch with these changes: #146.

**Comment by vincentbernat** [comment]
@douglaswth Thanks! I was hoping there would be a way to do that without a modified version. I have tried to extract all the keys and check if there are unknown ones, but this requires some reflection and redo the work already done by this package to correctly parse tags.

**Comment by niemeyer** [comment]
@vincentbernat The real solution for that is inline maps, as suggested above. Didn't get to it yet, sorry.

**Comment by atombender** [comment]
Can we get this merged? The inline map solution isn't great because it moves the burden of error checking to the target struct. When you have a bunch of structs, this becomes onerous to have to implement a `UnmarshalYAML` that checks for unknown keys.

As far as I can tell, there's no way to create a helper struct (e.g. `StrictKeys`) that cleanly implements `UnmarshalYAML`, since it requires a type alias to avoid recursive unmarshaling. Might be possible using reflection, but I'd like to avoid that.

**Comment by atombender** [comment]
@oec Why did you close this?

**Comment by niemeyer** [comment]
@atombender See the linked PR above. The feature is supported.

**Comment by atombender** [comment]
@niemeyer Thanks. This wasn't clear, since the PR doesn't reference this issue.
