### ISSUE TITLE
Change default map to map[string]interface{} instead map[interface{}]interface{}

### ISSUE THREAD

**Issue by aanm** [go-yaml/yaml#137]
https://github.com/go-yaml/yaml/blob/v2/decode.go#L199

After reading from a yml file I can't marshal as json since I get `json: unsupported type: map[interface {}]interface {}`. Is it possible to change the default map to map[string]interface{} instead map[interface{}]interface{}?

**Comment by niemeyer** [comment]
Unfortunately not.. Unlike json, yaml can take keys of arbitrary types.

**Comment by sparkprime** [comment]
Most YAML parsers don't support that as it's incompatible with JSON.  I've never seen it used in practice.

**Comment by MissingRoberto** [comment]
+1
