### ISSUE TITLE
how to parse semi-structured YAML?

### ISSUE THREAD

**Issue by RichMorin** [go-yaml/yaml#14]
I've been using YAML for about a decade, using parsers written in Perl, Ruby, and (most recently) Julia.  In all of these, the parser reads the YAML text and creates a corresponding data structure. It appears, however, that the Go parser needs to have the structure laid out in advance before it can parse the file.  Say what?

YAML is really good at encoding semi-structured data (eg, ASTs). How am I supposed to know the exact structure of this sort of file, at compile time?  Am I missing something?

-r

**Comment by RichMorin** [comment]
In my current use case, the input file looks like this:

```
Predicates:
# ns_name                             P  PT  I  Expansion
  owl_disjointWith:                 [ _, __, _, 'disjoint with' ]
  owl_equivalentClass:              [ _, __, _, 'equivalent class' ]
...
```

So, I guess I can use a type such as this:  type  T map[string] map[string] []string
However, in some cases, I may not know in advance how many levels are involved.

**Comment by 0x7061** [comment]
I'm not sure if I fully understood your question but if you don't know the exact structure you can parse it into a map (associative array) like so:

```
m := make(map[interface{}]interface{})
err = yaml.Unmarshal([]byte(data), &m)
```
