### ISSUE TITLE
Nested keys tags

### ISSUE THREAD

**Issue by josephbuchma** [go-yaml/yaml#145]
Consider this yaml with some configs: 

``` yaml
hub_config: 
    api_key: "somekey"

```

All I need is `api_key`. I'd like to be able to unmarshal it using tag like this

``` go
type AppConfig struct {
    ApiKey string `yaml:"hub_config.api_key"`
}
```

**Comment by niemeyer** [comment]
No plans to support this at the moment, sorry.
