### ISSUE TITLE
Default decoding/encoding behaviour is surprising for a Go library

### ISSUE THREAD

**Issue by samsalisbury** [go-yaml/yaml#148]
I was very surprised to find that `Unmarshal` _by default_ assumes that my exported, Uppercased struct field names should only be unmarshalled if they are different in the YAML file (that is, if they are lowercased there).

Surely, if a user wants to use a different field name in their YAML vs Go code, they should use the field tags to indicate this. Having this magic case switching _just happen_ feels very odd, especially when this is compared with the built-in `encoding/json` package, which does not do any such magic.

I guess it's too late to change this for v2, as it would be a breaking change. However adding a func to disable this behaviour on an opt-in basis would be very useful indeed.

Note that this is a different issue from https://github.com/go-yaml/yaml/issues/123 because once you have used the field tags to specify specific names, I don't see why the parser should perform any additional case-insensitive magic unless somehow told to.

**Comment by niemeyer** [comment]
Please see #120 for motivation details. Will comment on the PR too.
