### ISSUE TITLE
Validating yaml upon unmarshalling

### ISSUE THREAD

**Issue by thockin** [go-yaml/yaml#15]
We have some yaml data which we parse and want to validate.  In this context, validate generally means:
- check required fields are present
- check formatting of strings (regex)
- set default values (if y is not specified, default to value 123 or "same as another field")

I find the Setter interface, but I just don't grok what to do with it (still sort of new to Go).  What is the value when I am implementing SetYAML() on a multi-field structure?  Is there an example of this?  Or do people just open code the validation logic for complex types?

**Comment by gravis** [comment]
btw, Unmarshal API is broken, it's never returning an error:

https://github.com/go-yaml/yaml/blob/1ff37a7d30b085dc643dee7adb18759e3511661a/yaml.go#L87

:)

**Comment by rogpeppe** [comment]
On 26 June 2014 22:13, Philippe Lafoucrière notifications@github.com wrote:

> btw, Unmarshal API is broken, it's never returning an error:
> 
> https://github.com/go
> -yaml/yaml/blob/1ff37a7d30b085dc643dee7adb18759e3511661a/yaml.go#L87
> 
> :)

That's not true. See the handleErr function.

**Comment by gravis** [comment]
Indeed, sorry :)

**Comment by niemeyer** [comment]
@thockin The value you get into SetYAML corresponds exactly to the value that is in the YAML document in the position of the respective field. We have another issue open to improve the documentation there, but either way the best way to learn how to use it is to play a bit with the method and some data.

**Comment by niemeyer** [comment]
Ah, and in terms of validation of content, that's outside the scope for the yaml package. There are packages for dealing just with that problem alone, though. For example: https://github.com/juju/schema
