### ISSUE TITLE
Make parser API public

### ISSUE THREAD

**Issue by nati** [go-yaml/yaml#158]
Hi folks

I'm using YAML as a macro language (eg Ansible). 
I need line number for each YAML nodes, so that I can use it in logging or error message.

Do this project is positive to make parser API public? if so, I'll send PR.

**Comment by ndeloof** [comment]
+1 on this
go-yaml has a well defined separation between parser and decoder. 

On https://github.com/compose-spec/compose-go I'd like to be able to wrap the decoder so I can manage some transformation on nodes (typically, interpolate `"$FOO"` set as node value based on environment variables).

**Comment by niemeyer** [comment]
Good news then! This is all public by now. Just have a look at v3: https://gopkg.in/yaml.v3

**Comment by ndeloof** [comment]
yaml.v3 indeed defines `Node.Decode` but I can't find a way to obtain a `parser` and/or invoke `parse` to obtain yaml tree root `Node`. Did I miss something?
