### ISSUE TITLE
Tests failing with go 1.6 (go 1.5.3 fine)

### ISSUE THREAD

**Issue by ebrady** [go-yaml/yaml#159]
I noticed this… basically set a fresh GOPATH and pulled just yaml.v2 and check.v1 via 'go get' (just a minute ago)… and tried 'go test' in gopkg.in/yaml.v2 and it fails when pointing at Go 1.6… then below that I point at Go 1.5.3 and it works:

NOTE: below shows a redhat Linux box but I saw the same thing on my Mac OS X 10.10.5 box

0 ✓ ~/ark/test1/src% find . -name ".git" -print
./gopkg.in/yaml.v2/.git
./gopkg.in/check.v1/.git
0 ✓  ~/ark/test1/src% cd gopkg.in/yaml.v2
0 ✓  ~/ark/test1/src/gopkg.in/yaml.v2% go test

---

FAIL: encode_test.go:327: S.TestMarshal

encode_test.go:333:
    c.Assert(string(data), Equals, item.data)
... obtained string = "" +
...     "a: 1\n" +
...     "b: 2\n"
... expected string = "" +
...     "a: 1\n" +
...     "b: 2\n" +
...     "c: 3\n"

---

FAIL: encode_test.go:355: S.TestMarshalErrors

encode_test.go:358:
    c.Assert(func() { yaml.Marshal(item.value) }, PanicMatches, item.panic)
... function func() = (func())(0x4c7c40)
... expected string = "Duplicated key 'b' in struct struct \{ B int; .*"
... Function has not panicked

---

FAIL: decode_test.go:597: S.TestUnmarshal

decode_test.go:618:
    c.Assert(value, DeepEquals, item.value)
... obtained *struct { A int; C yaml_test.inlineB "yaml:\",inline\"" } = &struct { A int; C yaml_test.inlineB "yaml:\",inline\"" }{A:1, C:yaml_test.inlineB{B:2, inlineC:yaml_test.inlineC{C:0}}}
... expected *struct { A int; C yaml_test.inlineB "yaml:\",inline\"" } = &struct { A int; C yaml_test.inlineB "yaml:\",inline\"" }{A:1, C:yaml_test.inlineB{B:2, inlineC:yaml_test.inlineC{C:3}}}

OOPS: 18 passed, 3 FAILED
--- FAIL: Test (0.02s)
FAIL
exit status 1
FAIL    gopkg.in/yaml.v2    0.020s
1 ✗  ~/ark/test1/src/gopkg.in/yaml.v2% go version
go version go1.6 linux/amd64
0 ✓  ~/ark/test1/src/gopkg.in/yaml.v2% export GOROOT=/local/ark/pkg/go/1.5.3
0 ✓  ~/ark/test1/src/gopkg.in/yaml.v2% /local/ark/pkg/go/1.5.3/bin/go test
OK: 21 passed
PASS
ok      gopkg.in/yaml.v2    0.018s
0 ✓  ~/ark/test1/src/gopkg.in/yaml.v2%

Haven't had a chance to look much deeper but just noticed this failure as I tried out Go 1.6… perhaps I'm missing something though (?).

**Comment by ebrady** [comment]
This seems to be solved in this existing PR: "make compatible with Go 1.6 #152"

Once that's accepted (or something like it) this should go away it seems...

**Comment by advance512** [comment]
I've been trying to rebase advance512/yaml on the latest version, and I've noticed this too in my own fork. 
+1 merge in

**Comment by niemeyer** [comment]
This is already merged. Are you seeing any issues on the latest?
