### ISSUE TITLE
Possible to have multiple YAML names for a struct field

### ISSUE THREAD

**Issue by thockin** [go-yaml/yaml#16]
I have a struct with a field "Path" with a yaml: tag name "path".  For historical reasons, I want to accept YAML that sends either "path" or "mountPath" as the key.  Is it possible to do this without defining two fields in the struct?

**Comment by niemeyer** [comment]
That's not supported, but you can easily have two fields and copy the data from one to the other in application logic.

**Comment by thockin** [comment]
That's what I was trying to avoid doing. :-/

On Wed, Sep 17, 2014 at 11:32 AM, Gustavo Niemeyer <notifications@github.com

**Comment by niemeyer** [comment]
You do have two fields in the document, so there's no reason to avoid having two fields in the struct you are using to manipulate the document. This is application logic.
