### ISSUE TITLE
LICENSE LGPL

### ISSUE THREAD

**Issue by zubairhamed** [go-yaml/yaml#160]
Hi,

I know this was mentioned in Issue #135 however a good reason for changing might be that EPL and ASF-based projects do not allow including LGPL libraries.

http://www.apache.org/legal/resolved.html
https://eclipse.org/legal/eplfaq.php

Z

**Comment by tony** [comment]
Why pick a license more restrictive than golang and libyaml's C implementation?

The license isn't backwards compatible... You have to end up reinventing the wheel rewriting code under a portable license.

I recommend changing the license or contributing to a different project with a more permissive license. 2, 5, 10 years down the line, if you find your predicament isn't compatible with LGPL - you'll have no choice but to start over and write from scratch.

**Comment by tony** [comment]
As an update, I found an alternative, https://github.com/cloudfoundry-incubator/candiedyaml. docker/libcompose switch from this project to it in https://github.com/docker/libcompose/pull/91.

**Comment by niemeyer** [comment]
That's quite ironic. That project is a rip-off from go-yaml.. I can see parts that which were clearly "inspired" by go-yaml. If you are worried about licenses, you are switching from someone that is trying to support you to someone that is copying logic unlicensed.

Go for it. :-)

**Comment by niemeyer** [comment]
After much internal debate, we've finally managed to get agreement to move the license towards the Apache License v2. Reopening until the license lands.

**Comment by zubairhamed** [comment]
good to hear. hey i would appreciate it if you also state, whenever you can, if there were any specific steps you took to relicense this. I'm just curious to know if there are any specifics to changing the licenses of a project (other than the obvious license file change).

**Comment by niemeyer** [comment]
The main problem is being legally allowed to do so, which isn't something I can help you with in detail. As one point to observe, if you got contributions to your project without a license agreement that allows you to do that, you can't change the license without asking explicit permission to all of your contributors, because they implicitly licensed the work under that same license to you.

**Comment by hairyhenderson** [comment]
@niemeyer - good to hear the license is being changed! Are there any updates on the effort?

**Comment by niemeyer** [comment]
Just committed the text on e4d366f, apologies for the delay.
