### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by petercolberg** [go-yaml/yaml#167]
Please use semantic versioning:
- http://semver.org/
- https://en.wikipedia.org/wiki/Software_versioning
- https://wiki.debian.org/UpstreamGuide#Releases_and_Versions

**Comment by petercolberg** [comment]
Debian packages each Go package repository as a separate Debian source package. The version of a Debian package includes an upstream part (e.g. "1.0.0") and a Debian part (e.g. "-1"). If an upstream author does not tag releases, we need to make up an upstream version number based on the git commit and date, which yields unwieldy versions that are cumbersome to compare. 

All you would have to do is regularly tag releases, which yields handy Debian package versions and makes it easy to automatically [notice new upstream releases](https://tracker.debian.org/pkg/golang-gopkg-tylerb-graceful.v1) using the Debian package tracker.

**Comment by Nerdmaster** [comment]
Yes, and also consider tagging with the "v" prefix ("v1.0.0") - then tools like "gb" can pull stable releases without the need for gopkg.in (which I'm finding is down or unresponsive a lot more than github)

**Comment by akshayjshah** [comment]
This would be extremely helpful - I know that the authors of this package prefer the `gopkg.in` approach to versioning, but most of the community is converging on tagged releases.

**Comment by niemeyer** [comment]
Just tagged v2.2.0.
