### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by tj** [go-yaml/yaml#17]
would be awesome, it's not really clear what the flow option does etc, lots of trial and error to get it to unmarshal correctly for structs

**Comment by 0x7061** [comment]
+1 More examples would be great.

**Comment by HamOnBry** [comment]
+1 too for more examples

**Comment by luebken** [comment]
+1
(trying to parse a sequence)

**Comment by jackspirou** [comment]
+1 - More examples would be great.

What did help me was to first make a mock struct with example data relevant to what I was trying to do and then marshal/print it out.

**Comment by qwertmax** [comment]
+1

**Comment by niemeyer** [comment]
+1

Please consider submitting them in an examples_test.go file which is properly handled by godoc:

https://blog.golang.org/examples

**Comment by purpleidea** [comment]
+1 (since this seems to be a +1 fest :P -- an example to parse a list of different structs which fill the same interface would be welcomed! )

**Comment by vanloswang** [comment]
+1

**Comment by balanatarajan** [comment]
@tj  and @niemeyer : Willing to write examples here. Can one of you please help me with samples that would serve as examples? I plan to start off with examples in http://www.yaml.org/spec/1.2/spec.html#id2759572. I know that would be insufficient. Any examples of samples that you need would be appreciated

**Comment by niemeyer** [comment]
Closing this. The interface of the yaml package is pretty idiomatic in Go, and documented. Examples don't need to be hosted inside this repository.
