### ISSUE TITLE
go vet errors

### ISSUE THREAD

**Issue by ryboe** [go-yaml/yaml#172]
I rang `go vet ./...` on Go 1.6.2.

```
$ cd $GOPATH/src/github.com/go-yaml/yaml
$ go vet ./...
decode.go:123: unreachable code
emitterc.go:669: unreachable code
parserc.go:169: unreachable code
```

This is a problem for anyone vendoring `go-yaml`. When they run `go vet ./...` on their projects, it will scan the vendored `go-yaml` code as well.

**Comment by dmitris** [comment]
fixed in https://github.com/go-yaml/yaml/pull/181/files - @niemeyer , could you take a look, please - would you accept the PR?

**Comment by niemeyer** [comment]
Sorted out in #249.
