### ISSUE TITLE
Detecting undefined values is not possible(?)

### ISSUE THREAD

**Issue by purpleidea** [go-yaml/yaml#175]
I'd like to differentiate between a value in a yaml file that is missing (undefined) and set as the default value. Not sure how this can be done...

**Comment by niemeyer** [comment]
You can use a pointer or an interface{} so you can tell it was unset (nil).

**Comment by purpleidea** [comment]
@niemeyer Is there an example of this that you can point me to? Thanks in advance.

**Comment by niemeyer** [comment]
@purpleidea There isn't much to it, really.. if you have a field that is a pointer type (say, `*string`) the field isn't set if the field is missing from the input or set to YAML's `null`.
