### ISSUE TITLE
Improve docs for GetYAML and SetYAML

### ISSUE THREAD

**Issue by thockin** [go-yaml/yaml#18]
I've mostly figured it out, except for the "tag" return of GetYAML - what am I supposed to put there?

**Comment by niemeyer** [comment]
You are right, the documentation is definitely lacking. I'm sorry.

The tag is a YAML tag: http://yaml.org/spec/1.1/#id858600

Since you don't know what it is for, it means you probably don't care, so leaving it empty will likely produce the result you expect.

**Comment by thockin** [comment]
Ah!  I thought Tag was the key.  I did use "" and it did work, but I did
not know why.

On Thu, Jul 10, 2014 at 12:08 PM, Gustavo Niemeyer <notifications@github.com

**Comment by andrei-m** [comment]
+1 - I found this confusing as well.

**Comment by niemeyer** [comment]
Documentation and the interfaces themselves were improved in yaml.v2, as described in the announcement:

http://blog.labix.org/2014/09/22/announcing-yaml-v2-for-go
