### ISSUE TITLE
Can't get the package

### ISSUE THREAD

**Issue by esod** [go-yaml/yaml#180]
I can't get the package for some reason. My instructions are as follows:

![gopkg in](https://cloud.githubusercontent.com/assets/387576/15864614/c34127f6-2ca5-11e6-9a7f-adc7e574efa4.png)

in editable text:

```
$ cat /etc/issue
CentOS release 6.8 (Final)
Kernel \r on an \m

$ go version
go version go1.5 linux/amd64
$ export GOPATH=$HOME/go
$ go get gopkg.in/yaml.v2
^C$ 
$ 
$ su
Password: 
# export GOPATH=$HOME/go
# go get gopkg.in/yaml.v2
^C# 
```

What could be wrong?

**Comment by mrbuk** [comment]
Hey Eric,

I think this is related to the git version that CentOS 6.x is using (1.7.1). I fixed that issue on my CentOS machine by installing the newest git manually. See the following lines in my Dockerfile

from
 https://gist.github.com/mrbuk/8b0bb7a34391c8f67ce90c23db631b00#file-dockerfile-L19

to
https://gist.github.com/mrbuk/8b0bb7a34391c8f67ce90c23db631b00#file-dockerfile-L34

BR
Markus
