### ISSUE TITLE
License: LGPL or Apache?

### ISSUE THREAD

**Issue by starius** [go-yaml/yaml#188]
README.md says:

> The yaml package is licensed under the LGPL with an exception that allows it to be linked statically. Please see the LICENSE file for details.

LICENSE says:

> Licensed under the Apache License, Version 2.0 ...

Can one use this package under the terms of the Apache License, Version 2.0?
Can one change this package and distribute it in binary form only?

**Comment by justinclift** [comment]
As a thought, this looks related to #189.

**Comment by brosander** [comment]
[LGPL is a blocker for Apache projects.](http://www.apache.org/legal/resolved.html#category-x)

I'm exploring using this library but it would be awesome if #189 could be merged to clear up the ambiguity.

Thanks!

**Comment by niemeyer** [comment]
Done!

**Comment by brosander** [comment]
@niemeyer thank you sir 😄
