### ISSUE TITLE
`flow` tag on maps

### ISSUE THREAD

**Issue by liclac** [go-yaml/yaml#190]
It'd be very helpful to be able to specify the `flow` tag on map keys in some way, perhaps by wrapping it in another type.

Or is there a way to do this that I'm overlooking?

**Comment by niemeyer** [comment]
You can set it using a struct:
```
type YourType struct {
        YourMap map[string]interface{} `yaml:",flow"`
}
```
On v3 you'll also to set this dynamically to particular map keys. But that can't be done in v2 as it lacks the intermediate representation for that.

**Comment by niemeyer** [comment]
By the way, v3 is in progress, and is coming soon.
