### ISSUE TITLE
Marshaler incorrectly marshals date strings

### ISSUE THREAD

**Issue by autrilla** [go-yaml/yaml#192]
The marshaler should quote strings that have YAML's date format. For example, the go string "2006-01-02T15:04:05Z" should be marshaled as '2006-01-02T15:04:05Z', with the quotes, but is currently marshaled without quotes.

SSCCE:

```
package main

import (
    "fmt"
    "gopkg.in/yaml.v2"
)

func main() {
    m := make(map[string]string)
    m["foo"] = "2006-01-02T15:04:05Z"
    out, _ := yaml.Marshal(m)
    fmt.Println(string(out))
}
```

Should output:

`foo: '2006-01-02T15:04:05Z'`

But instead outputs

`foo: 2006-01-02T15:04:05Z`

**Comment by niemeyer** [comment]
Thanks for this.

**Comment by rogpeppe** [comment]
Given that YAML directly supports unquoted RFC3339 times, I think this is OK.
The marshaled YAML correctly unmarshals AFAICS.
Please re-open if this is still not OK.

**Comment by autrilla** [comment]
Yes, YAML supports unquoted times, but a Go string formatted like a time (e.g. `s := "2006-01-02T15:04:05Z"`) will be output as a YAML date (unquoted), not as a string. I don't think this silent type conversion is OK.

**Comment by rogpeppe** [comment]
@autrilla Thanks, I'd gone through this issue too quickly and missed that it wasn't a time being printed. Will fix, thanks.

**Comment by autrilla** [comment]
I opened a PR for this back in the day on https://github.com/go-yaml/yaml/pull/213 , it seems there's some merge conflicts now though. I'll see if I can get them fixed.

**Comment by niemeyer** [comment]
This case is already fixed.
