### ISSUE TITLE
Is it possible to add tag to force yaml string field to use | notion

### ISSUE THREAD

**Issue by meirwah** [go-yaml/yaml#197]
So I can do something like this:

``` go
type Example struct {
    Msg string `json:"changeStatus" yaml:"msg,pipe"`
}
```

so resulting yaml will be:

``` yml
msg: |
    value of msg
```

**Comment by niemeyer** [comment]
This is a "literal" string in yaml's spec. If you include a newline (\n) in your string, it will unmarshal like that.
