### ISSUE TITLE
unmarshalling list into an array doesn't work

### ISSUE THREAD

**Issue by robert-zaremba** [go-yaml/yaml#20]
I'm trying to unmarshall a list of 10 integers into `*[10]int{}` and it doesn't work. Array is not filled.

**Comment by niemeyer** [comment]
Yeah, arrays are not yet supported. Unmarshal into a slice ([]int) and it should be fine.

**Comment by robert-zaremba** [comment]
Yes, but it doesn't resolve the issue.

**Comment by niemeyer** [comment]
That's why it's still open.
