### ISSUE TITLE
when the field's tag define has json and yaml,  and json define at first, it will make the yaml marshal unexpected result

### ISSUE THREAD

**Issue by yacc2007** [go-yaml/yaml#250]
when the tag define such as json at first, it will marshal ipaddress, but which i want it is ip_address
```golang
type Test struct {
	IpAddress string `json:"ip_address", yaml:"ip_address"`
}

func main() {
	test := &Test{IpAddress:"123"}
	data, err := yaml.Marshal(test)
	fmt.Println(string(data), err)
	return
}
```
run result : ipaddress: "123"

but  i want the result is : ip_address:"123"

**Comment by pierrec** [comment]
The struct tag is invalid, it should be (no coma separating the various tags):
`json:"ip_address" yaml:"ip_address"`

**Comment by yacc2007** [comment]
thank you for reply
