### ISSUE TITLE
Marshaling a [2]uint results in a panic

### ISSUE THREAD

**Issue by paralin** [go-yaml/yaml#259]
I'm currently encountering the following panic:

```
panic: cannot marshal type: [2]uint [recovered]
        panic: cannot marshal type: [2]uint

goroutine 1 [running]:
github.com/go-yaml/yaml.handleErr(0xc420524818)
        /home/paralin/Documents/goworkspace/src/github.com/go-yaml/yaml/yaml.go:153 +0x95
```

Is it not reasonable that YAML should be able to handle unsigned integers?...

**Comment by paralin** [comment]
It seems the issue is that it doesn't know how to handle arrays of fixed length, I.e. `[2]uint`

**Comment by niemeyer** [comment]
That's been fixed by the commit above.
