### ISSUE TITLE
Multiple `omitempty` field tags

### ISSUE THREAD

**Issue by niedbalski** [go-yaml/yaml#26]
Defining more that 1 omitempty field tag, raises an error: Duplicated key 'omitempty' in struct core.Service. 

type Foo struct {
    Bar        string   `yaml:"a, omitempty"`
    Foo        string  `yaml:"b, omitempty"`
...

There is a technical reason for having this constraint?

**Comment by niemeyer** [comment]
You mean you have something like this:

```
Field Type `yaml:",omitempty,omitempty"`
```

?

That looks like a bogus declaration. Why would that be desirable?

**Comment by niedbalski** [comment]
Gustavo,

I updated the initial issue comment. Sorry for the bad explanation, but would be desirable to being able to have more than one field using the 'omitempty' flag on a structure.

**Comment by niemeyer** [comment]
Sorry, but I still don't understand what you mean. This works fine:

```
type Foo struct {
    Bar string `yaml:"a,omitempty"`
    Foo string `yaml:"b,omitempty"`
}

func main() {
    var foo Foo
    err := yaml.Unmarshal([]byte("{a: bar, b: foo}"), &foo)
    if err != nil {
        panic(err)
    }
    fmt.Println(foo.Bar)
    fmt.Println(foo.Foo)
}
```

**Comment by niedbalski** [comment]
Ooops, sorry, my fault, I just noticed that one of the structs i was missing the  yaml: prefix, and just tagging the members with `omitempty`

Thanks for your time.

Closing this bug.
