### ISSUE TITLE
Format with curly braces not supported

### ISSUE THREAD

**Issue by cscetbon** [go-yaml/yaml#270]
The following formats are not supported :
```
-
  domain: d1
  is_weekly: 0
-
  domain: d2
  is_weekly: 0
```

```
- {domain: d1,
   is_weekly: 0}
- {domain: d2,
   is_weekly: 0}
```

g-yaml returns 
```
null: null
null: null
```

**Comment by rogpeppe** [comment]
It seems to work fine to me.
This code prints the values I'd expect:

	package main
	
	import (
		"fmt"
		"log"
	
		"gopkg.in/yaml.v2"
	)
	
	var y = `
	- {domain: d1,
	   is_weekly: 0}
	- {domain: d2,
	   is_weekly: 0}
	`
	
	func main() {
		var x interface{}
		err := yaml.Unmarshal([]byte(y), &x)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%#v\n", x)
	}
