### ISSUE TITLE
bug: incorrect anchor/alias handling 

### ISSUE THREAD

**Issue by prateek** [go-yaml/yaml#275]
`go-yaml` handles Alias Nodes incorrectly. The [YAML spec section 7.1](http://yaml.org/spec/1.2/spec.html#id2786196), states anchor nodes must be defined prior to use in an alias node:

> An alias node is denoted by the “*” indicator. The alias refers to the most recent preceding node having the same anchor. **It is an error for an alias node to use an anchor that does not previously occur in the document**. It is not an error to specify an anchor that is not used by any alias node.

`go-yaml` does not enforce this, for example: the second iteration below should fail, but it passes –

```
package main

import (
	"fmt"
	"log"

	"gopkg.in/yaml.v2"
)

var validAliasedData = `
x: &earlier_anchor
  a: 1
  b: 2

b:
  <<: *earlier_anchor
  c: 2
  d: 3
`

var invalidAliasedData = `
b:
  <<: *later_anchor
  c: 2
  d: 3

x: &later_anchor
  a: 1
  b: 2
`

func main() {
	datas := [][]byte{
		[]byte(validAliasedData),
		[]byte(invalidAliasedData),
	}
	for _, data := range datas {
		m := make(map[interface{}]interface{})
		err := yaml.Unmarshal(data, &m)
		if err != nil {
			log.Fatalf("error: %v", err)
		}
		fmt.Printf("--- m:\n%v\n\n", m)
	}
}
```

**Comment by prateek** [comment]
Just a heads up, I'm sure many people have application code which relies on this behaviour. I certainly do. Changing this is going to cause issues for some end-users.

**Comment by prateek** [comment]
Happy to post a patch if you're good with changing the behaviour.

**Comment by niemeyer** [comment]
This is a divergence that doesn't sound worth fixing to be honest. People can break their documents by simply copy & pasting a section of a document which is a map of unordered fields. So this behavior breaks the idea of the lack of order there, and creates more problems than it solves.

We also never produce such documents by marshaling from the package, which means the broken document was produced some other way, most likely by hand.

It sounds fine to introduce a more strict checker, though, when one wants to make sure that documents comply to that rule. But again I'd prefer and recommend not failing to parse these documents.

**Comment by prateek** [comment]
@niemeyer I understand where you're coming from. Breaking documents that already parse is probably not acceptable, so the strict mode seems like a good path forward. 

A `yaml` file is **not** a map of unordered fields, it has to follow the rules dictated by spec. The rule I mentioned is important as the spec allows for multiple nodes to be aliased with the same identifier. The ordering constraint is required to be deterministic about which anchor node is referenced by an aliased node. For e.g. both the PyYAML (Python's YAML library) and Psych (Ruby's YAML library) both fail at parsing the example I posted for this reason.

**Comment by niemeyer** [comment]
@prateek From the [spec](http://www.yaml.org/spec/1.2/spec.html#id2765608):

> 3.2.2.1. Keys Order
>
> In the representation model, mapping keys do not have an order. To serialize a mapping, it is necessary to impose an ordering on its keys. This order is a serialization detail and should not be used when composing the representation graph (and hence for the preservation of application data). In every case where node order is significant, a sequence must be used. For example, (...)

The vast majority of YAML documents have such a mapping at the top level, so it's very reasonable that people think about it as something that lacks ordering. The fact you can dig further data to prove that this is in fact ordered in certain cases is beyond the point here.

**Comment by prateek** [comment]
@niemeyer The spec details three distinct models: `representation`, `serialisation`, and `presentation`. The bits you quoted are talking about a `representation` model.  A file on disk must be treated as `presentation` model at the start of parsing, again, explicitly pointed out in the [spec](http://www.yaml.org/spec/1.2/spec.html#id2762107). 

We do not need to discuss whether the current `go-yaml` behaviour is non-conformant. As the original post points out, it is called out in the spec as non-conformant. 

The point of a spec is portability. It doesn't matter whether the file was created by hand, the same library or another library. The spec dictates conforming behaviour. [Section 3.2](http://www.yaml.org/spec/1.2/spec.html#id2763452) makes this point clearly. 
> This section specifies the formal details of the results of the above processes. To maximise data portability between programming languages and implementations, users of YAML should be mindful of the distinction between serialization or presentation properties and those which are part of the YAML representation. Thus, while imposing a order on mapping keys is necessary for flattening YAML representations to a sequential access medium, this serialization detail must not be used to convey application level information. In a similar manner, while indentation technique and a choice of a node style are needed for the human readability, these presentation details are neither part of the YAML serialization nor the YAML representation. By carefully separating properties needed for serialization and presentation, YAML representations of application information will be consistent and portable between various programming environments.

**Comment by niemeyer** [comment]
> The fact you can dig further data to prove that this is in fact ordered in certain cases is beyond the point here.

**Comment by eine** [comment]
Related to #297 and #300.
