### ISSUE TITLE
releases +/ tags

### ISSUE THREAD

**Issue by doertedev** [go-yaml/yaml#277]
Hey there.

Is it possible to do releases or tags here? There are (also somewhat religious +/- political) issues with gopkg.in as the only approach.

Thanks in advance.

**Comment by niemeyer** [comment]
We have branches for the time being. Once vgo kicks in, we may do release tags.

**Comment by niemeyer** [comment]
I take that back. We already have tags in this repository. So I just tagged v2.2.0 for the latest changes.
