### ISSUE TITLE
Difference between v1 and master branch?

### ISSUE THREAD

**Issue by mattes** [go-yaml/yaml#28]
It seems as if people are working with branch v1 when forking. Maybe we should bring master branch in sync with v1 again and then add some comment in the README so master will become the active dev branch.

**Comment by mattes** [comment]
Default branch should be set to master, too?

**Comment by mattes** [comment]
Ah, just read: https://github.com/go-yaml/yaml/blob/master/error.go
Hmm. this is confusing.

**Comment by niemeyer** [comment]
The default development branch is v1, which reflects the current version of the API. We also prevent people incorrectly importing the package from github.com/go-yaml/yaml by having a clear error message via the error.go file.
