### ISSUE TITLE
Type of nested map during .Unmarshal

### ISSUE THREAD

**Issue by buddhike** [go-yaml/yaml#286]
When calling `.Unmarshal` with a `map[string]interface{}`, nested structures are unmarshalled into a `map[interface{}]interface{}`. Shouldn't it be using `map[string]interface{}` like `json` package does?

Here's an example to illustrate the situation.

```go
package main

import (
	"encoding/json"
	"reflect"

	yaml "gopkg.in/yaml.v2"
)

func main() {
	data := `a: a
b:
  c: d`

	m := make(map[string]interface{})
	yaml.Unmarshal([]byte(data), &m)

	jsonData := `{
  "a": "a",
  "b": {
    "c": "d"
  }
 }`

	jm := make(map[string]interface{})
	json.Unmarshal([]byte(jsonData), &jm)
	
	println(reflect.TypeOf(m["b"]).String())
	println(reflect.TypeOf(jm["b"]).String())
}
```

**Comment by lox** [comment]
YAML supports non-string keys for maps, where as JSON doesn't.

**Comment by buddhike** [comment]
OK, that makes sense then. Thanks for clarifying.

**Comment by chrisjohnson** [comment]
*EDIT* Updating yaml package to v3 solves this issue. I'll submit a patch to helm

-----

> YAML supports non-string keys for maps, where as JSON doesn't.

@lox is there a way to specify the format to `Unmarshall` recursively when unmarshalling? From Helm's source: https://github.com/helm/helm/blob/4ee8db2208923ea1ca1e4cc3792b2a3e088b6e0d/pkg/engine/funcs.go#L91-L98

I'm using fromYaml and getting `map[interface{}]interface{}` which I can't later merge with `map[string]interface{}`. The function even seems to specify the target format but I'm wondering if it's just not recursive? You can see the results here: https://play.golang.org/p/88eq1jFbA9d
