### ISSUE TITLE
boolean type field is not rendered if it is of false value and  declared as "omitempty"

### ISSUE THREAD

**Issue by zionwu** [go-yaml/yaml#291]
```go
func main() {
	a := Config{Global: false}
	b, err := yaml.Marshal(a)
	if err != nil {
		fmt.Printf("<error creating config string: %s>", err)
	}
	fmt.Print(string(b))

}

type Config struct {
	Global bool `yaml:"global,omitempty"`
}
```

Expected Result:
The above code should output `global: false`

Actually Result:
In the above example,  the Global field is of boolean type, and the result is `{}`. If `omitempty` is removed, then the result is `global: false`.

**Comment by rogpeppe** [comment]
The documentation for "omitempty" the qualifier says:

    Only include the field if it's not set to the zero value for the type 

False is the zero of the boolean type. Why is this not expected behaviour?
