### ISSUE TITLE
the function of isBase60Float in enecode.go have a problem

### ISSUE THREAD

**Issue by shiyanlin** [go-yaml/yaml#293]
isBase60Float("16:00") return true,it is wrong

**Comment by rogpeppe** [comment]
I'm inclined to go with the comment from the code:

    // From http://yaml.org/type/float.html, except the regular expression there
    // is bogus. In practice parsers do not enforce the "\.[0-9_]*" suffix.
    var base60float = regexp.MustCompile(`^[-+]?[0-9][0-9_]*(?::[0-5]?[0-9])+(?:\.[0-9_]*)?$`)

By that pattern, 16:00 is a base 60 float AFAICS.

Any further thoughts before I close the issue?

**Comment by niemeyer** [comment]
It doesn't matter much. We do not decode or encode those values, yaml 1.2 dropped them, and nobody sane should be trusting them to exist anyway because it's a very special case that doesn't deserve special syntax for it.
