### ISSUE TITLE
YAML with capital letters will make value incorrect.

### ISSUE THREAD

**Issue by qin-nz** [go-yaml/yaml#296]
```go
package main

import (
	"fmt"
	"log"

	"gopkg.in/yaml.v2"
)

var data = `
eatapple: true
eat_banana: true
EatFood: true
`

type T struct {
	EatApple  bool
	EatBanana bool
	EatFood   bool
}


func main() {
	t := T{}

	err := yaml.Unmarshal([]byte(data), &t)
	if err != nil {
		log.Fatalf("error: %v", err)
	}
	fmt.Printf("--- t:\n%v\n\n", t)

	d, err := yaml.Marshal(&t)
	if err != nil {
		log.Fatalf("error: %v", err)
	}
	fmt.Printf("--- t dump:\n%s\n\n", string(d))

	m := make(map[interface{}]interface{})

	err = yaml.Unmarshal([]byte(data), &m)
	if err != nil {
		log.Fatalf("error: %v", err)
	}
	fmt.Printf("--- m:\n%v\n\n", m)

	d, err = yaml.Marshal(&m)
	if err != nil {
		log.Fatalf("error: %v", err)
	}
	fmt.Printf("--- m dump:\n%s\n\n", string(d))
}

```

Output:

```
--- t:
{true false false}

--- t dump:
eatapple: true
eatbanana: false
eatfood: false


--- m:
map[eatapple:true eat_banana:true EatFood:true]

--- m dump:
EatFood: true
eat_banana: true
eatapple: true
```

`eatfood: false`  Is it a feature or bug?
If it was by design, I think it should be described.

**Comment by qin-nz** [comment]
yaml:
```yaml
eatapple: true
eat_banana: true
EatFood: true
```

struct:
```go
type T struct {
	EatApple  bool
	EatBanana bool
	EatFood   bool
}
```

result:
```
eatapple: true
eatbanana: false
eatfood: false
```

  
In the yaml file, `EatFood` is true, but when I use `t.EatFood` in golang, I got false.

**Comment by rogpeppe** [comment]
Thanks for the report. This is arguably unfortunate (it's different from the behaviour of other encoding packages such as encoding/json), but the behaviour by design and is documented as such. From the Unmarshal documentation:

> Struct fields are only unmarshalled if they are exported (have an upper case first letter), and are unmarshalled using the field name lowercased as the default key. Custom keys may be defined via the "yaml" name in the field tag: the content preceding the first comma is used as the key.

**Comment by yesennes** [comment]
By design? Is there a reason not to accept closer matches to key names? I don't think yaml has any set conventions for case.
