### ISSUE TITLE
Cannot decode !!float when it resolves to !!int 

### ISSUE THREAD

**Issue by rogpeppe** [go-yaml/yaml#312]
Decoding the following YAML fails, even though 0 is a valid float (and this example
is in example 10.7 of the YAML 1.2 specification):

    !!float 0

The error is:

    yaml: cannot decode !!int `0` as a !!float

**Comment by niemeyer** [comment]
Making this specific to !!int and !!float.

For the record, the problem is not type conversion, but that YAML is ambiguous. Values such as "0" are specified for both !!int and !!float.

Sorted that case out.
