### ISSUE TITLE
Vendoring advice?

### ISSUE THREAD

**Issue by jsha** [go-yaml/yaml#318]
In #307, @rogpeppe said:
> My plan was to merge devel into v2 soon, although I had a few more changes planned first. If you're using a dependency manager such as dep, you can always use the devel branch anyway (locking dependencies is always a good idea :-]).

We use `godep` to vendor our dependencies, but we vendor the `gopkg.in/yaml.v2` URL. Would you recommend vendoring the `github.com/go-yaml/yaml` URL instead? The latter does seem to be the direction the Go ecosystem is moving. If that's the direction the yaml project wants to take, it would be convenient to start tagging releases with semver.

Thanks for your work on this project!

**Comment by jsha** [comment]
Also, FYI, the `devel` branch tests currently don't pass because `encode_test.go` and `decode_test.go` import `gopkg.in/yaml.v2` instead of `github.com/go-yaml/yaml`, and the package API has evidently changed between `v2` and the current devel head. See https://github.com/letsencrypt/boulder/pull/3386.

I think it probably makes sense to change these imports to reference `github.com/go-yaml/yaml` instead, so they will always import whatever branch the user is currently working on.

**Comment by rogpeppe** [comment]
It should always be imported as gopkg.in/yaml.v2. To use the devel branch, you can check out that branch in the gopkg.in/yaml.v2 directory. You should not expect it to work when imported as github.com/go-yaml/yaml. In fact, I should probably put an import path restriction in the source for that.
