### ISSUE TITLE
invalid utf-8 can cause panic

### ISSUE THREAD

**Issue by rogpeppe** [go-yaml/yaml#32]
The is_break function (and probably others) can cause
a panic when marshalling strings containing invalid utf-8
(specifically a truncated line-break sequence in this case).

For example:

```
yaml.Marshal([]string{"hello\nfoo\xe2"})
```

panics.

**Comment by niemeyer** [comment]
This has to be marshalled as binary data, which I'm working on right now.

**Comment by rogpeppe** [comment]
I'd be OK if this drew an error actually. If I expect to be marshalling into a bson string type, I'm not sure that a behind-the-scenes change to binary data is great. I'm sure there are arguments the other way too though.

**Comment by niemeyer** [comment]
It's not a "behind-the-scenes change".. it's simply marshalling exactly the data provided into standard YAML form.
