### ISSUE TITLE
Struct tags are required in order to parse simple YAML

### ISSUE THREAD

**Issue by ecnepsnai** [go-yaml/yaml#320]
I ran into a problem where even with exported struct files, a simple two-property struct would not be populated from a valid YAML file.

Struct:
```go
type Config struct {
    BindAddr string
    Verbose  bool
}
```

YAML:
```yaml
BindAddr: "127.0.0.1:8080"
Verbose: true
```

Code:
```go
raw, err := ioutil.ReadFile(Directories.ConfigDir + "/config.yaml")
if err != nil {
	fmt.Println("Unable to locate configuration file.")
	os.Exit(1)
}

config := Config{}
err = yaml.Unmarshal(raw, &config)
if err != nil {
	fmt.Printf("Unable to parse configuration file: %s\n", err.Error())
	os.Exit(1)
}

fmt.Printf("Config: %v\n", config)
```

Without struct tags, the result is: `Config: { false}`

But if I change the struct to:
```go
type Config struct {
	BindAddr string `yaml:"BindAddr"`
	Verbose  bool   `yaml:"Verbose"`
}
```

It works.

Your example on the readme doesn't use struct tags (for the "A" property), and this works if I use JSON so I believe this is a bug.

**Comment by rogpeppe** [comment]
This is as documented:

> Struct fields are only unmarshalled if they are exported (have an upper case first letter), and are unmarshalled using the field name lowercased as the default key.

I think this is because most people use lower case field names; I'm sorry for the discrepancy with other encoding packages such as encoding/json, but this is just working as intended.

Note that the example in the readme doesn't use struct tags, but the names in the YAML are all lower case.

**Comment by ecnepsnai** [comment]
Okay, that makes sense. Thanks for clarifying!
