### ISSUE TITLE
Getting at the concrete syntax tree

### ISSUE THREAD

**Issue by aanand** [go-yaml/yaml#321]
Hi all. This isn't necessarily a feature request so much as a feeling-out of technical complexity.

I'm wondering how much work it would be to enable the reading of the _concrete_ syntax tree of a parsed YAML file. That is, all whitespace and comments are somehow accessible, as well as every key and value's exact textual representation.

The context is, of course, round-trip parsing - specifically, I want to write a YAML linter, and given how huge the YAML spec is, I _really_ don't want to write my own lexer/parser. I would much rather reuse a stable and battle-tested one.

Like I say, I'm not asking that this functionality be added to go-yaml - I'm happy to fork it and hack around - but first, I'd like to get a sense of how amenable the codebase is, in its current state, to that manner of hacking.

Thanks!

**Comment by rogpeppe** [comment]
I suspect it wouldn't be too hard to adapt the current code to do something like that (although I'm not sure about white space). What probably *is* going to be hard is to parse it, make meaningful changes, then produce output that works while preserving original comments, white space etc. If all you want to do is lint, it might not be too hard. But the YAML spec is insane. You are warned.

**Comment by niemeyer** [comment]
We won't offer access into the syntax tree itself, but v3 will offer something closer to it.

**Comment by niemeyer** [comment]
Sorry, clicked the button by mistake. Also meant to say that I'm currently working on v3, so we'll have something that might solve your problem in a short while.
