### ISSUE TITLE
Error not raised when wrong type found

### ISSUE THREAD

**Issue by riton** [go-yaml/yaml#322]
Hi, I'm using _YAML_ as a user configuration file format.

In my software, I need to somehow _validate_ that the user configuration matches my expectations.

My configuration file is using a `bool` type such as

```yaml
boolean_option: true
```

The problem occurs if the user (that may not know YAML format) writes something like

```yaml
boolean_option: "true"
```

and uses a `string` instead of a `boolean`.

This can be simulated and reproduced with the following code:

```go
package main

import (
	"fmt"

	yaml "gopkg.in/yaml.v2"
)

const toValidate = `
boolean_option: "true"
`

func main() {
	simple := struct {
		BooleanOption bool `yaml:"boolean_option"`
	}{}

	yaml.UnmarshalStrict([]byte(toValidate), &simple)
	fmt.Printf("%+v\n", simple)
}
```

which gives the following output

```
$ go run main.go
{BooleanOption:false}
```

If I understand well, we're getting here the _default_ `boolean` value `false` because the parser can't find a match with the struct it expects.

My question is now: how would you handle such validation and throw an error if the document provided does not _strictly_ match the `struct` types.

Thanks is advance

**Comment by rogpeppe** [comment]
Try checking the error returned from UnmarshalStrict.

**Comment by riton** [comment]
OMG ! I feel so stupid. 
You're absolutely right, my code is just lacking error handling... and the error is exactly what I was expecting `yaml: unmarshal errors: line 2: cannot unmarshal !!str `true` into bool`

Sorry for the noise and thanks for your answer.
