### ISSUE TITLE
go yaml parser for kubernetes yaml file

### ISSUE THREAD

**Issue by vaibhavjain1305** [go-yaml/yaml#327]
Is there a go yaml parser for kubernetes yaml file?

**I am not able to parse following line using "gopkg.in/yaml.v2":
image: {{ .Values.image.imageName }}**

It gives the error as:
_Unmarshal: yaml: unmarshal errors:
line 5: cannot unmarshal !!map into string
exit status 1_

To work fine, it needs to be enclosed with single/double quote. (like this: image: '{{ .Values.image.imageName }}' )

I have tried following declaration in struct:
- Image map[map[string]string]string `yaml:"image`
- Image[] map[string]interface{} `yaml:"image"`
- []map[string]map[string]string
- Kind string `yaml:"kind"`

But it gives almost same error all the time: _cannot unmarshal !!map into string_

Please suggest a way to parse the kubernetes yaml file in golang.

Thanks.

![image](https://user-images.githubusercontent.com/36156288/35802015-782affd4-0a94-11e8-9bb2-0dca2e197bab.png)

![image](https://user-images.githubusercontent.com/36156288/35845493-b3657418-0b38-11e8-9b53-cb723bd4b84b.png)

**Comment by rogpeppe** [comment]
I suspect that's not actually intended to be YAML input as is. It looks like something that needs to be run through the text/template package before parsing, and it's not valid YAML as is, I'm pretty sure.

Do you know where this configuration file format is documented?

**Comment by vaibhavjain1305** [comment]
It's a part of kubernetes helm chart file. I actually need to parse following set of YAML fields:

 volumes: /dockerdata-nfs/{{ .Values.nsPrefix }}/component/bin/installFeatures.sh
 namespace: '{{ .Values.nsPrefix }}-component'
 image: {{ .Values.image.componentBackend }}

Here it's giving error for parsing "image". If you could suggest a data type to be used in struct for "image". I cannot use string as it's not enclosed in quotes. I think it takes curly brackets as map. and we have 2 curly brackets here, so a nested map.

I tried running it by removing 1 set of curly brackets ( { .Values.image.componentBackend } ) and it worked  **Image map[string]string `yaml:"image"`**

**Comment by rogpeppe** [comment]
Again, I don't believe that's a valid YAML file, but a file intended to run through text/template before parsing as YAML. For example: https://play.golang.org/p/DNT9iZSv1tt

> It's a part of kubernetes helm chart file.

I don't see any files like yours in https://github.com/kubernetes/helm/blob/master/docs/charts.md.

**Comment by lox** [comment]
Those are golang text templates inline in yaml @vaibhavjain1305. If you want it to be YAML then you need to string quote your fields and it should work. I'd suggest getting your example working in https://yaml-online-parser.appspot.com/ first.

**Comment by rogpeppe** [comment]
Closing as this doesn't appear to be a bug.
