### ISSUE TITLE
Unexpected nil value when Unmarshal() is given an empty data value

### ISSUE THREAD

**Issue by dwhittle-sfdc** [go-yaml/yaml#333]
Unlike `encoding/json` when `data` is empty `Unmarshal()` does not return an error. When this happens, however, the target variable is left uninitialized. The expected result would be that either an error is returned or that the target is a non-nil value even if it is empty.

Furthermore, in the event of unmarshaling an empty string to a struct that has the `UnmarshalYAML()` receiver, `UnmarshalYAML()` is never called. This circumvents the ability to set defaults or check for custom errors via `UnmarshalYAML()`. The expected result is that if `Unmarshal()` does not return an error then `UnmarshalYAML()` should have executed.

Example code:
```go
package main

import (
	"encoding/json"
	"fmt"

	yaml "gopkg.in/yaml.v2"
)

type foo struct {
	Foo string
	Bar string
}

func (f *foo) UnmarshalYAML(unmarshal func(interface{}) error) error {
	fmt.Println("in UnmarshalYAML()")

	var raw map[string]string
	if err := unmarshal(&raw); err != nil {
		return err
	}

	if val, ok := raw["Foo"]; ok {
		f.Foo = val
	}
	if val, ok := raw["Bar"]; ok {
		f.Bar = val
	}

	return nil
}

func main() {
	var f *foo
	data := []byte("Foo: bar")
	err := yaml.Unmarshal(data, &f)
	fmt.Println("with string (YAML):", f, err)

	f = nil
	data = []byte("")
	err = yaml.Unmarshal(data, &f)
	fmt.Println("empty string (YAML):", f, err)

	err = json.Unmarshal(data, &f)
	fmt.Println("empty string (JSON):", data, err)
}
```

Example output:
```
$ go run main.go 
in UnmarshalYAML()
with string (YAML): &{bar } <nil>
empty string (YAML): <nil> <nil>
empty string (JSON): [] unexpected end of JSON input
```

**Comment by dwhittle-sfdc** [comment]
Possibly related to #276

**Comment by niemeyer** [comment]
An empty definition [is one of the representations of yaml's null](http://www.yaml.org/type/null.html).

We don't call the marshaler because if that was a pointer it would be attempting to unmarshal into a nil value. This is indeed a special case, but intentionally, in the sense that nil is a special case.
