### ISSUE TITLE
Omit empty as a method parameter

### ISSUE THREAD

**Issue by challarao** [go-yaml/yaml#338]
Sometimes we may need to control how we write yaml file based on the use case. Sometimes we may need empty values sometimes not. So, it would be helpful to also include this as a method parameter for Marshal such that it can be controlled programmatically.

Let me know if I overlooked something and this option already exists.

Thank you

**Comment by niemeyer** [comment]
You can control exactly how your values are marshaled by using a custom marshaler. See the yaml.Marshaler interface.
