### ISSUE TITLE
Inconsistent default values handling

### ISSUE THREAD

**Issue by mmatczuk** [go-yaml/yaml#339]
The parser wipes a field if it encounters an empty definition. This is inconsistent with providing a partial definition because empty definition is a special case...

Moreover when empty definition is encountered UnmarshalYAML is not called.

The example below produces

```bash
{{default default}}

UnmarshalYAML
{{default default}}

UnmarshalYAML
{{v0 default}}

{{ }}
```

Note the `{{ }}`.

```go
package main

import (
	"testing"
	"fmt"

	"gopkg.in/yaml.v2"
)

type Top struct {
	Sub Sub `yaml:"sub"`
}

type Sub struct {
	V0 string `yaml:"v0"`
	V1 string `yaml:"v1"`
}

func (s *Sub) UnmarshalYAML(unmarshal func(interface{}) error) error {
	fmt.Println("UnmarshalYAML")
	type plain Sub
	return unmarshal((*plain)(s))
}

func defaultTop() Top {
	return Top{
		Sub: Sub{
			V0: "default",
			V1: "default",
		},
	}
}

func TestYaml(t *testing.T) {
	table := []string{
		"",
		"sub:\n  bla: bla",
		"sub:\n  v0: v0",
		"sub:\n",
	}

	for _, test := range table {
		v := defaultTop()
		if err := yaml.Unmarshal([]byte(test), &v); err != nil {
			t.Error(err)
		}
		fmt.Println(v)
		fmt.Println()
	}
}
```

**Comment by niemeyer** [comment]
An empty definition [is one of the representations of yaml's null](http://www.yaml.org/type/null.html).

We don't call the marshaler because if that was a pointer it would be attempting to unmarshal into a nil value. This is indeed a special case, but intentionally, in the sense that nil is a special case.
