### ISSUE TITLE
Base 60 floats marshalled incompatibly with YAML 1.1

### ISSUE THREAD

**Issue by natefinch** [go-yaml/yaml#34]
ingest this yaml: https://github.com/discourse/discourse_docker/blob/master/samples/standalone.yml  
marshal it into a simple map[interface{}]interface{} and then unmarshal it back into a string and it becomes something like this: http://pastebin.ubuntu.com/8329740/   (this example is slightly modified but the important part is under expose, which is "unmodified".

Note that the entries under expose: are unquoted strings ... somehow this confuses yaml parsers due to the colons and they blow up.  The use case was starting a docker container, but trying to ingest the output with a python yaml parser also fails.  I'll update this issue with more info once I get a smaller example written.

**Comment by natefinch** [comment]
The problem is definitely the 2222:22 value... I can reduce it to just this part of the yaml:

``` yaml
expose:
- 80:80
- 2222:22
```

yaml.v1 can loop this data through its parser no problem, as this program indicates:
http://pastebin.ubuntu.com/8357053/

However, it seems other parsers have more difficulty.  All the other parsers I could find convert it into this value:

``` yaml
expose: 
  - "80:80"
  - 133342
```

Here's a list of online validators that I tried:
http://yaml-online-parser.appspot.com/ 
http://YAMLlint.com
http://instantyaml.appspot.com/
http://nodeca.github.io/js-yaml/

Maybe they're all using the same flawed library, I don't know.  But it seems suspicious that these, and whatever discourse is using, and PyYaml all have problems.

**Comment by niemeyer** [comment]
They're not flawed, strictly speaking. They're just following version 1.1 of the specification, which amusingly [defines](http://yaml.org/type/float.html) _base 60 floats:_

> Using “:” allows expressing the integer part in base 60, which is convenient for time and angle values (the fractional part is always in base 10).

Very convenient. Of course everybody saying `1:1` want that decoded as `61.0`, right? Nuts, and that's what you get in those parsers you've been testing.

Thankfully, someone [got rid](http://yaml.org/spec/1.2/spec.html#id2804092) of them in 1.2:

> Either 0, .inf, -.inf, .nan, or scientific notation matching the regular expression `-? [1-9] ( \. [0-9]* [1-9] )? ( e [-+] [1-9] [0-9]* )?`.

and more [generally](http://yaml.org/spec/1.2/spec.html):

> Normally, YAML insists the “:” mapping value indicator be separated from the value by white space. A benefit of this restriction is that the “:” character can be used inside plain scalars, as long as it is not followed by white space. This allows for unquoted URLs and timestamps. It is also a potential source for confusion as “a:1” is a plain scalar and not a key: value pair.

**Comment by natefinch** [comment]
This still seems like a bug.  It means the output in this case is incorrect as far as other yaml 1.1 parsers are concerned.  While I don't think it's super important to support base 60 floats, it still seems important to make goyaml's output compatible with other parsers for something like a generic string that happens to look like a base 60 float.   Always quoting the string if it contains a colon would a trivial fix to ensure that the output is correctly interpreted by other parsers.

**Comment by niemeyer** [comment]
Sounds fair.

**Comment by natefinch** [comment]
Awesome, thanks!
