### ISSUE TITLE
Anchors are broken for MapSlice

### ISSUE THREAD

**Issue by sam701** [go-yaml/yaml#344]
Unmarshal produces wrong output for `yaml.MapSlice`. Here is the code:

```
package main

import (
	"log"

	"gopkg.in/yaml.v2"
)

var content = `
a1:
  f1: value1
  <<: &anchor
    f2: value2
  
a2:
  f3: value3
  <<: *anchor
`

func main() {
	var result map[interface{}]interface{}
	yaml.Unmarshal([]byte(content), &result)
	log.Println(result)

	var result2 yaml.MapSlice
	yaml.Unmarshal([]byte(content), &result2)
	log.Println(result2)
}
```

**Output**:
```
2018/03/19 10:37:04 map[a1:map[f1:value1 f2:value2] a2:map[f3:value3 f2:value2]]
2018/03/19 10:37:04 [{a1 [{f1 value1}]} {a2 [{f3 value3}]}]
```
`f2` is missing for `yaml.MapSlice`.

**Comment by niemeyer** [comment]
That's #184.

**Comment by cup** [comment]
https://github.com/drone/drone/issues/2323
https://github.com/drone/drone-cli/pull/103
https://github.com/go-swagger/go-swagger/issues/1193
https://github.com/go-yaml/yaml/issues/184

https://github.com/go-yaml/yaml/issues/344
https://github.com/go-yaml/yaml/issues/91
https://github.com/mikefarah/yq/issues/178
https://github.com/mikefarah/yq/issues/206
