### ISSUE TITLE
Underscore in attribute name does not work

### ISSUE THREAD

**Issue by swapx** [go-yaml/yaml#346]
The application/x-yaml is used in conjunction with a go-swagger REST API application. The github.com/go-yaml/yaml is used. for this purpose. When using underscore "_" in attribute name, function Unmarshal(buf, v) in go-yaml/yaml doesn't properly work. 

Only when underscore "_" is removed from attribute names then it's properly working.

**Comment by niemeyer** [comment]
We have plenty of code and tests using those. If you have an example, please provide and we'll have a look.

**Comment by chenyu1990** [comment]
I have this problem too
![git](https://user-images.githubusercontent.com/15179320/81006760-97174a00-8e82-11ea-996e-bd501b21b408.png)

**Comment by shyandsy** [comment]
looks like the unmarshal doesnt take look for the key with underscore and uppercase letter like camel case

test case
```
package main

import (
	"fmt"
	"gopkg.in/yaml.v3"
)

type Database struct {
	Max	                int		    `yaml: "max"`
	WhoAmI	            string		`yaml: "whoami"`
	WhoAreU	            string		`yaml: "WhoAreU"`
	MaxIdleConnections	int         `yaml: "maxIdleConnections"`
	MaxOpenConnections	int64       `yaml: "max_Open_connections,omitempty"`
}

func main() {
	var yamlText = `
max: 1
whoami: someone
WhoAreU: nobody
maxIdleConnections: 12
max_Open_connections: 10
`
	// 加载配置
	var d Database
	err := yaml.Unmarshal([]byte(yamlText), &d)
	if err != nil {
		fmt.Println(err.Error())
	}
	
	fmt.Println(d.Max)
	fmt.Println(d.WhoAmI)
	fmt.Println(d.WhoAreU)              // theres no value for WhoAreU
	fmt.Println(d.MaxOpenConnections)   // theres no value for MaxOpenConnections
	fmt.Println(d.MaxOpenConnections)   // theres no value for MaxOpenConnections
}
```

output
```
1
someone

0
0
```

**Comment by tglanz** [comment]
@shyandsy if still relevant, what i noticed is that the marshaling is sensitive to whitespace. e.g, 

    `yaml: "maxIdleConnections"`

is ignored but

    `yaml:"maxIdleConnections"`

is fine
