### ISSUE TITLE
Unmarshaling empty YAML header into map yields nil instead of empty map

### ISSUE THREAD

**Issue by XenoPhex** [go-yaml/yaml#347]
**What happened:** `input` became `nil` after calling unmarshal and attempting to assign caused runtime error `panic: assignment to entry in nil map`.
**Expected:** `input` to remain an empty unpopulated map.

```go
package main

import (
	"gopkg.in/yaml.v2"
)

func main() {
	input := map[string]string{}
	data := []byte("---")

	err := yaml.Unmarshal(data, &input)
	if err != nil {
		panic(err)
	}

	input["foo"] = "bar"
}
```

**Comment by niemeyer** [comment]
An empty value in yaml is considered null.

From [the specification](http://www.yaml.org/type/null.html):
```
 ~ # (canonical)
|null|Null|NULL # (English)
| # (Empty)
```
Unmarshaling null into a map sets the map to null.

**Comment by niemeyer** [comment]
As a side note, there's no reason to initialize the map in this case. This works fine:
```
var input map[string]string
err := yaml.Unmarshal(data, &input)
```
The map is created as necessary.
