### ISSUE TITLE
Official project import path

### ISSUE THREAD

**Issue by galdor** [go-yaml/yaml#349]
After updating to master, compilation fails:

```
vendor/github.com/go-yaml/yaml/error.go:4:2: "ERROR: the correct import path is gopkg.in/yaml.v2 ... " evaluated but not used
```

Is there a reason for this kind of restriction ? I don't see anything wrong with using the official repository directly.

**Comment by niemeyer** [comment]
The official import of this project is gopkg.in/yaml.v2, with a version number, and it's a real problem to import projects from alternative URLs which are not the official ones. If we add an internal import (subpackage), we will reference the official location, and you will be importing two different packages most likely updated at different points in time.

So yes, there's a reason, and it's important if you don't want to end up with software broken in surprising ways.

**Comment by niemeyer** [comment]
As a side note, the original title of this issue said "master does not compile anymore", which is curious. We haven't touched the logic described here for years.

**Comment by galdor** [comment]
Well the message was created in 215c37dc98af42995b8f7e1f0f076e023e97c994. It's a pity to force users to go through gopkg.in even though the project repository is github.com/go-yaml/yaml. I guess I will end up forking the repository and patching all import paths.

**Comment by niemeyer** [comment]
Well that message is from **2014!**

I'm not forcing you to anything. I wrote that piece of code, four years ago, and I thought you'd be pretty glad that I made it available to you at a liberal license. But by all means, dear typically unfriendly open source developer, fork it and go solve your problems with the world elsewhere.

**Comment by galdor** [comment]
I'm sorry if I seemed critical, that was not my intention. I'm glad you made go-yaml available.

I am just not a fan of having to use gopkg.in when there is a perfectly usable repository, especially since you create tagged release to track stable versions.

Your project, your call anyway :)

**Comment by niemeyer** [comment]
That call was made back in 2014 and it was the right call.

Have a look at https://blog.golang.org/versioning-proposal if you don't understand the problem.
