### ISSUE TITLE
unmarshal of null produces error

### ISSUE THREAD

**Issue by rogpeppe** [go-yaml/yaml#35]
```
var x interface{}
err := yaml.Unmarshal([]byte("null"), &x)
```

This fails with the error "YAML error: reflect: reflect.Value.Set using unaddressable value".

I believe it should work. The heart of the problem is in the
implementation of the decoder.setter method, which does
not dereference the out pointer if the tag is !!null (as it is
in this case).

The actual error occurs in the decoder.scalar method, inside the
reflect.Ptr arm of the type switch. out.Set(reflect.Zero(out.Type())
fails because out is not settable, because it has not
been dereferenced.

I've tried a few possible fixes, but haven't got there yet - decoder.setter
is sensitive code! Filing this bug as a place holder.

**Comment by niemeyer** [comment]
The logic in decoder.setter is tricky indeed, but in this case you've probably struggled more because the issue isn't actually there.

Thanks for filing the bug.
