### ISSUE TITLE
Test broken because it expects error on wrong line

### ISSUE THREAD

**Issue by nim-nim** [go-yaml/yaml#351]
With 2.2.0, kubernetes 1.7.15 apimachinery unit tests fail with
```
+ GOPATH=/builddir/build/BUILD/apimachinery-kubernetes-1.7.15/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
err: error converting YAML to JSON: yaml: line 3: found a tab character that violate indentation
--- FAIL: TestDecodeBrokenYAML (0.00s)
	decoder_test.go:145: expected "error converting YAML to JSON: yaml: line 3: found a tab character that violate indentation" to have 'yaml: line 2:' found a tab character
FAIL
exit status 1
FAIL    k8s.io/apimachinery/pkg/util/yaml       0.703s
```
They pass fine with 2.1.1

**Comment by niemeyer** [comment]
That's testing a broken yaml document, which is still breaking, apparently at a different line. What's the test, what's the real broken line? Which version is correct?

**Comment by niemeyer** [comment]
Found it: https://github.com/kubernetes/apimachinery/blob/210bcde8e5a7715fe776460ca1df1a3f2738725e/pkg/util/yaml/decoder_test.go#L187

That test is breaking because it is expecting a bug. The line that is wrong is 3, not 2. The latest changed fixed that.

**Comment by nim-nim** [comment]
Sorry, I should have included the next line (fixed)

The test is there:
https://github.com/kubernetes/apimachinery/blob/c44b40f648ea8310317b60c4805f212a5d707a9b/pkg/util/yaml/decoder_test.go#L105
