### ISSUE TITLE
yaml.Marshal(...): adds an (for me) unwanted \n

### ISSUE THREAD

**Issue by consideRatio** [go-yaml/yaml#355]
For me, it is an unwanted behavior that a new line is popping up in the string after using the `yaml.Marshal(...)` function. Does it make sense to fix this? I arrive here through [Helm issue #3470](https://github.com/kubernetes/helm/issues/3470) and have traced the origin of that issue to this behavior of the `yaml.Marshal` function. The Helm repo could circumvent it by trimming the new line as well.

### Reproduction

```go
package main

import (
	"fmt"

	"gopkg.in/yaml.v2"
)

type Person struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

func main() {
	p := Person{"Erik", 31}
	y, _ := yaml.Marshal(p)
	fmt.Println(string(y))
	fmt.Println(string(y))
	/* Output:
	age: 31
	name: Erik

	age: 31
	name: Erik

	*/
}
```

**Comment by rogpeppe** [comment]
Thanks for the report, but AFAICS the extra newline is being printed because you're using fmt.Println not fmt.Print. If you use fmt.Print, there is no extra newline printed. Therefore I'm going to close this issue as invalid.

**Comment by consideRatio** [comment]
@rogpeppe thank you for the reply!

There is a new line added in the end of the string by the `yaml.Marshal` function, and an extra one by the `println`. Those two together produce the output of a fully blank line. So one too much I'd say.

If this is wanted or unwanted behavior can boil down to the question if it `yaml.Marshal` should output a string like A or B.

```
# output string A (current behavior)
"age: 31\nname: Erik\n"

# output string B (expected behavior)
"age: 31\nname: Erik"
```

**Comment by rogpeppe** [comment]
Newlines are a significant part of the YAML format. Why do you think it's a good idea that a formatted YAML file should not contain a final newline?

**Comment by consideRatio** [comment]
I'm not confident that it would make sense for this repo to add a new line. I'm thinking that the benefit of not including it would allow a user to choose to end with a new line or not by the usage of "println" / "print" or similar function. No matter if that would make sense, it might become an issue switching to not include a \n now for current users being accustomed to it.

The yaml.Marshal function is in my case not used to write a full YAML file, but a part of it. I'm using [Kubernetes/Helm](https://github.com/kubernetes/helm) that has declared a toYaml function that outputs yaml snippets based on [github.com/ghodss/yaml](https://github.com/ghodss/yaml) which is wrapping for this repo.

I'll close this as it seems like the current behavior is the generally expected behavior.

**Comment by niemeyer** [comment]
The yaml format is inherently multi-line, and indented, so having the new line there seems appropriate, and as you hint stripping it is trivial.

If someone is dealing with yaml snippets, they are already into byte-fiddling territory anyway because they will have to reindent the output to match the context.

**Comment by consideRatio** [comment]
@rogpeppe and @niemeyer thanks for taking the time to help me think this through!
