### ISSUE TITLE
Doesn't support camel-cased keys

### ISSUE THREAD

**Issue by rnix** [go-yaml/yaml#36]
e.g.

```

---
  basePath: "https://github.com"
```

That can not be unmarshaled into:

```
    type Data struct {
        BasePath    string
    }
```

But this can:

```

---
  basepath: "https://github.com"
```

This can be solved by support struct-tags in the same way json and XML un/marshaling works.

**Comment by niemeyer** [comment]
It supports struct tags, as per the documentation:

http://gopkg.in/yaml.v2#Marshal
