### ISSUE TITLE
NewDecoder export is missing despite being documented in the API

### ISSUE THREAD

**Issue by hookenz** [go-yaml/yaml#371]
This library doesn't implement what it documents.

Specifically the NewDecoder export which takes an io.Reader

**Comment by niemeyer** [comment]
The documentation is built from the code. If it's documented, the code exists.

You're most probably not looking at an up-to-date version of the gopkg.in/yaml.v2 Go package.

**Comment by hookenz** [comment]
Thanks,  it would seem then that when importing gopkg.in/yaml.v2 is out of date.  I used go get and grepped the sources and sure enough, NewDecoder is missing.  However, looking at the latest code on github and NewDecoder exists in yaml.go.
