### ISSUE TITLE
how to use  alias?

### ISSUE THREAD

**Issue by mikeweiwei** [go-yaml/yaml#374]
hi~
## for example：the yaml string to struct！
# the yaml string ：
name: alert-test
type: frequency
owner: gyw
description: "2018-06-06"
index: logstash-*
num_events: 1
timeframe:
  minutes: 30
filter:
- query:
    query_string:
      query: "kubernetes.labels.name: test"
- query:
    query_string:
      query: "kubernetes.namespace_name: admin"
- query:
    wildcard:
     log: &query1 '*Listening*'
query1: *query1
alert:
- "email"
smtp_host: smtp.exmail.qq.com
smtp_port: 465
smtp_ssl: true
from_addr: tester@tenxcloud.com
smtp_auth_file: /opt/config/email_config.yaml
email: 
- gaoyawei@tenxcloud.com
- jfeng.lv@tenxcloud.com

# the struct：
type Rule struct {
	Name           string
	Type           string
	Owner          string
	Description    string
	Index          string
	NumEvents      int `yaml:"num_events,flow"`
	Timeframe      struct{
						Minutes int `int:"minutes"`
  					}
	Filter         []Querys
	Query1         *Querys
	Alert          []string
	SmtpHost       string `yaml:"smtp_host"`
	SmtpPort       int    `yaml:"smtp_port"`
	SmtpSsl        bool   `yaml:"smtp_ssl"`
	FromAddr       string `yaml:"from_addr"`
	SmtpAuthFile   string `yaml:"smtp_auth_file"`
	Email          []string
}

type Querys struct  {
	Query Query
}

type Query struct{
	Wildcard Wildcard      `yaml:"wildcard,omitempty"`
	QueryString QueryString `yaml:"query_string,omitempty"`
}

type Wildcard struct{Log string}

type QueryString struct{Query string}

# question：
for this  yaml string
**- query:
    wildcard:
     log: &query1 '*Listening*'
query1: *query1**
### ## in the struct，how to write？

**Comment by niemeyer** [comment]
Hello,

This is a place to report issues with the yaml package. For general usage questions, I suggest getting in touch with a Go user group such as the golang-nuts mailing list.
