### ISSUE TITLE
yaml executable is not getting created when I install using "go get gopkg.in/yaml.v2"

### ISSUE THREAD

**Issue by chakravarthy392** [go-yaml/yaml#376]
After installing the package with `go get gopkg.in/yaml.v2` , source code is stored in `$GOPATH/src` and package is built and written to `$GOPATH/pkg/linux_amd64` but **no bin/yaml executable is created in `$GOPATH`.**

## Environment
ARCH=x86_64
go version=go1.10.1

## Expected Behavior
A bin folder should be created in `$GOPATH` and yaml exeutable file should be present in `$GOPATH/bin`

## Current Behavior
No bin/yaml executable is created in `$GOPATH`

## Steps to Reproduce 
1)Install go-1.10.1
2)export GOPATH
3)go get gopkg.in/yaml.v2

It became a blocker to build some other package, please let me know if there is any way to create the yaml executable file.

**Comment by triztian** [comment]
Hi Chakra Varthy!, 

Executables only get created (and installed under `$GOPATH/bin`) for packages that are  named`main`, the `go-yaml` package is a library package that is meant to be consumed by another (possibly yours) `main` package, like for example this one:

my_main.go:
```go
package main

import (
  "os"
  "log"
  "io/ioutil"

   "gopkg.in/yaml.v2"
)

func main() {
   f, err := os.Open(os.Arg[1])
   if err != nil {
      log.Fatal(err)
   }

   data, err := ioutil.ReadAll(f)
   if err != nil {
      log.Fatal(err)
   }
  
   m := map[interface{}]interface{}{}
   if err := yaml.Unmarshal(data, &m); err != nil {
      log.Fatal(err) 
  }

  log.Println(m)
}
```

**Comment by mcblair** [comment]
We use the go yaml executable via CLI in our build processes.

This breaks us.

Is there a recommended workaround?

**Comment by chakravarthy392** [comment]
Thanks for the reply @triztian, as you said some files are importing this `go-yaml` package.
But as I remember, the binary was getting created just by installing the package.
 I want to give some more details to check if others are also facing the same issue .

Earlier I have used `go get github.com/mikefarah/yaml` **[forked from golang]** to create the `yaml` binary which was being used for getting version tags from a `.yml` file while building a package.

But from 13th of this month neither `go get github.com/mikefarah/yaml` nor `go get gopkg.in/yaml.v2` creating the binary which leads to build failures as mentioned by @mcblair.

**Comment by mcblair** [comment]
I recommend you use this: https://github.com/mikefarah/yq

Syntax is identical, as I'm sure its using go yaml underneath.

**Comment by niemeyer** [comment]
The yaml package is just a library indeed. We don't expose any binaries by default.
