### ISSUE TITLE
Support encoding.TextMarshaler/Unmarshaler

### ISSUE THREAD

**Issue by niemeyer** [go-yaml/yaml#38]
Support the standard marshaling/unmarshaling interfaces from the `encoding` package:
- TextMarshaler
- TextUnmarshaler

**Comment by nictuku** [comment]
Nice. This would allow easy serialization of net.IP. Are you planning to add this to v1 also or only v2?

**Comment by nictuku** [comment]
If someone would contribute to this, would you take PRs for v1 or only v2?

**Comment by niemeyer** [comment]
Initial plan is to support v2 only.. there's really no big reason to stick on v1, so I'd rather give people more reasons to move on instead.

**Comment by niemeyer** [comment]
I've moved the implementation of the binary marshaling half onto issue #40.

**Comment by nictuku** [comment]
Thanks for doing it so quickly :).
