### ISSUE TITLE
Improve rendering of text with embedded newlines

### ISSUE THREAD

**Issue by akeemphilbert** [go-yaml/yaml#396]
Using `|` is supposed to allow for the input of multiline text which should maintain line breaks when parsed. This is not the case with the parser

e.g.
```
description: |
  Some long description
  That spans multiple lines
```

(This is similar to #70  but that was closed and not re-opened)

**Comment by niemeyer** [comment]
I don't understand the report. Can you provide an example of what you expected and what you are getting instead?

**Comment by akeemphilbert** [comment]
If in my yml I have:
```
description: |
  Some long description
  That spans multiple lines
```

When I parse it the value of description is output as:
```
Some long descriptionThat spans multiple lines
```
Note missing line breaks

**Comment by niemeyer** [comment]
That's a very common style and we use it all the time. Seems to work fine.

Can you provide a small self-contained reproducer?

**Comment by akeemphilbert** [comment]
The issue was not with the parser
