### ISSUE TITLE
Line folding ">" incorrectly chops off empty lines

### ISSUE THREAD

**Issue by tliron** [go-yaml/yaml#400]
With the following:
```
description: >
  This is a line.

  This is a second line after an empty line.
```
The parsed value is: `"This is a line.\nThis is a second line after an empty line."`. As you can see, the empty line in between has disappeared.

This is incorrect behavior according to the [spec](http://yaml.org/spec/1.2/spec.html#id2779048) and indeed works differently from other YAML parsers.

**Comment by niemeyer** [comment]
That's exactly the behavior the spec describes, and also the behavior you'll get from other parsers.

This is Python:
```
>>> yaml.load("""
... description: >
...   This is a line.
... 
...   This is a second line after an empty line.
... """)
{'description': 'This is a line.\nThis is a second line after an empty line.\n'}
```

This is the spec entry you referenced:

> Line folding allows long lines to be broken for readability, while retaining the semantics of the original long line. If a line break is followed by an empty line, it is trimmed; the first line break is discarded and the rest are retained as content.
