### ISSUE TITLE
Decode empty array to non-nil slice

### ISSUE THREAD

**Issue by chrneumann** [go-yaml/yaml#42]
Empty arrays (e.g. `foo: []`) are encoded to `nil`. That makes it hard do distinguish this case from `foo` being not present in the YAML or being `null`.

Any reasons not to change this (i.e. encoding it to an non-nil slice of zero length)?

**Comment by ghost** [comment]
I meet the situation , too.  So I am very confused...

```
test_ring_yaml = ` 
                datetime:   2015-01-01 13:00        # be precise to minute
                protocol_version:   1.0    
                owner:    zhaoxi
                alert_receivers:
                migration: 
                app_names:    
                    - CPC_Ad    
                    - Search-Ad
                shards:
                    - # one shard is one object 
                      master: 10.11.1.1:6379,1      # ip:port,weight
                      slaves:
                            - 10.11.2.1:6379,1
                            - 10.11.3.1:6379,1
                    -   
                      master: 10.11.1.2:6379,1      # ip:port,weight
                      slaves: []                    # empty content
                    -   
                      master: 10.11.1.3:6379,1
                    -   
                      master: 10.11.1.10:6379,2    
`

if actual.Shards[1].Slaves == nil {
    log.Println("Nil pointer")   
}
if !reflect.DeepEqual(actual, expectedRing) {
    t.Errorf("Not equal. Expected:%q, Actual:%q\n", expectedRing, actual)
}
```

---

my struct :

<pre>
// ------------------------------------------------------
// YAML -- Begin
type AppNames []string
type Migration struct {
} //TODO extension
type Shard struct {
    // IP:Port,Weight
    Master string   `yaml:"master"`
    Slaves []string `yaml:"slaves,omitempty"`
}
type RingYAML struct {
    Name            string     `yaml:"name"`
    Datetime        string     `yaml:"datetime"`
    ProtocolVersion string     `yaml:"protocol_version"`
    Owner           string     `yaml:"owner,omitempty"`
    AlertReceivers  []string   `yaml:"alert_receivers,omitempty"`
    Migration       *Migration `yaml:"migration"`
    AppNames        AppNames   `yaml:"app_names"` // simple ACL implementation
    Shards          []*Shard   `yaml:"shards"`
}
// YAML -- End
// ------------------------------------------------------
</pre>

== go test -v :
=== RUN TestDecodeRingYAML
2015/01/16 15:56:33 Nil pointer
--- PASS: TestDecodeRingYAML (0.00s)

**Comment by ghost** [comment]
yaml "gopkg.in/yaml.v2"

I am eagerly waiting for the bugfix.

**Comment by niemeyer** [comment]
I believe this behavior was already fixed as a side effect of  0885984. I've added a test to ensure this is the case in bef53ef. If you find the bug again with the current code, please let me know.

**Comment by ghost** [comment]
When do you put your fixed into gopkg.in/yaml.v2? 
Is it ready for Users.?

**Comment by niemeyer** [comment]
Yes, the commits referenced above are up right now.
