### ISSUE TITLE
Can't `go get`

### ISSUE THREAD

**Issue by dreampuf** [go-yaml/yaml#45]
```
$ go get gopkg.in/yaml.v1
# cd .; git clone https://gopkg.in/yaml.v1 /export/home/tomcat/.gvm/pkgsets/go1.2.2/global/src/gopkg.in/yaml.v1
Cloning into '/export/home/tomcat/.gvm/pkgsets/go1.2.2/global/src/gopkg.in/yaml.v1'...
error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version while accessing https://gopkg.in/yaml.v1/info/refs?service=git-upload-pack
fatal: HTTP request failed
package gopkg.in/yaml.v1: exit status 128
```

**Comment by niemeyer** [comment]
That error implies an SSL negotiation error with the website. You can try the git command by hand and debug it to see what is wrong. Ensure you're not behind a capturing proxy of some kind that is diverting the request to a different place.

You can also check that the website's certificate is alright by simply navigating to it with a browser.

Just tried it out, and it works fine:

```
$ GOPATH=$PWD/foo go get gopkg.in/yaml.v2
$
```

Please feel free to reopen if you get any evidence that this is a problem with the service.

**Comment by kagb** [comment]
I met this problem and solved it by this command:
`git config --global http.sslVerify true`

Open your git verfiy config for https
