### ISSUE TITLE
Node Encoder

### ISSUE THREAD

**Issue by mikefarah** [go-yaml/yaml#451]
The new v3 interface has the powerful Node struct, which includes comments and line numbers.

This has a Decode function but no Encode for outputting the result back out to yaml.

Context: I'm using this library in [yq](https://github.com/mikefarah/yq) to manipulate yaml files on the cli, so ideally I'd want to read the yaml into a Node struct, make some changes then output it again, preserving comments and the like.

Is there a plan to add an Encode function?

**Comment by mikefarah** [comment]
Done some more digging - basically I'm doing

```
import (
...
	yaml "gopkg.in/yaml.v3"
)
var dataBucket yaml.Node
....
var encoder = yaml.NewEncoder(cmd.OutOrStdout())
err := encoder.Encode(dataBucket)
if err != nil {
	return err
}
encoder.Close()
```

What this is doing however, is marshalling the Node as if it is a plain object:
```
kind: 1
style: 0
tag: ""
value: ""
anchor: ""
alias: null
content:
-   - become: true gather_facts: false # hi there
hosts: lalaland name: "Apply smth" roles:
        - lala
        - land serial: 1
    - hosts: something else
headcomment: ""
linecomment: ""
footcomment: ""
line: 1
column: 1
```

I traced the execution in yaml.v3 and found that in the marshalDoc function in encode.go
```
node, _ = in.Interface().(*Node)
```
is returning nil for the node at that line...

**Comment by mikefarah** [comment]
Ah found the issue, I need to
```
err := encoder.Encode(&dataBucket)
```

**Comment by hermanbanken** [comment]
@mikefarah thanks! This is literally the only place I could find how to encode yaml.Node. Otherwise I got the error (to help random fellow Googlers):

```
yaml: expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS, but got document start
```
