### ISSUE TITLE
string is not correctly escaped

### ISSUE THREAD

**Issue by itscaro** [go-yaml/yaml#453]
In my Yaml, a string `42340e1` is not quoted, which is not valid. When this yaml is decoded with another language, in my case PHP, the field is considered a float instead of string.

**Comment by niemeyer** [comment]
Can you reproduce this with v3?  I believe this is related to the misrepresentation of floats that was mistakenly changed a while ago. Will backport the fix to v2.

**Comment by itscaro** [comment]
Issue fixed in v3, here is the code used to test. @niemeyer thank you.

```package main

import (
	"fmt"
	"gopkg.in/yaml.v3"
)

type T struct {
	A string
}

func main() {
	out, _ := yaml.Marshal(&T{A: "232e5"})
	fmt.Print(string(out))
}
```
