### ISSUE TITLE
Can't roundtrip string

### ISSUE THREAD

**Issue by nickatsegment** [go-yaml/yaml#456]
For whatever reason, encoding a string adds a newline to the end of it.

https://github.com/nickatsegment/yaml/commit/43afc74c66d32fc4f397d37ceb2d114d2d445007

I added this test to show the problem:

```
$ GO111MODULE=on go test -v ./...
=== RUN   Test

----------------------------------------------------------------------
FAIL: encode_test.go:416: S.TestEncoderSingleDocument

test 0. "null\n"
test 1. "null\n"
test 2. "string"
encode_test.go:425:
    c.Assert(buf.String(), Equals, item.data)
... obtained string = "string\n"
... expected string = "string"


----------------------------------------------------------------------
FAIL: encode_test.go:405: S.TestMarshal

test 0: "null\n"
test 1: "null\n"
test 2: "string"
encode_test.go:412:
    c.Assert(string(data), Equals, item.data)
... obtained string = "string\n"
... expected string = "string"

OOPS: 29 passed, 2 FAILED
--- FAIL: Test (0.01s)
=== RUN   ExampleUnmarshal_embedded
--- PASS: ExampleUnmarshal_embedded (0.00s)
FAIL
FAIL	gopkg.in/yaml.v2	0.019s
```

**Comment by nickatsegment** [comment]
FWIW, PyYAML does something similar:
```
In [10]: yaml.dump("string", default_style='"')
Out[10]: '"string"\n'
```

Python's builtin JSON dumper does what I think is the right thing:
```
In [13]: json.dumps('string')
Out[13]: '"string"'
```

**Comment by nickatsegment** [comment]
I suppose I shouldn't be too surprised.

https://github.com/nickatsegment/yaml/blob/43afc74c66d32fc4f397d37ceb2d114d2d445007/encode_test.go#L42-L45 shows a test where another scalar (`null`) gains a newline

**Comment by niemeyer** [comment]
Yeah, this is intentional. The output of marshaling is suitable to be sent to a file, no matter what the content is, and it's most natural to have the line breaks. It's trivial to strip, though, if that's not what you want.

**Comment by nickatsegment** [comment]
Yeah, makes sense. It's tough to please everyone :)

My workaround was just to use the JSON encoder for scalars, since JSON is a subset of YAML.
