### ISSUE TITLE
Zero-valued, inlined named structs not omitted despite "omitempty" option

### ISSUE THREAD

**Issue by erjoalgo** [go-yaml/yaml#46]

**Comment by niemeyer** [comment]
Can you please provide an example with code, expected output, actual output?

**Comment by erjoalgo** [comment]
package main

import (
    "gopkg.in/yaml.v2"
    "fmt"
)

type Parent struct  {
    Name string 
    MaybeChild Child `yaml:",inline,omitempty"` //should only be included if non-zero
}
type Child struct   {
    Property1, Property2 string
}
func marshalyaml ( y interface{} ) string   {
    str, err := yaml.Marshal(y)
    if err != nil   {
        fmt.Printf( "error marshalling: %s\n", err )
    }
    return string(str)
}
func main (  )  {
    parentWithChild := Parent{MaybeChild:Child{"prop1", "prop2"}, Name:"parent with child"}
    parentNoChild := Parent{Name:"parent without child"}

```
fmt.Printf( "%s\n", marshalyaml(parentWithChild) )
fmt.Printf( "%s\n", marshalyaml(parentNoChild) )
```

}

**Comment by erjoalgo** [comment]
output:

name: parent with child
property1: prop1
property2: prop2

name: parent without child
property1: ""
property2: ""

**Comment by erjoalgo** [comment]
expected: second yaml should not include zero-valued Child struct

**Comment by niemeyer** [comment]
This is intended behavior for the moment. There's already plenty of flexibility by omitting or not (or renaming, etc) individual fields of the inlined document.

Basically, inlining means actual inlining. Fields of the inlined document are seen as being in the outer document.

I'll keep the issue open to have a second consideration of this on another day, but in principle I don't see the demand for the additional logic.

**Comment by niemeyer** [comment]
Yeah, the current behavior looks correct. Inline will pick the omitempty semantics from the inlined fields themselves, which is the correct thing to do in this case.
