### ISSUE TITLE
Embedded struct fields are ignored

### ISSUE THREAD

**Issue by dougrad** [go-yaml/yaml#47]
Say I have:

```
struct A {
  X string
}
struct B {
  A
  Y string
}
var b B
yaml.Unmarshal([]byte("x: abc\ny: def"), &b)
```

This will unmarshal "b.Y" but leave "b.A.X" uninitialized.  This behavior differs from the encoding/xml and encoding/json packages, which will iterate over the fields of all embedded types as if they were at the same level.

Further, I am unable to workaround this with a custom UnmarshalYAML method.  I can unmarshal to the embedded type:

```
func (b *B) UnmarshalYAML(unmarshal func(v interface{}) error) error {
   if err := unmarshal(&b.A); err != nil {
     return err
   }
   return nil
}
```

this will ignore the fields of B, and if I unmarshal to both:

```
func (b *B) UnmarshalYAML(unmarshal func(v interface{}) error) error {
   if err := unmarshal(&b.A); err != nil {
     return err
   }
   return unmarshal(b)
}
```

I get infinite recursion.

**Comment by dougrad** [comment]
OK, I had missed the ",inline" option - that does fix it.  But it's still an unexpected difference from xml / json encoding and should probably be the default.

**Comment by cpliakas** [comment]
@dougrad This saved me a bunch of time, and protected the remaining hair I have left :-). Thanks for posting the solution!
