### ISSUE TITLE
V3 Question: Is it possible to dump yaml.Node expanded?

### ISSUE THREAD

**Issue by cravler** [go-yaml/yaml#477]
I have this code:

``` golang
package main

import (
    "fmt"
    "log"
    "gopkg.in/yaml.v3"
)

var data = `
foo: &FOO
    x: 1
bar: &BAR 3
baz:
    << : *FOO
    y: 2
    z: *BAR
`

func main() {
    unmarshalled := &yaml.Node{}

    err := yaml.Unmarshal([]byte(data), unmarshalled)
    if err != nil {
        log.Fatalf("error: %v", err)
    }

    d, err := yaml.Marshal(unmarshalled.Content[0].Content[5])
    if err != nil {
        log.Fatalf("error: %v", err)
    }
    fmt.Printf("%s\n", string(d))
}
```
My output:
``` yaml
!!merge <<: *FOO
y: 2
z: *BAR
```

But need this:
``` yaml
x: 1
y: 2
z: 3
```

**Comment by niemeyer** [comment]
Yeah, decode the value you want into an interface and marshal that instead:

https://play.golang.org/p/bdvKnRkPcsz

**Comment by cravler** [comment]
but how to keep order?

https://play.golang.org/p/yPh2Ly05Is5

**Comment by cravler** [comment]
and multiple merge throw error

https://play.golang.org/p/MH_RpyD1gpW

**Comment by niemeyer** [comment]
If you want to preserve properties of the node tree while only processing some of it, you'll need to work with the node tree itself and follow the aliases yourself. Should be trivial, though, as there are explicit references in the returned alias nodes.

Latter is a separate problem that needs to be looked into. Can you please file an issue for it?
