### ISSUE TITLE
List unmarshal appends instead of overwriting

### ISSUE THREAD

**Issue by dankinder** [go-yaml/yaml#48]
This may be a "we didn't intend for it to work that way" kind of issue, so pardon me close this if that's the case.

If I'm marshalling into a struct, say:

```
type config struct {
    []string values
}
```

And if do the following:

```
c := &config{
    values: []string{"one"}
}
yaml.Unmarshal([]byte(`config:
    values: ["two"]
`), config)
```

Then I would expect the final struct to have values just be ["two"], overwriting the ["one"] entry. However it gets appended, and my final struct has config.values = ["one", "two"]. Is this expected or something that needs to be fixed?

**Comment by niemeyer** [comment]
Needs to be fixed. Thanks for the report.
