### ISSUE TITLE
Releases taged v2.2.0 onwards appears to be incompatible with go get

### ISSUE THREAD

**Issue by Hucaru** [go-yaml/yaml#496]
When using `go get` on a taged version of v2.2.0 (or against a v3 branch commit) or higher I get the following error message: `parsing go.mod: unexpected module path "gopkg.in/yaml.v2"`.

**Comment by laverya** [comment]
What paths were you `go get`ing @Hucaru? `go get gopkg.in/yaml.v2` works just fine for me - as does `go get gopkg.in/yaml.v3`. 

I'm using Go 1.13, but the behavior should be the same when using modules in previous versions.

**Comment by Hucaru** [comment]
Thanks for reply, after further digging I figured out it was our proxy. It had stopped pulling new modules. I will close the issue

**Comment by mcandre** [comment]
Go modules require that Go packages tagged beyond 1.x use the import path syntax ...`/v<major>`. This package uses the notation ...`.v<major>`.

A quick fix would involve replacing the dot with a slash.

**Comment by laverya** [comment]
`gopkg.in` is an exception - packages there can use paths like `gopkg.in/yaml.v3` instead of `/`. It's mentioned [in this blog post](https://blog.golang.org/v2-go-modules).
