### ISSUE TITLE
New Unmarshaler interface in v3 - when returning an error the parent structure is nil

### ISSUE THREAD

**Issue by tal-sapan** [go-yaml/yaml#499]
I have the following type defined:
```go
type MainStruct struct {
	Seq []*SequenceStruct
}
type SequenceStruct struct {
	Inner_New UnmarshalledStruct_New
}
type UnmarshalledStruct struct {
	Bool1 bool
	Bool2 bool
}
type UnmarshalledStruct_New UnmarshalledStruct
````
The `UnmarshalledStruct_New` type implements the new `Unmarshaler` interface introduced in v3:
````go
func (s *UnmarshalledStruct_New) UnmarshalYAML(node *yaml.Node) error {
	tempStruct := UnmarshalledStruct{}
	if err := node.Decode(&tempStruct); err != nil {
		return err
	}
	*s = UnmarshalledStruct_New(tempStruct)
	return nil
}
````
When an error is returned from `UnmarshalYAML`, instead of using the value of `s` and moving on to the next `SequenceStruct` instance, the parent of the `UnmarshalledStruct_New` structure that returned an error is set to `nil` and the rest of the `SequenceStruct` instances aren't unmarshalled.
For example, after unmarshaling this input:
```yaml
seq:
- inner_new:
    bool1: str
    bool2: 123
- inner_new:
    bool1: str
    bool2: 123
```
The value of `seq` is a slice of `SequenceStruct` with length 2, that contains 2 `nil` values, and the returned `Errors` in the `TypeError` only contains the first 2 errors (those returned from unmarshaling the first `SequenceStruct` instance).

Note: if I implement the old Unmarshaler interface instead it works as expected (all the errors are returned and the `SequenceStruct` values aren't nil). However, I need to support having unknown fields in the `UnmarshalledStruct_New` structure without getting an error (while returning errors for known fields that can't be unmarshaled) and I couldn't find a way to do this with the old interface (since `MainStruct` is decoded with `KnownFields` set to true - only the `UnmarshalledStruct_New` structure should support unknown fields).

**Comment by niemeyer** [comment]
Thanks for the report. I'll look into it.

**Comment by niemeyer** [comment]
With 35294da this should be fixed. Please let me know how it goes.

**Comment by tal-sapan** [comment]
Seems to work fine, thanks!
