### ISSUE TITLE
Unmarshal multiple documents

### ISSUE THREAD

**Issue by beatgammit** [go-yaml/yaml#5]
I see two ways (there are probably others) of doing this cleanly:

```
func UnmarshalMultiple([]byte, interface{}) error
func UnmarshalFirst([]byte, interface{}) (int, error)
```

The first expects a pointer to a `Slice` and does the same as `Unmarshal`, but appends each document to the passed in slice. The second does the same as `Unmarshal` but returns the index into the `[]byte` of the beginning of the next document or `-1` if it's reached the end.

My current use-case is implementing something like [TAP-Y](https://github.com/rubyworks/tapout/wiki/TAP-Y-J-Specification), which is defined as being a stream of documents. Parsing this into a slice of `map[string]interface{}` would make things nicer to work with.

**Comment by niemeyer** [comment]
How's that different from #4?

**Comment by beatgammit** [comment]
This issue was meant to be a minimally invasive as possible to the current API, whereas I prefer the approach in #4 better, especially since this can be implemented with `bufio.Scanner` (that's what I'm currently doing).

I'm undecided as to how parsing multiple documents should work with `Decode`. I think the best approach is to have `Decode` decode a single document, consuming the document delimiter before returning. This way the user could handle multiple documents in a simple loop:

```
dec = yaml.NewDecoder(r)
for dec.Decode(&doc) == nil {
}
```

There could also be a `DecodeAll([]interface{})` to do everything at once.

**Comment by niemeyer** [comment]
Okay, it sounds like this is effectively the same as #4.
