### ISSUE TITLE
Support for non-scalar map keys

### ISSUE THREAD

**Issue by tliron** [go-yaml/yaml#502]
The parser currently does not support non-scalar map keys. However, this is absolutely part of the YAML spec. In [section 10.1.1.1](https://yaml.org/spec/1.2/spec.html#tag/repository/map): "YAML places no restrictions on the type of keys; in particular, they are not restricted to being scalars." Also see [Example 2.11](https://yaml.org/spec/1.2/spec.html#id2760799).

The code is [here](https://github.com/go-yaml/yaml/blob/5420a8b6744d3b0345ab293f6fcba19c978f1183/decode.go#L630).

To be fair, PyYAML, a very widely used YAML parser, also does not support this feature. But Ruby's YAML parser does. (And Python's Ruamel YAML parser does, too.)

I think we absolutely must support this here if we are to adhere to the spec.

**Comment by niemeyer** [comment]
Yes, it does support non-scalar keys:

* https://play.golang.org/p/s7F03ZM1iRv

What you are likely doing is trying to decode into a map with a key type that is not supported by Go itself. That of course won't work.

**Comment by tliron** [comment]
Yes, that is what I'm trying to do. Here is a [playground](https://play.golang.org/p/osrfaG_oBQn). You can see that it errors out.

In my view this is still an issue that needs to be addressed somehow, because it's the one case in which standard YAML cannot be run through `Decode` on a generic map, but can be run through `Unmarshall` on a node struct. The implication is that users of this library cannot rely on `Decode` if they intend to support arbitrary YAML.

If there's no solution, this crucial caveat should at least be part of the documentation.

**Comment by niemeyer** [comment]
The yaml package seems to be doing its job correctly in this case. What's breaking down is the fact that you are trying to decode a yaml list into a map that has a string key. It will not work indeed.

The caveat is that Go map keys cannot be lists. That's in the Go spec itself. But you can decode the content into a yaml.Node and work with it as you please.

**Comment by tliron** [comment]
I understand that, but you'll see a lot of code out there that uses this YAML package in the way that I showed in the playground -- decoding into an arbitrary map. These applications will break if fed with YAML that has non-scalar keys. Users will make the assumption that `Decode` would work with any valid YAML, but that is not the case. At the very least this needs to be warned against in the documentation, though in my view there's room for a better solution (possibly stringifying such bad key values).

**Comment by niemeyer** [comment]
It doesn't matter what people already do or want to do. These are mutually exclusive:

1) Handling non-scalar yaml mapping keys properly
2) Decoding non-scalar yaml mapping keys into a Go map with string keys

The error message should be more clear, though. I'll fix that part.

**Comment by tliron** [comment]
You don't think it's worth adding documentation to the `Decode` function at least warning about non-scalar keys? I understand your approach, but this is a very widely used library and the negative effect could be very widespread.

**Comment by niemeyer** [comment]
It can't possibly be widespread because thankfully the use of non-scalar keys in yaml is not widespread. It's also just one of the many ways you can get bad behavior when shoehorning arbitrary user data into any given fixed type.

If you are dealing with data of unknown type and structure, use yaml.Node.. anything else may misbehave depending on the data and the application logic.

**Comment by tliron** [comment]
How about this: adding a section in the documentation called "Parsing arbitrary data" that explains that `Unmarshall` to node should be used rather than `Decode` into `map[interface{}]interface{}`, due to possible issues with data such as keys. What do you think? I would think you would want to be as helpful as possible to users.

**Comment by tliron** [comment]
So, it seems the committer is not interested in supporting this edge case. However, for completion and for those finding this issue via search engines I would like to offer solutions.

[Here](https://github.com/tliron/puccini/blob/cf6b7dad7b4e7114ff46179978ea79436691d69e/ard/yaml.go) is an example from my codebase. The way I've handled it is by creating my own version of `Node.Decode` that checks for map keys that are likely non-hashable and in that case wrapping the decoded key with a struct and using a pointer to it as the key. Pointers are hashable, so this will "work", but of course the key comparison cannot compare the content of the pointer's reference. This means that there _is no checking for duplicate key errors at this stage_. In my case this check happens elsewhere in the codebase, however another implementation could add a check here by iterating existing keys. Though, of course, note that this check would need be done any time a new value is put into the map.

An alternative solution could be to use a hashtable implementation other than a Go map, for example [this one](https://godoc.org/github.com/timtadh/data-structures/hashtable), which allows for arbitrary keys by implementing an interface. The cost would be that traversing the decoded data would have to take into account this special type, which could be incompatible with similar parsers (JSON, XML, etc.).

**Comment by tliron** [comment]
OK, I have gone further and put my money where my mouth is. :)

I released a library, [yamlkeys](https://github.com/tliron/yamlkeys), that you can use as an add-on to this YAML library in order to handle complex keys.
