### ISSUE TITLE
omitempty lead to a panic

### ISSUE THREAD

**Issue by spyroot** [go-yaml/yaml#504]
Here is the code

```
type AnsibleInventoryHost struct {
	AnsibleConnection   string `yaml:"ansible_connection"`
	AnsibleHost         string `yaml:"ansible_host"`
	AnsiblePort         int    `yaml:"ansible_port"`
	AnsibleUser         string `yaml:"ansible_user"`
	AnsibleSSHExtraArgs string `yaml:"ansible_ssh_extra_args, omitempty"`
}

type AnsibleGroups struct {
	Hosts map[string] *AnsibleInventoryHost `yaml:"hosts"`
}
```

Stack trace below.

ar/go/1.13/libexec #gosetup
GOPATH=/Users/spyroot/.go #gosetup
/usr/local/Cellar/go/1.13/libexec/bin/go build -o /
goroutine 1 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc000295d98)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/yaml.go:249 +0x9a
panic(0x48ca4e0, 0xc0003be1e0)
        /usr/local/Cellar/go/1.13/libexec/src/runtime/panic.go:679 +0x1b2
gopkg.in/yaml%2ev2.(*encoder).structv(0xc0003d0000, 0x0, 0x0, 0x4a4d940, 0xc0003504b0, 0x199)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:211 +0x118
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x4a4d940, 0xc0003504b0, 0x199)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:160 +0x760
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x48473e0, 0xc0003504b0, 0x16)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:154 +0x5d9
gopkg.in/yaml%2ev2.(*encoder).mapv.func1()
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:193 +0x193
gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc0003d0000, 0x0, 0x0, 0xc000293ed8)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:256 +0x146
gopkg.in/yaml%2ev2.(*encoder).mapv(0xc0003d0000, 0x0, 0x0, 0x48c51e0, 0xc000010400, 0x195)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:188 +0x95
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x48c51e0, 0xc000010400, 0x195)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:149 +0x68b
gopkg.in/yaml%2ev2.(*encoder).structv.func1()
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:226 +0x558
gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc0003d0000, 0x0, 0x0, 0xc0002942c8)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:256 +0x146
gopkg.in/yaml%2ev2.(*encoder).structv(0xc0003d0000, 0x0, 0x0, 0x493df80, 0xc000010400, 0x199)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:213 +0xf7
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x493df80, 0xc000010400, 0x199)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:160 +0x760
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x48ca960, 0xc000010400, 0x16)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:154 +0x5d9
gopkg.in/yaml%2ev2.(*encoder).mapv.func1()
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:193 +0x193
gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc0003d0000, 0x0, 0x0, 0xc0002946d8)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:256 +0x146
gopkg.in/yaml%2ev2.(*encoder).mapv(0xc0003d0000, 0x0, 0x0, 0x48c5180, 0xc0000103f8, 0x195)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:188 +0x95
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x48c5180, 0xc0000103f8, 0x195)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:149 +0x68b
gopkg.in/yaml%2ev2.(*encoder).structv.func1()
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:226 +0x558
gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc0003d0000, 0x0, 0x0, 0xc000294ac8)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:256 +0x146
gopkg.in/yaml%2ev2.(*encoder).structv(0xc0003d0000, 0x0, 0x0, 0x493df00, 0xc0000103f8, 0x199)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:213 +0xf7
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x493df00, 0xc0000103f8, 0x199)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:160 +0x760
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x48ca900, 0xc0000103f8, 0x16)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:154 +0x5d9
gopkg.in/yaml%2ev2.(*encoder).mapv.func1()
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:193 +0x193
gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc0003d0000, 0x0, 0x0, 0xc000294ed8)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:256 +0x146
gopkg.in/yaml%2ev2.(*encoder).mapv(0xc0003d0000, 0x0, 0x0, 0x48c5120, 0xc0002d3d10, 0x195)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:188 +0x95
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x48c5120, 0xc0002d3d10, 0x195)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:149 +0x68b
gopkg.in/yaml%2ev2.(*encoder).structv.func1()
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:226 +0x558
gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc0003d0000, 0x0, 0x0, 0xc0002952c8)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:256 +0x146
gopkg.in/yaml%2ev2.(*encoder).structv(0xc0003d0000, 0x0, 0x0, 0x4911ae0, 0xc0002d3d10, 0x199)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:213 +0xf7
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x4911ae0, 0xc0002d3d10, 0x199)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:160 +0x760
gopkg.in/yaml%2ev2.(*encoder).structv.func1()
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:226 +0x558
gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc0003d0000, 0x0, 0x0, 0xc0002956c0)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:256 +0x146
gopkg.in/yaml%2ev2.(*encoder).structv(0xc0003d0000, 0x0, 0x0, 0x4996e40, 0xc0002d3d00, 0x199)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:213 +0xf7
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x4996e40, 0xc0002d3d00, 0x199)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:160 +0x760
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0003d0000, 0x0, 0x0, 0x4915380, 0xc0002d3d00, 0x16)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:154 +0x5d9
gopkg.in/yaml%2ev2.(*encoder).marshalDoc(0xc0003d0000, 0x0, 0x0, 0x4915380, 0xc0002d3d00, 0x16)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:93 +0x10e
gopkg.in/yaml%2ev2.Marshal(0x4915380, 0xc0002d3d00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/spyroot/.go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/yaml.go:203 +0x370
github.com/spyroot/jettison/ansibleutil.(*AnsibleInventoryHosts).WriteToFile(0xc0002d3d00, 0x0, 0x0)

**Comment by schattian** [comment]
U have a typo; its `yaml:"ansible_ssh_extra_args,omitempty"` (without the space).

**Comment by spyroot** [comment]
I'll re-check I think it was in both cases.

**Comment by niemeyer** [comment]
The error should be indicative of the issue. It was omitted above so it's not clear what was the actual error emitted.

If you still have the issue, please try to reproduce it at play.golang.org so we can look at it.
