### ISSUE TITLE
Stop using gopkg.in

### ISSUE THREAD

**Issue by djmitche** [go-yaml/yaml#506]
It looks lke gopkg.in is again having issues (similar to #401): https://github.com/niemeyer/gopkg/issues/67.  There's a stunning silence from the gopkg.in maintainers on that issue.  We have been forced to work around this [using `replace` declarations in our application](https://github.com/taskcluster/taskcluster/pull/1354/files)

Please consider making the package path for yaml `github.com/go-yaml/yaml`, perhaps for a new major version.

**Comment by niemeyer** [comment]
The gopkg.in server is being moved to a different data center right now, partly due to its increased usage. Bashing the server with a loop won't be very helpful for you or for others.
