### ISSUE TITLE
v3 equivalent of v2's MapSlice and MapItem?

### ISSUE THREAD

**Issue by jmhodges** [go-yaml/yaml#527]
I'm sure there's a very obvious answer to this, but v2 has the very handy MapSlice and MapItem types for order-preserving parses and emission.

What's the v3 method of keeping the round-tripping stable?

**Comment by niemeyer** [comment]
You probably figured it out by now, but yaml.Node is a significantly superior version of it.

**Comment by jmhodges** [comment]
Well, it’s taken a lot longer to get the same work done with it, unfortunately. I was hoping there was a simpler API available because it was really fiddly.

**Comment by jmhodges** [comment]
Sorry should have left an example: I had to figure out on my own that MappingNodes have their keys at the even indexes of Content, and values in the odd indexes. And then do the fiddly work for updating that, too)

**Comment by FelicianoTech** [comment]
@jmhodges Do you have  code example of what you did?

**Comment by echarrod** [comment]
Would also appreciate an example! 

I found some other solutions, but none seem very succinct:
- https://stackoverflow.com/questions/63254684/unmarshalling-yaml-to-ordered-maps
- https://stackoverflow.com/questions/48569309/unmarshal-go-yaml-to-either-a-map-or-a-string

Also related: https://github.com/go-yaml/yaml/issues/698
