### ISSUE TITLE
Unmarshaling then Marshaling data produces different result

### ISSUE THREAD

**Issue by belak** [go-yaml/yaml#530]
I was wondering if there's a reason that lines get split like this. It seems to be unmarshalled properly (the node contains the value with the space, not the string), but it would be really nice to keep it in the long line if possible.

Sample code:

```
package main

import (
	"fmt"
	"strings"

	yaml "gopkg.in/yaml.v3"
)

func main() {
	data := `
keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIIdmFwaB4lwmogg7ggFE8M45Zywx1W3T7dGktY563FM k.elwert@Mac-02WF1MLHTD6
`

	var n yaml.Node
	yaml.Unmarshal([]byte(data), &n)
	out, _ := yaml.Marshal(&n)

	fmt.Println(string(out))

	if strings.TrimSpace(string(out)) != strings.TrimSpace(data) {
		fmt.Println("Data doesn't match")
	}
}
```

Output:
```
keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIIdmFwaB4lwmogg7ggFE8M45Zywx1W3T7dGktY563FM
    k.elwert@Mac-02WF1MLHTD6

Data doesn't match
```

**Comment by niemeyer** [comment]
The data is exactly the same in fact, and most importantly, it's also correct:

   https://play.golang.org/p/IurrfN5__oN

The _style_ is indeed not the same, and although v3 does much better in terms of preserving the content style, it still does not attempt to match the input exactly.

What you are seeing there is a result of the line length configuration. We have a PR open to allow tuning it, and we'll most likely get it or something similar to it merged in the near future. We've just been waiting for v3 to stabilize in general before introducing further complexity.

**Comment by belak** [comment]
I guess that's what I was running into - I tried all the different Style options on the node type, but none of them seemed to accomplish what I wanted.

In any sense, as long as the data is the same when unmarshaled it doesn't matter too much, it was just an oddity I wasn't sure about.

Thanks for following up! I'm really liking v3 so far - it's been nice to directly modify the node tree to preserve comments.
