### ISSUE TITLE
Should decoding/encoding yaml.Node preserve whitespace

### ISSUE THREAD

**Issue by dprotaso** [go-yaml/yaml#534]
See the example here: https://play.golang.org/p/k91cIcYIArO

Should `yaml.Node` be round-trippable wrt. to whitespace?

**Comment by niemeyer** [comment]
v3 deals much better with preservation of style and formatting, but it doesn't have perfect roundtripping as a goal right now.

**Comment by arbourd** [comment]
I understand that it's not a goal right now, but is this a feature we could request? `yq` has become extremely popular and with Kubernetes and YAML, preserving whitespace would be a lovely feature.

Thanks so much for the comments and other preserved artifacts in v3 either way! ❤️
