### ISSUE TITLE
Node.Decode panics when Node is empty

### ISSUE THREAD

**Issue by Kanshiroron** [go-yaml/yaml#545]
version: v3.0.0-20190924164351-c8b7dadae555

Hello,

We have a field in our YAML that is of type `Node` and may not be present. When trying to decode a Node that has not been defined in the YAML file, the `Decode` function panics (even if the `omitempty` annotation is present):
```
panic: internal error: unknown node kind: 0 [recovered]
	panic: internal error: unknown node kind: 0

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc0000f54c0)
	/home/me/gopath/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190924164351-c8b7dadae555/yaml.go:276 +0x9a
```

So I'm wondering what's the best way of handling it:
- Should the `Decode` function return the passed structure without modifying it?
- Or should a new `IsEmpty` function added to the `Node` struct, that will check if the Node has been filled (i.e: `kind != 0`)?

Thanks for your help

**Comment by niemeyer** [comment]
That's been fixed with e307989. Thanks for reporting.
