### ISSUE TITLE
untagged exported fields with uppercase characters after first character are not unmarshalled

### ISSUE THREAD

**Issue by farrellit** [go-yaml/yaml#547]
Exported fields in a struct that have an uppercase character within them, are not picked up by Yaml.v2 without explicit annotation..  They are imported properly by "encoding/json" with the implicit annotation.  

Note below that the same json source sets `T.FieldName` and `T.Another_name` but Yaml misses it.  They both update `T.Works_everywhere` which only has one uppercase.

I'm not using the field annotations; I'd assume that would change behavior.  I don't see that it's common for folks to use the implicit annotations but it is a point of inconsistency between json and yaml.  

```
$ go run t.go
JSON: &{FieldName:value Another_Name:anotherValue Works_everywhere:only-leading-uppercase}
YaML: &{FieldName: Another_Name: Works_everywhere:only-leading-uppercase}
```

```
$ cat t.go
package main
import (
  "fmt"
	"encoding/json"
	"gopkg.in/yaml.v2"
)

type T struct {
	FieldName string
	Another_Name string
	Works_everywhere string
}

func main() {
	input := []byte(`{"fieldName": "value", "another_Name": "anotherValue", "works_everywhere": "only-leading-uppercase"}`)
	t := new(T)
	if err := json.Unmarshal(input, &t); err != nil {
		panic(err)
	}
	fmt.Printf("JSON: %+v\n", t)
	t = new(T)
	if err := yaml.Unmarshal(input, &t); err != nil {
		panic(err)
	}
	fmt.Printf("YaML: %+v\n", t)
}
```

**Comment by niemeyer** [comment]
The convention field marshaling and unmarshaling is different for the json and yaml packages, and json became more flexible over time accepting a fallback of any casing by default.

The yaml package consistently lowercases the field by default, as that's more usual in yaml files themselves, but not universal.

The idea of a single consistent pattern still seems reasonable. If you want to marshal back those strings, you'll need the explicit annotations in any case or the output will be wrong.
