### ISSUE TITLE
Comments are incorrectly parsed in lists

### ISSUE THREAD

**Issue by vsapronov** [go-yaml/yaml#550]
Here's an example:
```yaml
some-list:
- first   # one
- second   # two
- third   # three
```

Expected: array of nodes, each node having `LineComment` set to corresponding comment.
Reality:
`first` node with *empty* `HeadComment`, `LineComment`, `FootComment`.
`second` node with `HeadComment` == `one` and empty other comment fields
`third` node with `HeadComment` == `two` and `LineComment` == `three`

**Comment by niemeyer** [comment]
Sorry about that. I broke this when special casing to handle the construct described in #533.

Both cases now work properly with 4206685.
