### ISSUE TITLE
Support encoding values back into Node

### ISSUE THREAD

**Issue by vsapronov** [go-yaml/yaml#554]
I'm trying to write free form YAML that respects order of keys in map.
Currently I'm using v2 for this and `MapSlice`. It guarantees order and it's value part being encoded into YAML correctly from any `interface{}`.
From what I get in v3 I'm supposed to use `Node` instead of `MapSlice`. However I can't get how to write value into `Node`. `Node.Value` is YAML string representation so I can't just put there `interface{}` value.

Overall my use case is composing free form YAML. In v2 I was able to do so by using `[]interface{}` for arrays and `MapSlice` for maps. They could be nested. Passing root of those structure into `yaml.Marshal` gave me YAML of my free-form data structure.

I would appreciate any help. Thank you.

**Comment by niemeyer** [comment]
That's a valid concern, thanks for the input.

I think the correct solution here is to implement something like Node.Encode, which is the opposite of Node.Decode: it would accept an interface{}, and make the Node represent the Go value provided. This way it would be trivial to implement even MapSlice itself again locally, if that's desired, or any similar variation that would fit the problem at hand.

**Comment by egorse** [comment]
Wouldn't just unmarshal to
```
type T struct {
  Yaml map[string]interface{} `yaml:"-,inline"
}
```
works fine?

**Comment by vsapronov** [comment]
@egorse I was asking about marshaling (with guaranteed order) - not unmarshaling.
"I'm trying to write free form YAML that respects order of keys in map." - not to read it, but to write it - marshaling... Other text in the issue description also clearly indicates that my Go code is producing YAML not parsing it.

**Comment by ashrayjain** [comment]
@vsapronov @niemeyer I have the same problem when trying to replace my existing uses of MapSlice with Node in v3.

What is the current recommendation for doing this?

**Comment by niemeyer** [comment]
I'll fix that as described above. Let me see if I can find a slot today for some more work here.

**Comment by niemeyer** [comment]
Alright, can you please test current v3 (change in 6ec2bf8) and let me know if that solves your concerns please.

**Comment by abourget** [comment]
Anyone has the MapSlice implementation based on those Nodes?
