### ISSUE TITLE
Mark v3 branch as default.

### ISSUE THREAD

**Issue by willemavjc** [go-yaml/yaml#568]
This is mainly a request and discussion proposal:
It has been around a year now since v3 is out. 
Is v3 not enough stable to mark it as default branch rather than v2?

**Comment by willemavjc** [comment]
Note: I just saw there is no release tag either. (GitHub > Releases : v2.x only)
Why so?

**Comment by niemeyer** [comment]
Yes, the time is coming. I want to review a few last details before tagging it, but we're close.

I will keep this open and close it when tagging so those interested can subscribe to it.

**Comment by niemeyer** [comment]
Actually, we already have #487 for this. Closing this one.
