### ISSUE TITLE
Go get from GitHub instead of gopkg.in/yaml.v2

### ISSUE THREAD

**Issue by hsluoyz** [go-yaml/yaml#570]
The domain `gopkg.in` is blocked in China. `github.com` is much better. Can we switch the path to github? Thanks.

**Comment by niemeyer** [comment]
Unfortunately we won't do that at this time. People have been using the gopkg.in path for a long time and we can't just break them by changing the code. Once the modern go command is ubiquitous, we'll look into the situation again.
