### ISSUE TITLE
Question: Is it correct to assume that MappingNode key/value children share the same hierarchy level?

### ISSUE THREAD

**Issue by Lantero** [go-yaml/yaml#573]
Not sure if an issue is the best place to ask a question, but could not find a better way.

I'm currently working on a project that needs to use the new `Node` intermediate interface. While playing with it to understand its internals, I found something that looked a bit counter-intuitive to me, but that could be well part of the yaml spec, so I just want to confirm my assumption is correct.

So, given this file:

```yaml
foo: 5
bar: 6
```

What I get is a top level `DocumentNode`, which is composed of a single child `MappingNode`. All good until here. The unexpected was when I found that the children are 4 `ScalarNode` in the sequence of key-value-key-value (foo, 5, bar, 6), as if they were inside a `SequenceNode`.

**Can I safely assume that all the even indexes of `MappingNode` children are keys, whilst the odd indexes are the values?**

Thank you.

**Comment by niemeyer** [comment]
That's exactly right. This preserves the ordering and allows a more compact and fast representation. It won't change in v3 as that would break the API, and most likely won't change in v4+ either. Sorry that it's not yet documented properly.

**Comment by Lantero** [comment]
Thank you for the quick answer and the information regarding v3/v4.

I totally understand efficiency is needed here over any human mental model. Just making sure I wasn't going too far without confirmation. :+1:
