### ISSUE TITLE
Use the yml tag similarly to the yaml tag

### ISSUE THREAD

**Issue by ilyakaznacheev** [go-yaml/yaml#576]
YAML supports both `.yaml` and `.yml` file extensions by default.
For many people, it's more common to use `yml` instead of `yaml`.

According to documentation only `yaml` tag will be parsed.

I assume it would be very helpful to add `yml` synonym to a structure parser.
Or if it works this way already (I haven't found it in the source) add to the docs.

**Comment by niemeyer** [comment]
Consistency wins here, so it's best to have a single one than teaching everybody to read and write both with the same meaning. I wish filenames were also consistent.
