### ISSUE TITLE
How to build array structures in inline form in go-yaml

### ISSUE THREAD

**Issue by kallydev** [go-yaml/yaml#581]
Hi, there! I encountered a problem building the inline structure that defines the array, and I expect to output the results in the following format.

```yaml
items:
  - {name: xxx, description: xxx}
  - {name: xxx, description: xxx}
```

But I couldn't do this with flow and inline, respectively, and inline threw an error:

```text
option ,inline may only be used on a struct or map field
```

The structure I define is:

```golang
type Data struct {
	Items []Item `yaml:"items"`
}

type Item struct {
	Name        string
	Description string
}
```

I have the following confusion:
- I need to generate a configuration file in this format. I have no way to change the configuration file format
- I tested the v2 and v3 versions, and they both result the same
- I didn't try to use map, because it's too flexible for this
- This syntax exists in YAML, but it seems that go-yaml does not fully support it

This is the code for testing [The Go Playground](https://play.golang.org/p/P7HarIL5Fm2)

**Comment by kallydev** [comment]
No help

**Comment by dongxiaba** [comment]
I have the same

**Comment by ichenhe** [comment]
the same problem. Have you found any workarounds? @kallydev @dongxiaba

**Comment by kallydev** [comment]
> the same problem. Have you found any workarounds? @kallydev @dongxiaba

Unfortunately, this issue is still unresolved. But I have done this part using JSON.
