### ISSUE TITLE
v3  marshalling of  "boolean" strings breaks YAML 1.2 interoperability.

### ISSUE THREAD

**Issue by tcolgate** [go-yaml/yaml#582]
In v2:
```go
package main

import (
        "fmt"
        "log"

        yaml "gopkg.in/yaml.v2"
        //yaml "gopkg.in/yaml.v3"
)

func main() {
        data := struct {
                ID string `yaml:"id"`
        }{ID: "off"}
        bs, err := yaml.Marshal(data)
        if err != nil {
                log.Fatalf("err: %v", err)
        }
        fmt.Println(string(bs))
}
```

this prints:
```
id: "off"
```

in v3:
```
id: off
```

The field is a string, and should marshal, and re-unmarshal as one.

**Comment by tcolgate** [comment]
I'm pretty confused now, I can't recreate this in the tests. I've checked the commit I'm using, it's a6ecf24a6d71 , which is the same as the checkout I'm running the tests on.

**Comment by tcolgate** [comment]
okay, the test I added was bad. it works if the string is "true", it doesn't work if the string is "off"

**Comment by tcolgate** [comment]
okay, it has just occurred to me as to what is happening here. I saw a comment around the yaml spec change for these values, and you are now only handling true/false with the quote enforced marshaling.
This means the output effectively needs to be read with a reader that also adheres to the spec, and cleanly.
I'm not really sure how/if to fix this. Ideally we'd marshal these out as quoted, because it fixes my problem, but the world doesn't revolve around me.

**Comment by tcolgate** [comment]
So, in a sort of begging/pleading sense, I would suggest that marshaling the old 1.2 "boolean" strings as quoted strings would not, strictly speaking, be a break from the spec maybe?

**Comment by niemeyer** [comment]
Yes, you're right and the change makes sense. We should quote strings that match 1.1 booleans.
