### ISSUE TITLE
Marshalling Multiple Documents

### ISSUE THREAD

**Issue by EnriqueL8** [go-yaml/yaml#584]
I see that work has been done to `Unmarshall` multiple documents #232 , and it would be nicer to have an expressive API such as: `yaml.UnMarshallDocuments` without having to work with decoder.

I have a yaml file with multiple documents, which I have unmarshalled each into a struct. Now I would like to marshall an array of those struct back to a yaml file. I haven't really found a solution... Is there a clear example for this?

**Comment by 0xThiebaut** [comment]
I second this need as [Sigma relies on multiple documents per file](https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_mal_creddumper.yml). This lack of feature makes it currently impossible to group similar documents in a same file without manually defining the separator.

**Comment by niemeyer** [comment]
I might be misunderstanding the issue, but the way we handle this is instead with Encoder and Decoder, and with encoding and decoding individual documents in a loop.

Is that not working for you, or haven't tried that?

I'll assume the latter and close the bug, but please comment if I misunderstood.
