### ISSUE TITLE
Marshaling of yaml.Node value not supported, *yaml.Node pointer is supported

### ISSUE THREAD

**Issue by worldturner** [go-yaml/yaml#588]
(v3 branch)

encode.go has support for marshaling `*yaml.Node` in structs, but not `yaml.Node` values:

https://github.com/go-yaml/yaml/blob/v3/encode.go#L119

This seems to be an oversight, as for other data types like `time.Time`, both the pointer and the value version are supported.

I can provide a pull request for this problem which adds support and test cases for the value and the pointer version of `yaml.Node`, if this would be accepted.

**Comment by worldturner** [comment]
Seems related to #575

**Comment by Yohox** [comment]
the fork can work
https://github.com/Yohox/yaml

**Comment by niemeyer** [comment]
That's sorted in a81ed60. Thanks for the report.
