### ISSUE TITLE
v3: Consider providing references to keys<=>values in MappingNodes

### ISSUE THREAD

**Issue by ahmetb** [go-yaml/yaml#599]
So if you haven't realized from my issues so far I'm very happily using go-yaml.v3.

Something I've found my self doing over and over is building two `map[*yaml.Node]*yaml.Node` trees to navigate a MappingNode later on.

One of these maps is for `keys => values` another one is `values => keys`.

The reason I keep doing it is because in go-yaml.v3, a yaml like:

```yaml
foo:
  k1: v1
  k2: [a,b]
```

actually translates to

```text
rootNode [kind=MappingNode], with .Contents:
  - k1 [kind=ScalarNode]
  - v1 [kind=ScalarNode]  
  - k2 [kind=ScalarNode]
  - array [kind=SequenceNode], with .Contents
    - a [kind=ScalarNode]
    - b [kind=ScalarNode]
```

And I keep myself writing recursive code with funky logic like:

```go
if node.Kind == yaml.MappingNode {
	for i, ch := range node.Contents {
		if i % 2 = 0 {
			// means a map key
		} else {
			// means a map value
		}
	}
}
```

So if there was

- some indicator if the Node is a "key" or "value" in a MappingNode
- if a "key", ref to its "value" (and vice versa)

I could be more productive as a developer.

**Comment by niemeyer** [comment]
yaml.Node has a foot in two different places: performance, and convenience. The vast majority of people are not looking at the Node content, but at the decoding of it into their own structures. So our current intermediate representation is a compromise between these two factors. It means both maps and sequences store their data in a similar way, and in a single contiguously allocated array.

We may revisit it at some point, but it's a bit late for v3.
