### ISSUE TITLE
parsing top level array does not work

### ISSUE THREAD

**Issue by eatwithforks** [go-yaml/yaml#601]
https://play.golang.org/p/p1ET6_ZZ29P
```
package main

import (
	"fmt"
	yaml "gopkg.in/yaml.v2"
)

type PublicKey struct {
	Id  int
}

func main() {
	keysBody := []byte(`---\n- id: 1\n`)
	keys := make([]PublicKey, 0)
	yaml.Unmarshal(keysBody, &keys)
	fmt.Println("keys are", keys)
}
```

generates an empty array. similar things work fine in golang's json and other yaml implementation ie. ruby 
```
>> YAML.load(%{---\n- id: 1\n})
=> [{"id"=>1}]
```

**Comment by rogpeppe** [comment]
You've got the wrong kind of quotes for your body - YAML doesn't recognise `\n` escapes itself.
It looks to me as if this works as expected when actual newlines are used: https://play.golang.org/p/cuOahTrnC1F
