### ISSUE TITLE
Support for Unmarshalling strict in yaml v3

### ISSUE THREAD

**Issue by harkishen** [go-yaml/yaml#602]
We were working around validating the yaml fields inside the rules files, Prometheus. However, we faced an issue that the yaml v3 unmarshalling does not throw an error if it finds unknown fields inside the bytes stream. Earlier we were using `Unmarshalstrict()` from yaml v2 which was effective to handle this.

Hence, it will be good if yaml v3 supports `Unmarshalstrict()`. Any other workaround would be great to know as well.

**Comment by brian-brazil** [comment]
#557 and #460 seem relevant here.

**Comment by niemeyer** [comment]
We've replaced "strict" unmarshaling, which is an open-ended term, by more specific terms. The feature you're looking for is currently supported as KnownFields(true/false) in the decoder. We indeed need a way to pass those to the Node.
