### ISSUE TITLE
Multiple maps flagged as inline cause panic

### ISSUE THREAD

**Issue by 0xThiebaut** [go-yaml/yaml#603]
I am looking to use the `inline` flag on two map fields. This allows me to have strongly-typed structures while the object itself ensures the keys don't overlap.

```go
type Detection struct {
	Selections map[string]Selections `yaml:",inline,omitempty"`
	Keywords   map[string]Keywords   `yaml:",inline,omitempty"`
	TimeFrame  string                `yaml:",omitempty"`
	Condition  string                `yaml:",omitempty"`
}
```
However, when I marshal the above code, I end up with the following error:

> ```
> panic: Multiple ,inline maps in struct project.Detection [recovered]
>         panic: Multiple ,inline maps in struct project.Detection
> ```

As a work-around I have currently merged the two maps into a single one, this however leads to additional over-head as I can't enforce the content of the `interface{}`.

```go
type Detection struct {
	Selections map[string]interface{} `yaml:",inline,omitempty"`
	TimeFrame  string                 `yaml:",omitempty"`
	Condition  string                 `yaml:",omitempty"`
}
```

I was wondering what the reasoning was behind enforcing a single `inline` flag limit for maps while the same is not done for structures. This is quite surprising given the fact this limit is never documented.

From [`yaml/yaml.go`](https://github.com/go-yaml/yaml/blob/770b8dae4cf00919e5eafffbd8d58186294b61b5/yaml.go#L357-L384):
```go
			switch field.Type.Kind() {
			case reflect.Map:
				if inlineMap >= 0 {
					return nil, errors.New("Multiple ,inline maps in struct " + st.String())
				}
				if field.Type.Key() != reflect.TypeOf("") {
					return nil, errors.New("Option ,inline needs a map with string keys in struct " + st.String())
				}
				inlineMap = info.Num
			case reflect.Struct:
				sinfo, err := getStructInfo(field.Type)
				if err != nil {
					return nil, err
				}
				for _, finfo := range sinfo.FieldsList {
					if _, found := fieldsMap[finfo.Key]; found {
						msg := "Duplicated key '" + finfo.Key + "' in struct " + st.String()
						return nil, errors.New(msg)
					}
					if finfo.Inline == nil {
						finfo.Inline = []int{i, finfo.Num}
					} else {
						finfo.Inline = append([]int{i}, finfo.Inline...)
					}
					finfo.Id = len(fieldsList)
					fieldsMap[finfo.Key] = finfo
					fieldsList = append(fieldsList, finfo)
				}
```

**Comment by niemeyer** [comment]
The reason is we can't tell which map is the proper map to dump values into, or what to do if we find conflicts in them. It's indeed a constraint we have at the moment, and seems worth having it.
