### ISSUE TITLE
为什么生成的yaml 第一行永远是空行呢？

### ISSUE THREAD

**Issue by ruixule** [go-yaml/yaml#604]
s := School{
		Teacher: Teacher{
			Sub:     "计算机",
			TeaAge:  32,
			TeaName: "张三",
		},
		Student: Student{
			StuName: "芮",
			StuAge:  24,
		},
		//Other: []string{"rxl","ryl"},
	}
	out, err := yaml.Marshal(s)
	if err != nil {
		log.Println(err)
		panic(err)
	}
	fmt.Printf("%v",string(out))
	//StructToYamlFile(string(out))
	file, err := os.Create("./rxl89.yaml")
	if err != nil {
		fmt.Println(err)
		panic(err)
	}
	defer file.Close()
	d := yaml.NewEncoder(file)
	defer d.Close()
	errE := d.Encode(string(out))
	if errE != nil {
		fmt.Println(errE)
		panic(errE)
	}

为什么， 生产的文件的第一行空行？
|
  Teacher:
    Sub: 计算机
    TeaName: 张三
    TeaAge: 32
  Student:
    StuName: 芮
    stuage: 24

这个是生成的文件内容 ？还有朋友遇到过吗

**Comment by ruixule** [comment]
知道了 errE := d.Encode(string(out)) ，进行encode 的时候只能传入 对应的结构体，不能为yaml,Mashzhi之后的 string 类型

**Comment by niemeyer** [comment]
That line is not empty. It has a "|" marker that is there to qualify the multi-line string coming next. This is a file with a single yaml value that is a formatted string.
