### ISSUE TITLE
Unable to Parse Nested Array of Objects

### ISSUE THREAD

**Issue by avinash92c** [go-yaml/yaml#612]
My YML:
```
---
users:
  - id: 1
    name: user1
    email: user1@email.com
  - id: 2
    name: user2
    email: user2@email.com
  - id: 3
    name: user3
    email: user3@email.com
```
My Structs:
```
type Users struct {
	MyUsers []User `xml:"user" json:"users" yaml:"users"`
}

type User struct {
	ID    int    `xml:"id" json:"id" yaml:"id"`
	Name  string `xml:"name" json:"name" yaml:"name"`
	Email string `xml:"email" json:"email" yaml:"email"`
}
```
My Error:

> 2020/05/15 23:06:43 yaml: unmarshal errors:
>   line 2: cannot unmarshal !!map into []main.User

Can you help me figure out whats wrong with my code.

**Comment by niemeyer** [comment]
Probably, but there's no code here. Can you please provide a link to code in play.golang.org demonstrating the issue?

**Comment by avinash92c** [comment]
NeverMind i figured what i did wrong. i passed in the wrong reference in. Thank you for the assistance

**Comment by aaronleopold** [comment]
I am new to Go and am having a similar issue, I'm really not sure what I am doing wrong but I'll paste some code below if anyone is able to help me out:

```go
type Playlist struct {
	name string `yaml:"name"`
	id string `yaml:"id"`
}

type YMLConfig struct {
	playlists []Playlist `yaml:"playlists"`
}

func initPlaylists() (Playlist, error) {
    config, err := ioutil.ReadFile(configPath)
    if err != nil {
		return playlist, errors.New("WHAT?")
    }

    var yml YMLConfig 
    err = yaml.Unmarshal(config, &yml)

    if err != nil {
        log.Fatalf("Unmarshal: %v", err)
    }

    fmt.Println(yml)

   // you can ignore this return I know its the wrong type for now
    return playlist, nil
}
```

`data.yml`
```yml
playlists:
  - name: somename
    id: someid
```

output: `{[]}`

**Comment by pradeepkusingh** [comment]
> I am new to Go and am having a similar issue, I'm really not sure what I am doing wrong but I'll paste some code below if anyone is able to help me out:
> 
> ```go
> type Playlist struct {
> 	name string `yaml:"name"`
> 	id string `yaml:"id"`
> }
> 
> type YMLConfig struct {
> 	playlists []Playlist `yaml:"playlists"`
> }
> 
> func initPlaylists() (Playlist, error) {
>     config, err := ioutil.ReadFile(configPath)
>     if err != nil {
> 		return playlist, errors.New("WHAT?")
>     }
> 
>     var yml YMLConfig 
>     err = yaml.Unmarshal(config, &yml)
> 
>     if err != nil {
>         log.Fatalf("Unmarshal: %v", err)
>     }
> 
>     fmt.Println(yml)
> 
>    // you can ignore this return I know its the wrong type for now
>     return playlist, nil
> }
> ```
> 
> `data.yml`
> 
> ```yaml
> playlists:
>   - name: somename
>     id: someid
> ```
> 
> output: `{[]}`

Struc field name must be init caps. Name, Id.

type Playlist struct {
	name string `yaml:"name"`
	id string `yaml:"id"`
}

**Comment by avinash92c** [comment]
Notice the CapCase Of Variables in the structs
```
func main() {
	initPlaylists()
}

type Playlist struct {
	Name string `yaml:"name"`
	Id   string `yaml:"id"`
}

type YMLConfig struct {
	Playlists []Playlist `yaml:"playlists"`
}

func initPlaylists() (Playlist, error) {
	config, err := ioutil.ReadFile(`app.yml`)
	if err != nil {
		return Playlist{}, errors.New("WHAT?")
	}

	log.Println(string(config))

	var yml YMLConfig
	err = yaml.Unmarshal(config, &yml)

	if err != nil {
		log.Fatalf("Unmarshal: %v", err)
	}

	fmt.Println(yml)

	// you can ignore this return I know its the wrong type for now
	return Playlist{}, nil
}
```

YML:
```
playlists:
  - name: somename
    id: someid
  - name: someothername
    id: someotherid
```
RESULT
`{[{somename someid} {someothername someotherid}]}`

**Comment by wjkcoder** [comment]
> I am new to Go and am having a similar issue, I'm really not sure what I am doing wrong but I'll paste some code below if anyone is able to help me out:
> 
> ```go
> type Playlist struct {
> 	name string `yaml:"name"`
> 	id string `yaml:"id"`
> }
> 
> type YMLConfig struct {
> 	playlists []Playlist `yaml:"playlists"`
> }
> 
> func initPlaylists() (Playlist, error) {
>     config, err := ioutil.ReadFile(configPath)
>     if err != nil {
> 		return playlist, errors.New("WHAT?")
>     }
> 
>     var yml YMLConfig 
>     err = yaml.Unmarshal(config, &yml)
> 
>     if err != nil {
>         log.Fatalf("Unmarshal: %v", err)
>     }
> 
>     fmt.Println(yml)
> 
>    // you can ignore this return I know its the wrong type for now
>     return playlist, nil
> }
> ```
> 
> `data.yml`
> 
> ```yaml
> playlists:
>   - name: somename
>     id: someid
> ```
> 
> output: `{[]}`

I have the same problem, have you made it out?

**Comment by aaronleopold** [comment]
> I have the same problem, have you made it out?

@wjkcoder the solution is above, @avinash92c pointed it out - the fields must start with a capital letter
