### ISSUE TITLE
v3 short tags: incorrect encoding on second exclamation

### ISSUE THREAD

**Issue by Foxcapades** [go-yaml/yaml#616]
**Version**: v3.0.0-20200506231410-2ff61e1afc86
**Issue**: When encoding short tags, the second exclamation mark in the tag marker is encoded as `%21`.
**Setup**:
```go
func main() {
	enc := yaml.NewEncoder(os.Stdout)

	nodeA := &yaml.Node{
		Kind: yaml.MappingNode,
		Tag: "!!map",
		Style: yaml.TaggedStyle,
	}

	enc.Encode(nodeA)

	nodeB := &yaml.Node{
		Kind: yaml.MappingNode,
		Tag: "tag:yaml.org,2002:map",
		Style: yaml.TaggedStyle,
	}

	enc.Encode(nodeB)
}
```
**Expected Output**:
```
!!map {}
---
!!map {}
```
**Actual Output**:
```
!%21map {}
---
!!map {}
```
**Workaround**: Use longform tags

**Comment by niemeyer** [comment]
That's been fixed with c1a7af8. Thanks for the report.
