### ISSUE TITLE
Support encoding to Node

### ISSUE THREAD

**Issue by shibe2** [go-yaml/yaml#617]
When writing marshalers for big structures, one may want to change just a few things and keep default encoding for most of the fields. Currently, those are the ways to do this:

1. copy all the needed values to another big structure;
2. construct a complex Node structure, duplicating the library functionality;
3. marshal it as is to bytes, then use some trick to unmarshal to Node, and then make changes to the Node structure.

With direct encoding to Node the task would be more straightforward.

**Comment by niemeyer** [comment]
This was described earlier in #554, and was addressed today with 6ec2bf8.
