### ISSUE TITLE
yamlenums

### ISSUE THREAD

**Issue by igrmk** [go-yaml/yaml#618]
I didn't find anything like jsonenums for this library so I built it myself https://github.com/igrmk/yamlenums.
Does anybody has an interest in it?
Is it a good idea to create a pull request to mention it in README?

**Comment by niemeyer** [comment]
Thanks for the pointer, and I'm glad this works out for you. I'd prefer not to maintain a link list in the README, but I'll point anyone asking towards it, and this issue will also survive as a reference.
