### ISSUE TITLE
Duplicate keys are not handled properly

### ISSUE THREAD

**Issue by kostrahb** [go-yaml/yaml#623]
[YAML spec in version 1.2](https://yaml.org/spec/1.2/spec.html) says that in a valid YAML file, mapping keys “MUST” be unique.

However, I see that v3 of this library parses all the keys into the tree structure.

```
package main

import (
	"fmt"
	"gopkg.in/yaml.v3"
)

var deviated = `a:
  - b
  - c
a:
  q: a
  q: b
`

func print(root *yaml.Node, num int) {
	fmt.Printf("%v: %#v\n", num, root)
	for _, child := range root.Content {
		print(child, num+1)
	}
}

func main() {
	root := &yaml.Node{}
	err := yaml.Unmarshal([]byte(deviated), root) // Should return either same structure as for string {a: {q: b}}, which is the most logical representation of the data above or some error
	if err != nil {
		panic(err) // will not panic with current state of library
	}
	print(root, 0)
}
```

**Comment by niemeyer** [comment]
If you actually try to decode the intermediate representation, you should get this:
```
panic: yaml: unmarshal errors:
  line 4: mapping key "a" already defined at line 1
```
If that's not the case, please let me know.

**Comment by wslaasya** [comment]
Is there an option to ignore the duplicate fields and parse it to the latest field in Yaml?

We have a scenario where some of the yaml templates are configured with duplicate keys by mistake. The Java snakeyaml peoject is ignoring duplicates whereas here we see the error
