### ISSUE TITLE
Trailing commas should not be allowed when unmarshalling JSON strings.

### ISSUE THREAD

**Issue by aaronjheng** [go-yaml/yaml#630]
Per JSON spec, trailing commas is not allowed.
```
{
   "k1": "v1",
   "k2": "v2",
}
```
But `yaml.Unmarshal` can't dectect such errors. Is it a bug or by design?

**Comment by niemeyer** [comment]
That's YAML, not JSON, which is why it doesn't fail. If you want strict JSON, the encoding/json package will properly validate it for you.
