### ISSUE TITLE
Failing builds because of gopkg.in/yaml.v2 dependency

### ISSUE THREAD

**Issue by sranka** [go-yaml/yaml#631]
Hi folks, this is the second time in the last 5 days that my build fails without changes in my code because of a failure in external dependency. The gopkg.in service now does not proxy well to github, the builds are failing with:

```
go: gopkg.in/yaml.v2@v2.2.7: unrecognized import path "gopkg.in/yaml.v2" (parse https://gopkg.in/yaml.v2?go-get=1: no go-import meta tags ())
```

https://gopkg.in/yaml.v2 that ends up with:

```
Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: dial tcp: lookup github.com on 127.0.0.53:53: no such host
```

I already informed gopkg.in about this. It might be better to depend on github directly, since the gopkg.in service only adds another layer of possible failure. I am curious, is there any value for you to use gopkg.in?

**Comment by niemeyer** [comment]
Looks like a temporary error. I can still go get it fine from here.

**Comment by sranka** [comment]
yes, it was about 2 hours
