### ISSUE TITLE
Trailing spaces force quoted string encoding

### ISSUE THREAD

**Issue by Alexbyy** [go-yaml/yaml#648]
I use yaml.Unmarshal to Unmarshal a file.
![image](https://user-images.githubusercontent.com/27987483/89635846-37459a80-d8da-11ea-9e16-55a0242f8c56.png)

![image](https://user-images.githubusercontent.com/27987483/89635310-5f80c980-d8d9-11ea-9dfa-89835fcba3e6.png)

The file is as follows:
![image](https://user-images.githubusercontent.com/27987483/89635220-3a8c5680-d8d9-11ea-867a-da32ee3ed740.png)

 Then I change the struct
				
![image](https://user-images.githubusercontent.com/27987483/89635751-167d4500-d8da-11ea-9e99-7d26eb84abad.png)

Then I use Marshal to reverse it:
![image](https://user-images.githubusercontent.com/27987483/89635774-1f6e1680-d8da-11ea-9b31-eeed93d21fad.png)

The output is as follows:
![image](https://user-images.githubusercontent.com/27987483/89635571-c1413380-d8d9-11ea-9eb9-6c8f0b974511.png)
the output is Completely messed up，Who can tell me How can I preserve the  original format?
I expect the output looks like that:
![image](https://user-images.githubusercontent.com/27987483/89635959-65c37580-d8da-11ea-984d-b8ef2f02e93b.png)
Many thanks!

**Comment by niemeyer** [comment]
The yaml package will already format it as suggested automatically, as long as the string contains newlines. The fact this heuristic is not working for your case probably implies that the content being marshaled contains unusual characters that had to be quoted to be parsed properly.  Can you please provide a reproducer using https://play.golang.org so we can look into it?

**Comment by Alexbyy** [comment]
https://play.golang.org/p/L_V8Zhx2Auc
Thank you very much!
I find when I use Backticks such as `some words` rather than Double quotes such as "some word"，the output will mess up.
And when I put a "\n" in a string,the output will also mess up,For example,when I use "some \n words" rather than "some words",the out put will mess up.
I expect to insert a format string.Would you tell me how to solve this problem?

**Comment by niemeyer** [comment]
Your _str2_ Go literal has invisible trailing spaces:
```
fmt.Printf("%q\n", str2)
```
Output:
```
"   \nkey namespace_name\npattern %s\n"
```
The yaml encoder currently avoids marshaling it out as a plain scalar because, just like in your Go source code, this makes the data invisible. If the Go string is fixed to not have trailing spaces, the yaml output will look like what you seem to expect.
