### ISSUE TITLE
v3: Comments for map entries with blank values get associated to the map key

### ISSUE THREAD

**Issue by mikefarah** [go-yaml/yaml#656]
Comments for map entries that have no values:

```rules: # hi```

Are being associated to the key nodeValue 'rules' rather than the value nodeValue.

See https://play.golang.org/p/cRaD_ByfFg9 for reference.

This means when I use this library to decode the yaml, update the 'rule' value, and re-encode it invalid yaml gets produced:

```
rules: # hi
another: entry
```

Result:

```
rules: # hi
    great
    another: entry
```

https://play.golang.org/p/rg_PQKqVT9f

**Comment by mikefarah** [comment]
@niemeyer this is producing invalid yaml - any thoughts?

**Comment by niemeyer** [comment]
Hello Mike,

Thanks for reporting the issue. I'll get it fixed.

**Comment by niemeyer** [comment]
@mikefarah Hey Mike, sorry it took me a while to allocate time for v3 again, but here I am.

With 496545a we should have better handling of inline comments under map keys in this and other similar scenarios.

Please let me know if you stumble on any other issues.

**Comment by mikefarah** [comment]
Thanks @niemeyer - can confirm this worked
