### ISSUE TITLE
v3: float encoding is too scientific

### ISSUE THREAD

**Issue by bangzek** [go-yaml/yaml#669]
I used yaml to encode large digits number in `float64`, but apparently the float-to-string use default **%g** precision (6 digits) instead maximizing precision for human consumption.

See https://play.golang.org/p/-ap9xKINc_g for details.

According to [stackoverflow](https://stackoverflow.com/questions/56514892/so-exactly-how-many-digits-can-float8-float16-float32-float64-and-float128-c), it's about **6-9** for `float32` and **15-17** for `float64`

**Comment by rogpeppe** [comment]
The `%g` verb uses as many digits as are necessary, not just 6.

From [the documentation](https://golang.org/pkg/fmt/):

> The default precision for %e, %f and %#g is 6; for %g it is the smallest number of digits necessary to identify the value uniquely.

In other words, if `%g` is used, you can always get exactly the same value back again.

Here's an example: https://play.golang.org/p/0P7FkwxLj4N

**Comment by bangzek** [comment]
@rogpeppe please read the doc carefully:

> **The default precision for %e, %f and %#g is 6**

The value is the same but I'm complaining the presentation

**Comment by niemeyer** [comment]
We use this logic precisely so that we can make the presentation nice on both ends of the spectrum. For example, it outputs both 1e20 and 1.234567 in that respective style. Now, you'll likely find cases that you'd want to see one way or the other in the middle of that spectrum, but unless you have a more concrete proposal we can't do much about this without hurting precisely the good presentation which you're looking for.

**Comment by bangzek** [comment]
Well the simplest thing just follow what encoding/json do, they don't use
%g but selectively choose %f or %e depend on the number.

Pada tanggal Sel, 10 Nov 2020 18.06, Gustavo Niemeyer <
notifications@github.com> menulis:

**Comment by niemeyer** [comment]
It will also happily format 1e18 as 1000000000000000000. I'm happy to improve things, but this isn't it.

**Comment by bangzek** [comment]
Most people would expect that.

Well it's opensource, I prefer to make my software cater to normal people
instead some elitist programmer.


Pada tanggal Sel, 10 Nov 2020 20.33, Gustavo Niemeyer <
notifications@github.com> menulis:

**Comment by niemeyer** [comment]
A key sign of elitism is the inability to hold up a respectful and productive conversation.

Have a good day.

**Comment by rogpeppe** [comment]
For the record, encoding/json originally just used `FormatFloat`, but the behaviour was changed deliberately to be more consistent with other JSON encoders in https://github.com/golang/go/commit/92b3e3651dc44f54b458f171f641779f10fbaec0

For the record, I quite like the current JSON behaviour, but the representation of large exact orders of magnitude indeed isn't ideal. As so often, it's a trade-off with no single correct way to do things.
