### ISSUE TITLE
v3: Inline Marshalers are ignored

### ISSUE THREAD

**Issue by campoy** [go-yaml/yaml#672]
Types that satisfy the `yaml.Marshaler` interface are not taken into account as marshalers when they're inline.

This short [playground snippet](https://play.golang.org/p/RbkhCWDTl7o) reproduces the issue:

```go
package main

import (
	"log"
	"os"

	"gopkg.in/yaml.v3"
)

type marshaler struct {
	Hidden bool
}

func (m marshaler) MarshalYAML() (interface{}, error) {
	return struct{ Marshaled bool }{true}, nil
}

func main() {
	inline := struct {
		A         int
		Marshaler marshaler `yaml:",inline"`
	}{A: 1}

	if err := yaml.NewEncoder(os.Stdout).Encode(inline); err != nil {
		log.Fatal(err)
	}
}
```

Given the fact that `marshaler` satisfies the `yaml.Marshaler` interface, the output should be:

```yaml
a: 1
marshaled: true
```

But instead, we get the field `Hidden`, and the output becomes:

```yaml
a: 1
hidden: false
```

If we remove the `",inline"` annotation, the marshaler is correctly handled and the output becomes:

```yaml
a: 1
marshaler:
  marshaled: true
```

**Comment by niemeyer** [comment]
Yeah, that's indeed how the feature works at the moment, per docs:
```
inline       Inline the field, which must be a struct or a map,
             causing all of its fields or keys to be processed as if
             they were part of the outer struct. For maps, keys must
             not conflict with the yaml keys of other struct fields.
```
We may change that eventually, but the current priority is to stabilize current v3 and obsolete v2.
