### ISSUE TITLE
v3: Weird behavior, Unmarshal worked on field 'Welcome' but not on 'WelcomeTime'

### ISSUE THREAD

**Issue by tubzby** [go-yaml/yaml#676]
Please check out a simple Unmarshal playgroud: https://play.golang.org/p/OTf1ul9OkOB

In short, In a structure:
```golang
type TT struct {  
  Welcome string   
  WelcomeTime string  
}
```
the field "WelcomeTime" is not set by yaml.Unmarshal, very strange. Any body can help?

**Comment by niemeyer** [comment]
Per the docs of [Unmarshal](gopkg.in/yaml.v3#Unmarshal):
> Struct fields are only unmarshalled if they are exported (have an upper case first letter), and are unmarshalled using the field name lowercased as the default key. Custom keys may be defined via the "yaml" name in the field tag: the content preceding the first comma is used as the key, and the following comma-separated options are used to tweak the marshalling process (see Marshal). Conflicting names result in a runtime error.
