### ISSUE TITLE
Incorrectly allows usage of anchors before they are defined

### ISSUE THREAD

**Issue by kisielk** [go-yaml/yaml#68]
The yaml package allows an anchor to be dereferenced before it's defined, eg:

```
foo:
  <<: *bar

bar: &bar
```

while it could be argued it's convenient that this works, it's not in line with the yaml spec and other yaml parsers.

**Comment by niemeyer** [comment]
Given that it actually decodes it correctly, it doesn't feel like breaking it would benefit anyone.

As an aside, the provided example is invalid YAML. It errors with:

```
yaml: map merge requires map or sequence of maps as the value
```

**Comment by kisielk** [comment]
I was a bit lazy with the example, should have put some keys in the dictionaries :)

Anyway according to the spec *bar should only be used in future occurrences after &bar, see http://www.yaml.org/spec/1.2/spec.html#id2785586

We had some real cases where this caused problems, there were yaml files we were using with Go programs that worked fine but the same files would fail to parse with the Python yaml parser which was more true to the spec. A fairly easy fix of course but since our Go tools will never warn us about this error in the future there's the chance it will happen again.

**Comment by niemeyer** [comment]
It doesn't seem fair to attribute that problem to the fact Go _can_ handle these files. If the package was _generating_ broken files, then I'd agree this was a problem, but that's not the case.
