### ISSUE TITLE
zapcore.Level unrecognized

### ISSUE THREAD

**Issue by goctl** [go-yaml/yaml#680]
type Log struct {
	Level               zapcore.Level `yaml:"level"`
}
config.yaml setting:
log:
    level: -1

error:
yaml.Unmarshal get unrecognized level: "-1" error.

**Comment by Wshuhao001** [comment]
I use inline solve it.

**Comment by niemeyer** [comment]
This looks like some issue in a library using the yaml package. There's no "level" in go-yaml.

If that's incorrect somehow, please provide a small self-contained sample we can have a look at.
