### ISSUE TITLE
`omitempty` on map values?

### ISSUE THREAD

**Issue by kevin-hanselman** [go-yaml/yaml#683]
I have a map of strings to struct pointers (the map key type isn't particularly important). I'd like to the resulting marshalled YAML to be bare keys, without `{}` or `null` values. I've looked over the documentation for this project and I'm not sure this is possible. Can someone confirm?

Here's a minimal example:

([Go Playground URL](https://play.golang.org/p/zmofJDa_Fmv))

``` go
package main

import (
	"gopkg.in/yaml.v2"
	"os"
)

func main() {
	type Item struct {
		value string
	}
	type Container struct {
		Items map[string]*Item
	}
	
	c := Container{
		Items: map[string]*Item{
			"foo": {},
			"bar": nil,
		},
	}
	
	yaml.NewEncoder(os.Stdout).Encode(c)
}
```

Actual output:
```
items:
  bar: null
  foo: {}
```

Wanted output:
```
items:
  bar:
  foo:
```

I'd even be OK with just one or the other of the zero-value struct (map key `foo`) and the null pointer (map key `bar`) serializing to an empty string.

**Comment by niemeyer** [comment]
You should be able to do that using the yaml.Node type from v3, as it allows you to decorate the actual representation of the value as you please.

If that doesn't work, please let me know.
