### ISSUE TITLE
v3: Comment inside array gets dropped

### ISSUE THREAD

**Issue by mikefarah** [go-yaml/yaml#686]
The empty lines (before key_bindigs and after the comment) make the comment disappear, removing either of the empty lines brings the comment back:

```yaml

key_bindings:
# (Windows/Linux only)

  - { key: L }
```

See

https://play.golang.org/p/6pDxVwSBOPh

**Comment by niemeyer** [comment]
This should be fixed with c476de3. Please let me know if it isn't.

**Comment by mikefarah** [comment]
Thanks @niemeyer - can confirm this worked
