### ISSUE TITLE
Feature request: Keeping leading spaces on comments

### ISSUE THREAD

**Issue by albertvaka** [go-yaml/yaml#688]
Keeping preceding whitespace on comment lines would allow indented blocks of code to preserve their hierarchy. 

As an example, reading and writing this file:
```
# subsection:
  # meaning_of_life: 42
```
currently results in:
```
# subsection:
# meaning_of_life: 42
```

**Comment by niemeyer** [comment]
This is a bit atypical, in yaml or otherwise, and as such probably not worth encouraging. I'd instead recommend doing this:
```
# subsection:
#     meaning_of_life: 42
```

**Comment by albertvaka** [comment]
To me, comments are ignored starting from the comment char. Anything before that, specially in a file format where spacing matters, should be preserved.
