### ISSUE TITLE
can not pare $ placehoder

### ISSUE THREAD

**Issue by wzhsh90** [go-yaml/yaml#696]
this is my yaml file 
table_name:
  sys_company_t
exist_name:
  select count(*) from ${table_name} where com_name=#{name}

func main() {
	t := make(map[string]string,0)
	err := yaml.Unmarshal([]byte(data), &t)
	if err != nil {
		log.Fatalf("error: %v", err)
	}
	fmt.Printf("--- t:\n%v\n\n", t)

}
print:

map[exist_name:select count(*) from ${table_name} where com_name=#{name} table_name:sys_company_t]

the ${table_name} not parse the right data.

**Comment by niemeyer** [comment]
Your expectation almost certainly comes from a tool that was reading the data from a YAML file and processing further.  Such placeholders are not part of YAML itself.
