### ISSUE TITLE
Partial use of UnmarshalYAML

### ISSUE THREAD

**Issue by vanbroup** [go-yaml/yaml#717]
I'm trying try to replicate the following `UnmarshalJSON` implementation with `UnmarshalYAML` to allow transferring yaml comments from the `yaml.Node` to a variable in the struct without duplicating or filling the whole struct manually using `yaml.Node` (how it's often demonstrated).

```go
func (d *Data) UnmarshalJSON(data []byte) error {
	log.Println("UnmarshalJSON Data")
	type alias *Data
	err := json.Unmarshal(data, alias(d))
	if err != nil {
		return err
	}
	d.AA = "AA Test"
	return nil
}
```
Complete (working) example: https://play.golang.org/p/fQCb4EE-fZk

Unlike `UnmarshalJSON`, the `UnmarshalYAML` expects a node, which means we can't create the exact equivalent.
`UnmarshalYAML(value *Node) error`. 

Using `node.Decode(alias(d))` results in a loop:

```go
func (d *Data) UnmarshalYAML(node *yaml.Node) error {
	log.Println("UnmarshalYAML Data")
	type alias *Data
	err := node.Decode(alias(d))
	if err != nil {
		return err
	}
	d.AA = "AA Test"
	return nil
}
```
Complete (failing) example: https://play.golang.org/p/T3946oeees1

**Comment by humandad** [comment]
I'm having this same issue. Wondering if anyone has any ideas.

For my particular use case, I just want to inspect the `*yaml.Node` and check some things about my destination struct, if there's a problem, I want to return an error, otherwise, just continue with the regular unmarshaling process. The only way I can think to do this is to make a complete copy of the struct.

**Comment by ghost** [comment]
Any update on this Issue?

**Comment by nolotz** [comment]
Won't work for everyone:

```go
func (d *Data) UnmarshalYAML(node *yaml.Node) error {
	type alias Data
	var da alias

	err := node.Decode(&da)
	if err != nil {
		return err
	}
	*d = Data(da)
	return nil
}

```

**Comment by mark-kubacki** [comment]
```go
func (d *Data) UnmarshalYAML(node *yaml.Node) error {
	type alias Data
	bereftOfMethods := (*alias)(d)

	return node.Decode(&bereftOfMethods)
}
```

**Comment by vanbroup** [comment]
I have updated the example using the suggestion from @wmark above which seems to work:

https://go.dev/play/p/piJlvG_HQrT

**Comment by macdabby** [comment]
I just came across this same problem and thought I'd put in my 2 cents. The approach @vanbroup mentions works, unless you have a type that can't be unmarshaled. I have a field that uses an interface type that can not be unmarshaled automaticaly and fails. So another way that works is to use an embedded struct and unmarshal on that. This works:

```
type Main struct {
     Sub
     Custom CustomInterface
}
type Sub struct {
     Field1 `yaml:"field1"`
}

func (m *Main) UnmarshalYAML(n *yaml.Node) error {
	err := n.Decode(&m.Sub)
        m.Custom = ...
}
```
