### ISSUE TITLE
Any options about not change struct field name by default?

### ISSUE THREAD

**Issue by bronze1man** [go-yaml/yaml#73]
Any options about not change struct field name by default?
I create a yaml library that fork form this one myself with a struct field name not change by default.

I think name style change stuff make everything complex.
I just want a kiss yaml library.

https://github.com/bronze1man/kmg/tree/master/encoding/kmgYaml
http://godoc.org/github.com/bronze1man/kmg/encoding/kmgYaml

**Comment by niemeyer** [comment]
No, there are no such options at this time, and we cannot have a global flag to switch as that would render other importers incompatible. We may think about changes at some point, but right now the change is still not in sight.

**Comment by bronze1man** [comment]
Thanks for your feedback.
I have to use my own fork right now.
