### ISSUE TITLE
issues with tags?

### ISSUE THREAD

**Issue by charleslaw** [go-yaml/yaml#74]
I haven't dug into this as I am new to go, but I could not parse a yaml file that began with:

```
%YAML 1.1
%TAG ! tag:google.com,2009:test/
```

When I removed the %Tag line, it worked.

**Comment by charleslaw** [comment]
I believe it is a http://yaml.org/spec/1.2/spec.html#id2785512 tag issue.  Changing ! to !yaml! also works.

**Comment by rogpeppe** [comment]
The following program now seems to work OK, so this seems to have been fixed.

	package main
	
	import (
		"log"
	
		yaml "gopkg.in/yaml.v2"
	)
	
	var d = `
	%YAML 1.1
	%TAG ! tag:google.com,2009:test/
	---
	hello
	`
	
	func main() {
		var x interface{}
		if err := yaml.Unmarshal([]byte(d), &x); err != nil {
			log.Fatal(err)
		}
		log.Println(x)
	}
