### ISSUE TITLE
Unmarshal doesn't return error when input not yaml

### ISSUE THREAD

**Issue by spyroot** [go-yaml/yaml#757]
Hi Folks,

It looks like Unmarshal doesn't produce errors when input contains valid JSON and input is generic interface io.Reader. In this example, input is JSON. If I understood correctly, it is expected behavior since it does the best effort and JSON file doesn't violate yaml spec,  (I'm no 100 sure), but the question is how to test if it is not yaml input at all? 

If I swap, it still breaks logic; imagine input is invalid JSON,  JSON parser will return an error.
I attempt to read it as yaml but yaml. Unmarshal never returns an error.

```

funcSpecsFromString(str) (*T, error){
	r := strings.NewReader(str)
      return  ReadSpec(r)
}

func ReadSpec(b io.Reader) (*T, error) {

	var spec T

	buffer, err := ioutil.ReadAll(b)
	if err != nil {
		return nil, err
	}

	err = yaml.Unmarshal(buffer, &spec) // <---- this should return error no If input is json
         if err == nil {
		return &spec,  nil
     }

     err = json.Unmarshal(buffer, &spec) 
     if err == nil {
		return &spec, nil
	}
```

**Comment by perlpunk** [comment]
That's expected. JSON is a subset of YAML 1.2, so it shouldn't return an error.
