### ISSUE TITLE
unexpected unmarshal result for JSON object

### ISSUE THREAD

**Issue by u2d9c9117** [go-yaml/yaml#771]
First of all, thank you for your work on this library. I am also not as familiar with YAML as many of the authors will be. That said, using v3, I found that 

```
yaml.Unmarshal([]byte(`{a:b, c:"d", "e":f, "g":"h", i: j, k: "l"}`), &output)
```

returns an unexpected result, here shown as the output of json.Marshal:

```
{"a:b":null,"c:\"d\"":null,"e":"f","g":"h","i":"j","k":"l"}
```

This assumed that JSON is valid YAML. Note also that the above input should have had all the names/keys quoted.

In cases where:

1. the name/key is not quoted *and*
2. the value is not separated by whitespace from the name/key

The key/value pair is treated as a key, with a null value. I would have expected either an error (due to the missing quoting of the object name strings), or for the missing quotes to be ignored.

Could you please clarify if this is intentional?

**Comment by cbandy** [comment]
> In cases where:
> 
> 1. the name/key is not quoted _and_
> 2. the value is not separated by whitespace from the name/key

The spec is clear that `a:b` is not a key/value pair: https://yaml.org/spec/1.2.2/#flow-mappings

> Normally, YAML insists the “`:`” mapping value indicator be separated from the value by white space. … It is also a potential source for confusion as “`a:1`” is a plain scalar and not a key/value pair.

In the example after that paragraph, the spec also shows that
`{ https://foo.com, omitted value:, }` should be parsed to mean
`{ "http://foo.com": null, "omitted value": null }`.

**Comment by u2d9c9117** [comment]
Thanks @cbandy for taking the time to point that out. My bad, I totally missed that when I first looked into it.
