### ISSUE TITLE
gopkg.in/yaml.v2 is 503 Service Unavailable

### ISSUE THREAD

**Issue by stevenwijaya2** [go-yaml/yaml#781]
i can't run go get gopkg.in/yaml.v2 or access https://gopkg.in/yaml.v2
and get 503 service unavailable

thanks
![image](https://user-images.githubusercontent.com/62003980/132648769-70dffec8-aa27-4325-9fa2-f3c4d4cf6eef.png)

**Comment by jesussancheztellomm** [comment]
Same here

**Comment by Tioborto** [comment]
Seems to be up and running 👍

**Comment by stevenwijaya2** [comment]
i think they already solved it

**Comment by niemeyer** [comment]
There was an outage today indeed. You can see the status here:

https://status.canonical.com/

Was fixed by the 24x7 team before I even realized it. Thanks to them.
