### ISSUE TITLE
yaml.v3: how can I use yaml.Node to reproduce a node's content verbatim after unmarshalling?

### ISSUE THREAD

**Issue by andig** [go-yaml/yaml#785]
Unmarshaling into a `yaml.Node` I can get the node's original content using `node.Content`. However, this only affects the current node but not its child nodes (`Content []*Node`).

Is there a way to reconstruct the entire node's content including child nodes?

**Comment by we4tech** [comment]
Hi @andig,

This PR #726 was intended to solve that problem. We haven't made any progress getting into the merged state. @taustgen-wework worked on that earlier on.

**Comment by andig** [comment]
Thank you. Waiting for progress there.
