### ISSUE TITLE
Is this (v3) repo still maintained?

### ISSUE THREAD

**Issue by mikefarah** [go-yaml/yaml#788]
Are you looking for new contributors? Has someone made a more active fork?

**Comment by niemeyer** [comment]
Yeah, I still look after it. I just haven't had as much time for it in the last year.

**Comment by mikefarah** [comment]
Yeah fair enough, thanks for all your work too!   I must admit that I worry a little that it all comes down to a single person.
________________________________

**Comment by niemeyer** [comment]
Yeah, I understand the concern. I'm sure someone will pick it up if I drop it completely, but that's not the case right now.

In truth, that's one of the things I have never managed to fix in my open source projects, and I perceive that as a common issue elsewhere too. The high profile projects I'm responsible for end up with investment and proper quality teams, and take a lot of attention. My niche projects end up with just me, and in the few cases I tried to open up to co-maintainers, I ended up paying the price a few years later, either by having to spend significant time to bring the project back on track, or with it just dead.

So the only functional way I found of keeping projects like this in a healthy state that everyone can rely on is by doing work in bursts. A few days to a couple of weeks at a time, usually.

Even then, I realize it can be frustrating to be on the other side waiting for the action. But that's what I can manage, at least right now, to keep this 10+ years foundational project going.

**Comment by TristanSpeakEasy** [comment]
Is it worth reopening this ticket and looking for new maintainers? The issues and PRs are piling up and this is a critical package in a lot of downstream software

**Comment by andig** [comment]
@niemeyer would you consider onboarding more maintainers? It has been another two years since the last update and there are a couple of worthy PRs waiting for review.

**Comment by niemeyer** [comment]
There are 128 PRs, most of them worth of consideration, but many of them likely not proper, at least yet.  What we need is a proper team to maintain this project as part of their job, with good oversight (we don't want another xz), and that's what I've been working on, attempting to organize a team at Canonical for this.  That, or I move out from my current job and get more time again. Well, or the upstream Go team takes it over.  I don't have the means to onboard one-off maintainers right now.
