### ISSUE TITLE
Setter not working on non-pointer fields

### ISSUE THREAD

**Issue by ewalk153** [go-yaml/yaml#8]
I'm working out how to parse and encoding time.Time in YAML.

I have a prototype for marshal but I'm stuck on how to unmarshal a time.Time.

Can anyone suggest a starting point?

I'm happy to submit a PR if it's interesting. 
https://github.com/ewalk153/yaml/tree/add_time_marshal

**Comment by ewalk153** [comment]
I'm also confused by the Setter interface; it appears that it can only be used in conjunction with pointer fields.

Here is a simple example:
https://gist.github.com/ewalk153/11043842

**Comment by spf13** [comment]
I found the same issue and was beginning to draft a similar fix. If you can send this as a PR it would help me... even if it's only the first half of the entire solution.

**Comment by ewalk153** [comment]
Pull request for time.Time -> YAML encoding https://github.com/go-yaml/yaml/pull/10

**Comment by ewalk153** [comment]
So far, I haven't figured out the YAML -> time.Time decoding.

**Comment by niemeyer** [comment]
I'm changing the subject to reflect the pointer bug. We have #10 covering the time.Time support.
