### ISSUE TITLE
Client timeout while awaiting headers - Cannot talk to Github

### ISSUE THREAD

**Issue by aagamdoshi** [go-yaml/yaml#800]
![image](https://user-images.githubusercontent.com/13047898/141744969-6b8a4703-ad4a-4ff1-9d80-592861dbf631.png)

go: downloading github.com/go-task/task/v3 v3.9.0
go: downloading github.com/go-task/task v1.4.4
go install github.com/go-task/task/v3/cmd/task@latest: github.com/go-task/task/v3@none updating to
	github.com/go-task/task/v3@v3.9.0 requires
	**gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Bad Gateway
	server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)**

**Comment by g-marius** [comment]
noticing this here also for gopkg.in/yaml.v2, looks like a repeat of niemeyer/gopkg#63

**Comment by niemeyer** [comment]
Yeah, this is not gopkg.in being down, but github.com itself failing to respond appropriately.

We're looking into it. Please see niemeyer/gopkg#63 for any follow ups.

**Comment by ipstas** [comment]
one more time:
`go get gopkg.in/yaml.v3
package gopkg.in/yaml.v3: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Bad Gateway
        server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
`

**Comment by vinayak-kukreja** [comment]
> one more time: `go get gopkg.in/yaml.v3 package gopkg.in/yaml.v3: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Bad Gateway server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers) `

+1, if other's are experiencing this, could this be reopened?
