### ISSUE TITLE
Panic when parsing "! !00 \xf6" string

### ISSUE THREAD

**Issue by prymitive** [go-yaml/yaml#833]
Found via fuzzing tests added to Go 1.18

```go
package main

import (
	"fmt"

	"gopkg.in/yaml.v3"
)

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Printf("panic: %s", r)
		}
	}()

	var node yaml.Node
	yaml.Unmarshal([]byte(string("! !00 \xf6")), &node)
}
```

https://go.dev/play/p/28Dlf2ncCct

**Comment by Zenithar** [comment]
Same with `string("! !!0 \xf7")`

**Comment by tcarreira** [comment]
I think this issue is fixed already.
At least the [example](https://go.dev/play/p/28Dlf2ncCct) you gave passes fine with no panic.

**Comment by prymitive** [comment]
#666 fixed it

**Comment by dolmen** [comment]
@prymitive Could you submit your fuzzing code?
