### ISSUE TITLE
Travis project not found

### ISSUE THREAD

**Issue by munrocape** [go-yaml/yaml#84]
It appears that the build on Travis is cannot be found. I've attached two screenshots - from GitHub itself and the linked Travis page.

![screen shot 2015-02-18 at 4 59 28 pm](https://cloud.githubusercontent.com/assets/916774/6256549/9676a156-b78f-11e4-9380-d58a6de555be.png)

![screen shot 2015-02-18 at 5 01 53 pm](https://cloud.githubusercontent.com/assets/916774/6256599/df3a5770-b78f-11e4-830e-58f78b979b88.png)

**Comment by niemeyer** [comment]
This has been sorted out.
