### ISSUE TITLE
yamlv2 will enter a new line when my string is too long, how can i cancel this ?

### ISSUE THREAD

**Issue by Yelijah** [go-yaml/yaml#848]
yamlv2 will make a new line when my string is too long, how can i cancel newline ? my string actually is command and has some spaces.

**Comment by laverya** [comment]
There's a long saga related to this particular issue. Short answer is to update to v3.  See #166 and #670 . You can also maintain a fork or use unexported variables via unsafe.

The change to the default line wrapping behavior was made to both v2 and v3, but v2 was rolled back after it broke a lot of kubernetes (and elsewhere) tests.

**Comment by Yelijah** [comment]
> 

Thank you for you answer!
