### ISSUE TITLE
Please support gccgo

### ISSUE THREAD

**Issue by dannf** [go-yaml/yaml#85]
I was trying to use a project built w/ go-yaml on arm64, which currently restricts me to using gccgo intead of gc. However, the test cases fail on this platform. This is apparently a known difference in behavior:
  https://github.com/golang/go/issues/7522

Is there an alternate way to code go-yaml to deal with both compilers?

**Comment by niemeyer** [comment]
Issue has been fixed upstream, apparently. Please reopen if you see issues.
