### ISSUE TITLE
v2 and v3 are not the same!

### ISSUE THREAD

**Issue by thinkerou** [go-yaml/yaml#865]
reproduce simple code: main.go
```
package main

import (
        "fmt"
        "log"

        "gopkg.in/yaml.v3"
)

var data = `
a: Easy!
b:
  c: 2
  d: [3, 4]
`

type YAML struct {
	Data interface{}
}

func main() {
         data := `
a : Easy!
b:
	c: 2
	d: [3, 4]
	`

        d, err := yaml.Marshal(data)
        if err != nil {
                log.Fatalf("error: %v", err)
        }
        fmt.Printf("--- t dump:\n%s\n\n", string(d))
}
```

v2 run the result:
```
➜  go run main.go
--- t dump:
"\na : Easy!\nb:\n\tc: 2\n\td: [3, 4]\n\t"

```

v3 run the result:
```
➜  go run main.go
--- t dump:
|4-
    a : Easy!
    b:
    	c: 2
    	d: [3, 4]

```

why? thanks!

**Comment by colega** [comment]
Why should they be the same? Both are valid, and it's a new major version.

I think the v3 results is more readable.

**Comment by thinkerou** [comment]
> Why should they be the same? Both are valid, and it's a new major version.
> 
> I think the v3 results is more readable.

I agree `more readable`, but what's `|4-`? thanks!

**Comment by colega** [comment]
See this:
- https://yaml.org/spec/1.2.2/#8111-block-indentation-indicator
- https://yaml.org/spec/1.2.2/#8112-block-chomping-indicator
- https://yaml-multiline.info/

It indicates that it's a block with literal style (`|`), indented by 4 spaces (`4`) and the strip chomping indicator (`-`) that means that the final newline should be stripped.
