### ISSUE TITLE
Does this support !!binary encoding

### ISSUE THREAD

**Issue by datianshi** [go-yaml/yaml#88]
Seems decoding works fine, wondering how the encoding works

Assume I have a struct

type Test struct {
         TestString string
 }

I want to marshal the struct to  yaml to have 

teststring: !!binary {64encoded string}

**Comment by niemeyer** [comment]
This is handled automatically. For example, this:

```
 data, err := yaml.Marshal(&Test{TestString: "\x80"})
```

will output this:

```
teststring: !!binary gA==
```
