### ISSUE TITLE
YAML inheritance broken when using yaml.MapSlice

### ISSUE THREAD

**Issue by mattes** [go-yaml/yaml#91]
See comments in code below:

``` go
package main

import (
    "fmt"
    "gopkg.in/yaml.v2"
)

var body = `
foo: &foo
  some: "var"

bar:
  <<: *foo
`

type Foobar struct {
    Foo interface{}
    Bar interface{}
}

func main() {
    // works as expected
    f := &Foobar{}
    if err := yaml.Unmarshal([]byte(body), &f); err != nil {
        fmt.Println(err)
    }
    fmt.Printf("%+v\n", f) // &{Foo:map[some:var] Bar:map[some:var]}

    // fails parsing yaml inheritance
    f1 := &yaml.MapSlice{}
    if err := yaml.Unmarshal([]byte(body), &f1); err != nil {
        fmt.Println(err)
    }
    fmt.Printf("%+v\n", f1) // &[{Key:foo Value:[{Key:some Value:var}]} {Key:bar Value:[]}]
    // expected: &[{Key:foo Value:[{Key:some Value:var}]} {Key:bar Value:[{Key:some Value:var}]}]
}
```

**Comment by amolokoedov** [comment]
Not yet fixed. Is there a patch for this?

**Comment by vinzenz** [comment]
@mattes @amolokoedov Would be cool if you could check that your use cases are covered with the PR I have sent

**Comment by rogpeppe** [comment]
@vinzenz I cannot find a description of the `<<` operator in any of the YAML 1.x specifications.

Should this actually be a supported feature?

**Comment by vinzenz** [comment]
@rogpeppe http://yaml.org/type/merge.html

**Comment by rogpeppe** [comment]
@vinzenz How many other "working drafts" are actually part of the YAML spec without being mentioned there? How is one supposed to know what YAML actually is without a full specification?

**Comment by vinzenz** [comment]
@rogpeppe Well I don't know, YAML is a beast ;-) I just added the support for MapSlice - Merge support was there already before

**Comment by hjdr4** [comment]
I need to use both merge and override and keep order.
Using https://github.com/vinzenz/yaml/commit/764aa8c1729663c83a7df36e1a68e81ca32ce8f1 I'm able to use merge with MapSlice but overriding a merged key does not work, keys are just duplicated.

**Comment by niemeyer** [comment]
I'd like to put a tombstone on this issue. MapSlice will die in v3, and be replaced by a much more flexible intermediate representation. I want to focus on that instead, and anyone that really wants such MapSlices and merges, which is not quite common, can move forward and migrate into it.

v3 is on the way and coming soon.

**Comment by cup** [comment]
https://github.com/drone/drone/issues/2323
https://github.com/drone/drone-cli/pull/103
https://github.com/go-swagger/go-swagger/issues/1193
https://github.com/go-yaml/yaml/issues/184
https://github.com/go-yaml/yaml/issues/344

https://github.com/go-yaml/yaml/issues/91
https://github.com/mikefarah/yq/issues/178
https://github.com/mikefarah/yq/issues/206
