### ISSUE TITLE
yaml key getting quoted for unknown reason

### ISSUE THREAD

**Issue by lirtistan** [go-yaml/yaml#917]
Hello,

iam new to Golang, so maybe this isn't a real issue, but iam gambling for a while now and tried some libraries (also Yaml v3) and found a strange behavior with marshaling of struct keys to yaml keys..

to understand what i mean, see the following example...

```console
enrico@ebony:~/Projects/golang/test1$ go version 
go version go1.18.1 linux/amd64
enrico@ebony:~/Projects/golang/test1$ cat go.mod 
module test1

go 1.18

require gopkg.in/yaml.v3 v3.0.1
enrico@ebony:~/Projects/golang/test1$ cat main.go 
```
```golang
package main

import (
	"fmt"
	"gopkg.in/yaml.v3"
)

type Point struct {
	X float32 `yaml:""`
	Y float32 `yaml:""`
	Z float32 `yaml:""`
}

func main() {
	point := &Point{1.3, .8, 3.}
	serialized_point, _ := yaml.Marshal(point)
	fmt.Printf("%s", serialized_point)
}
```
```console
enrico@ebony:~/Projects/golang/test1$ go run main.go 
x: 1.3
"y": 0.8                  # <-- key is quoted but why?
z: 3
```

what is wrong with that Y key?

i also tested it with an older v2 version (v2.4.0) of that library, the result is the same!!

**Comment by perlpunk** [comment]
The `y` is special in YAML 1.1 as it stands for `true` (as well as `yes`, `Yes`, `ON`, `on`, ...)
Have a look at all the definitions for special values in YAML 1.1 and 1.2: https://perlpunk.github.io/yaml-test-schema/schemas.html

**Comment by lirtistan** [comment]
But how can i avoid that, let me guess... i should give it a other name then, right!?

**Comment by lirtistan** [comment]
i close this case, but in my eyes its wrong to quote a key, because it matches on a possible truthy/falsy value.
