### ISSUE TITLE
Silently unmarshals JSON as well as YAML

### ISSUE THREAD

**Issue by GrantFleming** [go-yaml/yaml#926]
Due to a bug in my code, I discovered by accident that this library will happily unmarshal JSON as well as YAML. Yet there is no mention of this in [the documentation](https://pkg.go.dev/gopkg.in/yaml.v2).

This can be confusing and mask errors that would otherwise be caught (like forgetting to set an appropriate Accept header).

I think that at least one of the following changes needs to be made:

- update the library so that it does not silently handle JSON and returns appropriate errors instead
or
- update the documentation to reflect that this parser is not YAML specific and also works for JSON

**Comment by perlpunk** [comment]
For the record: JSON is a subset of YAML 1.2

**Comment by GrantFleming** [comment]
> For the record: JSON is a subset of YAML 1.2

I was today-years-old when I learned this. Not sure how this bit of info managed to pass me by for so long.
